### ISSUE TITLE
Metadata Backup

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#101]
Hi Daniel :)
I wanted to enable "Metadata Backup" option when I was connecting to a database.
I select the check box "Save model.bim backup here", but I couldn't choose backup address because the the button to choose the address was disabled. 
![image](https://user-images.githubusercontent.com/24508605/31432369-56b17b66-ae83-11e7-912e-c5eda0338263.png)

Thank you in advance,
Arman

**Comment by otykier** [comment]
That's a bug - for some reason many of the event handlers on the Preferences form have been removed. For example, the "Check for Updates" button on the "General" tab also doesn't work. Will fix in an upcoming release.

In the meantime, try to open the AppData\Local\TabularEditor\Preferences.json file in a text editor. There should be a property called "BackupLocation". Try to set this value directly in the file, and restart Tabular Editor:

```json
{
  ...
  "BackupLocation": "c:\\Test\\TabularEditorBackup",
  ...
}
```

Remember to put double backslashes ( \\ ) to separate folders, otherwise the JSON will be invalid.

**Comment by ArmanFalah** [comment]
Thanks,
I tried the way you said and it works well.
