### ISSUE TITLE
Find and replace window locks program

### ISSUE THREAD

**Issue by kbl42** [otykier/TabularEditor#103]
When I am in an expression, and haven't edited anything in the editor (greyed out accept/reject buttons), and then replaces anything, with ctrl-H, the program is locked, and I can't do anything, other than close the program through task manager.
There is no problem, if I edit the expression first, so it is in edit mode.

**Comment by otykier** [comment]
Thanks for posting this - the cause seems to be that the "x occurence(s) replaced" box is spawned *behind* the "Find and replace" box, when the expression editor is not in edit mode. And since the "x occurence(s) replaced" box needs to be dismissed by clicking "OK" or pressing Enter, it will seem like the program is locked. If you move the "Find and replace" box somewhere else before hitting "Replace all", you can see what I mean.

I will see if I can post a fix, so that the box will spawn as the top-most object instead. In the meantime - simply pressing Enter should solve the problem :-)

**Comment by otykier** [comment]
In addition, I discovered that both the Find text and the Find and replace box didn't work for the Advanced Scripting tab - this will also be fixed.
