### ISSUE TITLE
Export/import selection of properties/objects

### ISSUE THREAD

**Issue by marcosqlbi** [otykier/TabularEditor#106]
It would be nice to export (and possibly import) a set of properties for a selection of objects.
E.g.
- Measures: Table, name, DAX expression, format, description
- Calculated column: Table, name, DAX expression, format, description
...
The selection of attributes should be flexible.
The format should be CSV or XLSX
The idea is to enable "bulk" changes using Excel (where you can group by particular properties, e.g. Format string).
Adding also annotations would make this much more powerful, but a basic import/export would already provides value.

**Comment by otykier** [comment]
Hi Marco,
You can actually do this using the scripting functionality. Try for example this script, which will output some of the properties for the currently selected measures:

```csharp
var header = "Table\tType\tName\tFormatString\tDisplayFolder\tDescription\tIsHidden\tExpression\n";
var data = string.Join("\n",
    Selected.Measures.Select(m => string.Join("\t", new string[]{
        m.Table.Name,
        m.ObjectType.ToString(),
        m.Name,
        m.FormatString,
        m.DisplayFolder,
        m.Description.Replace("\n","\\n"),  // Avoids line breaks in Description
        m.IsHidden.ToString(),
        m.Expression.Replace("\n","\\n")    // Avoids line breaks in Description
    })).ToArray());
    
(header + data).Output();
```
Executing this script while a few measures has been selected in the Explorer Tree:
![image](https://user-images.githubusercontent.com/8976200/31963178-244e37f4-b900-11e7-9165-d7bce3e1a1ea.png)
Copy-pasting the output directly into Excel:
![image](https://user-images.githubusercontent.com/8976200/31963229-4ab176ae-b900-11e7-9689-2eb7365ce2f4.png)

That last line could be replaced with `System.IO.File.WriteAllText(@"c:\Demo\test.tsv", header + data);` to write the output directly to a file, and a similar (if slightly longer) script could be used to assign the properties from an input file.

Are you suggesting to have a UI to support this kind of operation?

**Comment by marcosqlbi** [comment]
I didn't realize you can already export using a script - thanks!
The import would require more code, so a UI for this could be useful. You could also read the columns in the import without requiring a particular selection. However, maybe it's a better idea to experiment with the scripts, and then defining requirements for a UI in case we see it could be valuable. We can create some script to test the water first...

**Comment by otykier** [comment]
I agree. Will provide some scripts for import as well as handling other object types tomorrow.

If it turns out to be useful, we can start by encapsulating the scripts in some simple method calls, so that developers can more easily invoke both export and import of any kind of object and property, and then some sample method calls to illustrate the usage could be added to the existing scripting samples. Then a UI might not be needed at all :-)

**Comment by marcosqlbi** [comment]
I completely agree. Who use this tool needs flexibility and productivity more than simple UI.

**Comment by otykier** [comment]
Hi Marco,

This ended up as a slightly longer post, so please bear with me. I've uploaded two scripts, which illustrate how this could work in general:

* [ExportProperties.cs](https://github.com/otykier/TabularEditor/blob/master/Scripts/ExportProperties.cs#L63-L69)
* [ImportProperties.cs](https://github.com/otykier/TabularEditor/blob/master/Scripts/ImportProperties.cs#L106-L107)

Most of the code in the scripts will be encapsulated as Extension Methods inside Tabular Editor in the next release, so the only thing a user needs to do, is to specify which objects they want to output, along with a comma-separated list of property names. This part is highlighted in the ExportProperties.cs link above. Here is how the output from Sample 2 would look like in Excel:

![image](https://user-images.githubusercontent.com/8976200/31984055-3b8ddc0c-b960-11e7-8067-ebae784db9af.png)

The first column ("Object") of the TSV data will contain a value that uniquely identifies the object within the model (this currently has some shortcomings which will be addresses in future releases). This greatly simplifies how the import works, since everything is self-contained in the TSV format. Object names can even be changed. It may also be interesting to let new objects be created this way, but this may only be viable for a subset of object types for now.

Note that Excel may sometimes add quotes to values in the .tsv file when saving. Since the import script does not expect the values to be quoted, it is actually [better to save the changes using a text editor](https://superuser.com/a/206097/307109) before importing in Tabular Editor.

As an example, we've changed the Name and DisplayFolder properties of two measures:
![image](https://user-images.githubusercontent.com/8976200/31999158-a8a14f54-b992-11e7-920b-94942b129075.png)

After importing in Tabular Editor, we notice that 8 changes were performed. This is more than the number of changes in the file, but it happens because we changed a name of a measure, that is also referenced by other measures, so Tabular Editor considers the automatic formula fixup that happens as an additional change. We can use the "Edit" > "Show history..." function, to view all changes made:

![image](https://user-images.githubusercontent.com/8976200/31999418-6d1354fe-b993-11e7-9a0b-b8d925dd7485.png)

When the next release is up, I will provide some simpler examples, that also shows how these scripts can be persisted as "Custom Actions" in Tabular Editor's UI, so that they are easier to invoke. Also, I will improve the underlying code that does the job of generating the output .tsv and parsing the input .tsv. Perhaps I will also add some format options, so that data may be serialized as other formats as well.

**Comment by otykier** [comment]
One more thing: You mentioned annotations as well. What would be the use case for this?

The reason I ask, is that annotations are not just a simply property on an object, but as you know, they can be anything, and so they are not well-suited to go into a flat tab-separated file. Would it be sufficient to have the JSON of the annotation outputted in the .tsv file, or would there be a need to output specific annotation values by their key?

**Comment by marcosqlbi** [comment]
Wow, this is more than was I was expecting in half a day!
This is going to be very useful.
The annotation is just an idea, I have to elaborate on this. But my thought is that if I generate the model from another tool, or if I decorate certain properties with additional metadata, I might want to be able to edit these properties in an easy way in the TSV file.
I understand that the flexibility would allow complex structures in an annotation, but what would make the import/export useful is the extraction/update of individual annotations made by a single attribute. 
For example, imagine a metadata saying "User Filter", which would allow an attribute to be available as a filter in a custom client (e.g. web page that generates DAX query based on a number of selections). Or an annotation that explains how to display the UI for the filter. If you create a custom application querying the Tabular model, you might want to add information to the model so that the client knows what to do without an external configuration.

**Comment by o-o00o-o** [comment]
This looks like a really awesome feature and could be used for our breaking changes process also.. 

I guess annotations could be done with some kind of prefix on the column heading name? e.g. "ANN.Relationships", "ANN.See Also" could be two Annotation entries. As long as the prefix convention was clear this would work really well for these sub list types.
