### ISSUE TITLE
more filtering options, viewing specific objects, table recreation

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#114]
1) ability to see only hidden objects
2) extend the filter pane to have different options: filtering by measure formula; filtering by the query text in a partition
4) ability to view only roles; only data sources; only tables and their partitions
5) ability to expand all within a folder (currently expand all expands every folder from the base model)
6) ability to create new table in tabular editor based on saved json (say you saved the create or replace script for a table...then deleted the table...and then want to put it back the easy way).

**Comment by kalmenk** [comment]
Just realized that number 5 is already available (just not drag & drop). However, when copying something that exists in the other tabular editor instance, it creates it as Object1 instead of Object (i.e. copying a table called 'Revenue' that exists in the other instance will paste it as 'Revenue1' - when you want it to replace the table).

Thanks so much Daniel!

**Comment by TabularEditor** [comment]
Great suggestions - they will all be included in 2.7. Regarding point 5, the behaviour will be changed so that when you paste a script that uses the "CreateOrReplace" TMSL command, it will replace an existing object with the same name. Pasting a script that uses the "Create" command, will create the object only if it does not already exist (a message will be displayed otherwise).

The JSON that is stored in the clipboard when copying an object from Tabular Editor using CTRL+C is neither of the above - it is not valid TMSL syntax, but it is needed for objects such as measures and columns, that can normally not be scripted individually. This will keep working the way it does today, so that if you subsequently paste this, the object will always be inserted regardless of whether it already exists - in that case, a number is added as you described above, instead of replacing existing objects (which is the behaviour users would normally expect from copy-paste operations).

**Comment by otykier** [comment]
Great suggestions - they will all be included in 2.7. Regarding point 5, the behaviour will be changed so that when you paste a script that uses the "CreateOrReplace" TMSL command, it will replace an existing object with the same name. Pasting a script that uses the "Create" command, will create the object only if it does not already exist (a message will be displayed otherwise).

The JSON that is stored in the clipboard when copying an object from Tabular Editor using CTRL+C is neither of the above - it is not valid TMSL syntax, but it is needed for objects such as measures and columns, that can normally not be scripted individually. This will keep working the way it does today, so that if you subsequently paste this, the object will always be inserted regardless of whether it already exists - in that case, a number is added as you described above, instead of replacing existing objects (which is the behaviour users would normally expect from copy-paste operations).

**Comment by otykier** [comment]
2.8 will have an improved Filter feature, that let's you use Dynamic LINQ (same as Best Practice Analyzer) to search for objects. The Filter textbox will continue to work as normally, but if you put a : (colon) as the first character, it will switch to Dynamic LINQ mode. So you could use expressions like:

- `:IsHidden = true` - shows only objects that are hidden
- `:Expression.Contains("TODO")` - shows only objects whose expression contains the word "TODO"
- `:ObjectType = "Role"` - shows only Role objects
- `:ObjectType = "Table" or ObjectType = "Partition"` - shows all tables and partitions

When using these expressions to search for objects, the Tree Explorer will switch to a non-hierarchical list view to display the results. Let me know what you think :-)
