### ISSUE TITLE
Show Dependencies feature addition

### ISSUE THREAD

**Issue by tilakdash** [otykier/TabularEditor#121]
Hi,

First of all, a big thanks for creating this tool. It's awesome!
However, there is one feature that would help while analyzing large models (such as one on which I had to work, which had 265+ tables) is that if in the "Show Dependencies" form, an option can be added for showing "how two specific tables are related". This will help developers analyze issues where the output from those two tables are not coming as expected.
For large models, tracing the relationships through SSDT "Diagram" View doesn't make sense at all.

Thanks & Congrats for creating this great tool!
TD

**Comment by otykier** [comment]
Hi TD,
I'm not a 100% sure what you mean. The "Show Dependencies" box already indicate the cardinality and cross-filtering directions of the relationships (as can be seen by the arrows and the 1's and n's):
![image](https://user-images.githubusercontent.com/8976200/33444706-4e11e320-d5fb-11e7-9f3b-3e2a63894abd.png)
Are you thinking about some kind of UI that allows you to select any two tables in the model, in order to trace the relationships and intermediate tables (if any) between them?

**Comment by tilakdash** [comment]
Yes, that's what I was looking for. Because for models with large number of tables, tracing the relationships between two tables can become a bit cumbersome. By the way, "Show Relationships" is already still better in this aspect than what comes with SSDT. But, adding this feature will allow for easier tracing.

**Comment by tilakdash** [comment]
I can also give you an example- I want to find the relationship between Table A & Table B.
Table A is directly related to 50 tables, but from those 50 tables, I am not really sure which tree I should follow so that it takes me to Table B. 
For now, I do these stuff by using TOM libraries, because manually tracing the path takes way too much time.

**Comment by otykier** [comment]
I see - now when tracing the relationships, I assume we only need to trace along the filtering directions?

So assuming the following model: 

- FactSales
   - (n <- 1) DimDate
   - (n <- 1) DimProduct
   - (n <-> 1) DimCustomer (bidirectional filter)

If you ask to trace the relationships from DimDate to DimCustomer it should show:

1. DimDate
2. FactSales
3. DimCustomer

But if you asked to trace the relationships from DimDate to DimProduct it should output that DimProduct is not filtered (directly or indirectly) by DimDate. Is my understanding correct?

**Comment by tilakdash** [comment]
Yes, you are right. Just to clarify a bit further. If you want to see the relationship between DimDate and DimProduct, then also, it should show- 
1.DimDate
2.FactSales
3.DimProduct
Reason being, even though DimProduct doesn't have a bidirectional filter associated, it still gets filtered from DimDate, because of measures (let's say, Product A doesn't have any measures associated to it for entire 2017. So, if you filter DimDate only for 2017, it will filter out Product A as well, as there are no measure values for Product A).

**Comment by o-o00o-o** [comment]
Hi guys, In using the relationship dependencies it does become a bit unwieldy for large models. I was thinking about something similar but have an option on the existing dialog to restrict so that it only allows flowing downstream or upstream only.

So instead of a massive tree if I view dependencies from a Dim table Dim 0

Dim 0
    (1 → n) Fact 1
        (n ← 1) Dim1 **(dont show this)**
        (n ← 1) Dim2 **(dont show this)**
    (1 ↔ n) Fact 2
        (1 → n) Fact 3
            (1 → n) Fact 4
        (1 → n) Fact 5
        (n ← 1) 'Dim 3 **(don't show this)**
etc

However if showing from a Fact you would want to see only upstream (arrows pointing in)

Fact 0
    (n ← 1) 'Dim Dates'
        (1 → n) Fact 1 **(dont show this)**
        (1 → n) Fact 2  **(dont show this)**
    (n ← 1) Dim 1
        (1 → n) Fact 3 **(dont show this)**
        (1 → n) Fact 4 **(dont show this)**
    (n ← 1) Dim 2
        (1 ↔ n) Fact 5
            (n ↔ 1) Dim 3
        (1 → n) Fact 5 **(dont show this)**
    (n ← 1) Fact 6
        (n ↔ 1) Dim 4
            (1 → n) Fact 7 **(dont show this)**
        (n ← 1) Dim 5
        (n ← 1) Dim 6
        (n ← 1) Dim 7
        (n ← 1) Dim 8

So I guess we need the ability to toggle between show all relationships, upstream only or downstream

Then with the ability to export to ascii - would this achieve what you need @tilakdash ?

**Comment by otykier** [comment]
Cleaning up old issues / things that are planned for Tabular Editor V3.
