### ISSUE TITLE
Source file could not be found

### ISSUE THREAD

**Issue by matal7** [otykier/TabularEditor#125]
when i want to run the application ill encounter  the following errors
Source file WrapperBase.generated.cs' could not be found
Metadata file TOMWrapper\bin\Debug\TOMWrapper.dll' could not be found

Thank you in advance

**Comment by otykier** [comment]
Hi matal7. It sounds like you are trying to compile the project yourself?
In that case, there are a couple of things to be aware of. First off, make sure you can run the T4 text template code generation on [this file](https://github.com/otykier/TabularEditor/blob/master/TOMWrapper/TOMWrapper/Base/WrapperBase.tt). In Visual Studio, you would normally right-click and choose "Run custom tool". This should create the WrapperBase.generated.cs file. If it doesn't work, it is likely due to the T4 file requiring the [Microsoft.AnalysisServices.Tabular](https://github.com/otykier/TabularEditor/blob/b6fa397bea429346b8ae3a8d1717bc534514118c/TOMWrapper/TOMWrapper/Base/WrapperBase.tt#L7) assembly to be registered in the GAC on your machine.
You can download the TOM assemblies [from here](https://go.microsoft.com/fwlink/?linkid=829578). Once you have them, use gacutil to register them in your GAC, and then try to build the project again.

**Comment by otykier** [comment]
Hi @matal7 - can you provide the information I requested above?

**Comment by otykier** [comment]
Closing this, as no additional information received.
