### ISSUE TITLE
When saving a model to a folder structure give relationships files a deterministic name

### ISSUE THREAD

**Issue by jaapp** [otykier/TabularEditor#126]
All files in the folder struc have a deterministic name, except for the relationships. These are random GUIDs.

![image](https://user-images.githubusercontent.com/3406948/36213218-75a4bdea-11a6-11e8-9b0e-48f9627d6b18.png)

One of the great function of saving to a folder is that you can compare different models with eachother using tools like WinMerge. It also makes it possible to, on a file system level, share objects between models.

The random nature of GUIDs inhibit a lot of this functionality.

![image](https://user-images.githubusercontent.com/3406948/36213439-006b2d60-11a7-11e8-8160-98838ce9778d.png)

**Comment by otykier** [comment]
Hi Jason,

The GUIDs are generated by the TOM, but we can control the names when serializing to a folder structure. Would you prefer that the name simply reflect the FromColumn, ToColumn and filter direction of the relationship (similar to how it is displayed in the UI), or would you rather have an option to supply your own name for each relationship?

In the former case, you should be aware that changing the FromColumn, ToColumn or direction of a relationship, will cause the old relationship file to be deleted, and a new one to be created (as the file name will have been changed). Will this be ok for your diff-tool?

Best regards,
Daniel

**Comment by skfd** [comment]
Just humble advice no to put direction in relationship name, because it will display same relationship as different in folder diff.

**Comment by otykier** [comment]
Hi @jaapp . I agree with @skfd that it would probably not be a good idea to put the direction of the relationship in the file name. For the same reason, one could argue that it wouldn't be a good idea to put the from- and to- columns in the file name. The GUIDs are not changed when you change a property on a relationship, but I understand that it can be an issue when browsing the file structure, as they appear in a completely random order in the file system.

Instead of using GUIDs, we can assign sequential names: "Relationship 1", "Relationship 2", etc... and then let you manually change these names. But still, this might not be what you want. Leaving this open for now - any suggestions are highly welcome.

**Comment by otykier** [comment]
I was thinking: Would it make sense to allow Relationships to be serialized within the context of each table? This is similar to how Tabular Editor lets you store Perspective and Translation information within the context of each object, instead of at the model level.

This way, when using SaveToFolder, there would be a setting which would remove Relationships from the root folder, and pull them into each table from which the relationship starts. Then, as usual you can decide if the Relationships JSON should be serialized into individual files per relationship, or keep them inside the Table JSON.

Relationships would "belong" to the table on the "From" side of the relationship. So a fact table would store information about all relationships to any surrounding dimension tables.

**Comment by jordandakota** [comment]
@otykier  Am a fan of your most recent thoughts. Fact table storing information about all relationships to any surrounding dimension tables makes sense.

**Comment by otykier** [comment]
Thanks for the feedback. I'm going to make that an option in the next release.

**Comment by SQLBent** [comment]
I have been working on several bigger projects using Tabular Editor. Based on experience using GIT i have noticed a lot of issues with the current implementation of relationships.

At the moment i am not fan of using the relationships as individual objects. In a lot of situations you end up having multiple relationships between tables (i.e. study and reference version for comparison of data) or i.e. multiple relationships between a fact table and a calendar dimension.

My recommendation would be putting relationships into one file for a given table where the specific relationship starts. This could then give an easy overview of change to relationships and at the same time see all the changes at once.

**Comment by otykier** [comment]
The solution I decided upon in [2.7.4](https://github.com/otykier/TabularEditor/releases/tag/2.7.4) was a new serialization option that puts relationships as annotations on their "FromTable" (typically a fact table). To make version control diffs easier to work with, I made sure that the relationships are serialized using indented multi-line JSON, instead of putting everything in a single line.
