### ISSUE TITLE
When database name is changed, deploy fails

### ISSUE THREAD

**Issue by zenzeinet** [otykier/TabularEditor#127]
Hi,
Context: I have a database originally called let's say "originalNameDB". I can later change its name via SSMS to "ProductionDB". Clients see the "ProductionDB" name.
When TabularEditor connects, it sees the "originalNameDB". It can load it, work on it etc - all is good.
*But*, when after I make changes, I deploy de DB back to the server, I still see the "originalNameDB"... and when I try to deploy to it, I get an error message: 
"The JSON request message failed with the following error: Another 'database' object has the 'originalNameDB' ID."
... and the deployment is cancelled.
I've tried this with both TE 2.6 and the new 2.7 - it happens again.
It would be great if you could correct this - make working with DBs with changed name impossible. Meanwhile thanks for the awesome tool!

**Comment by zenzeinet** [comment]
Self-note: It seems related to the first part of the TMSL script:
The "XXXX" below, in a SSMS créate-or-replace-database-script reads "ProductionDB", whereas the TMSL created by TE reads "originalNameDB".

So hopefully it should be very easy to solve. Hope this helps!

{
  "createOrReplace": {
    "object": {
      "database": "XXXX"
    },
    "database": {
      "name": "ProductionDB",
      "id": "originalNameDB",
      "compatibilityLevel": 1400,

**Comment by otykier** [comment]
Thanks for reporting this. Apparently, TMSL scripts identify databases by Name, not by ID (the XXXX part in your example), which is something I was not aware about (it's not very clear from the [documentation](https://docs.microsoft.com/en-us/sql/analysis-services/tabular-models-scripting-language-commands/createorreplace-command-tmsl)).

I've just updated the [2.7 release](https://github.com/otykier/TabularEditor/releases/tag/2.7) with a fix that corrects the generated TMSL script, so that you can now deploy to a renamed database, or use the "Save" button when a renamed database is loaded in Tabular Editor. There is currently no way to rename a database from within Tabular Editor, although you could copy the generated TMSL-script into SSMS, manually change the Name and then execute it from SSMS.

I've also modified the database view to include both the ID and Name of the databases on a server:
![image](https://user-images.githubusercontent.com/8976200/36562173-7358b778-1816-11e8-9cbf-1c6d074f5a91.png).

Let me know if this works for you.

**Comment by zenzeinet** [comment]
Wow, thanks, that's what I call a quick response! just tried it and it seems to work fine now. Thanks again!
