### ISSUE TITLE
Installer keeps requesting AS AMO v14 after installing

### ISSUE THREAD

**Issue by RamonBertrand** [otykier/TabularEditor#131]
The link in the installer now downloads version 15. As this writes into a different key in registry, the installer does not see AMO is installed. Unable to find a download for version 14. TabularEditor does work with 15.

Work-around, add the following key and dword with regedit:
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\5A1064FE302E38E4182444A1C73B2E79]
"Version"=dword:0e000000

Solution, let the installer also look for key.
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products\000126A7FE8E15B44840586B21F13980 version >= 251658540

Do not know if there are other ways to do this.

**Comment by otykier** [comment]
Hi Ramon.
Thanks for reporting this - since there is now an [official NuGet available for AMO](https://www.nuget.org/packages/Microsoft.AnalysisServices.retail.amd64/) I am working on an update to the installer, which will download the package from there.
Leaving this open for now, so that others can benefit from your workaround, if they encounter the same issue.

**Comment by ay5h** [comment]
Hi - I have also hit this issue. How long do you estimate it will be before the installer is updated?
Thanks

**Comment by otykier** [comment]
I'm looking into updating the installer project right now. Stay tuned!

**Comment by jorgemlesteves** [comment]
Same problem here! Waiting for the updating.

**Comment by nzdudeinsydney** [comment]
Please consider allowing people to install AMO without NuGet in case they are behind a proxy.

Just saw this now, after I've logged https://github.com/otykier/TabularEditor/issues/138.  That one could be closed as a duplicate.
