### ISSUE TITLE
Unable to create Calculated Table column

### ISSUE THREAD

**Issue by teasot** [otykier/TabularEditor#140]
Currently, there is no option (which I could find via the UI) to add a calculated table column, despite there being the option to create a calculated table.

![image](https://user-images.githubusercontent.com/8462929/38061495-28d911e4-333b-11e8-875e-deffbcc1640f.png)

While we are at it, if you add this feature could you please disable the ability to add a data column to a calculated table, and vice versa.

**Comment by otykier** [comment]
Hi Teasot.
The entire handling of calculated tables is quite buggy for the moment, and far from ideal. The main issue is, that if you modify the DAX expression of a calculated table and save the changes to an instance of Analysis Services, the expression gets evaluated and the actual calculated columns on the table may change (column may be added/removed on the server). This causes a bunch of issues for Tabular Editor. For example, undo/redo won't work correctly, and if a calculated table column is used in a hierarchy, and the column then disappears server side, you will get error messages in the client.
I am working on a solution that is a bit more long-term, but I will consider giving users the option to manually add calculated table columns instead of data columns to calculated tables in the mean time.

**Comment by teasot** [comment]
Hi Otykier,

I did not realise I could use DataColumns in place of the CalculatedColumns (it makes you wonder why they added them...).

This makes the CalculatedColumns redundant for me - consider this issue redundant, unless you would prefer it left open.

**Comment by otykier** [comment]
Just to be clear, you meant to write Calculated**Table**Columns instead of CalculatedColumns, right?
