### ISSUE TITLE
Add ability to create/open new models via plugin

### ISSUE THREAD

**Issue by teasot** [otykier/TabularEditor#147]
Currently, I am creating a plugin to allow opening/saving 1103 Tabular models (unfortunately, we still need to support 1103...).

Unfortunately, the Handler.Model is null when the program is first opened, and cannot be assigned to.
As such, there needs to be an open model in order to manipulate it.

This means the potential workflow becomes:

1. Create a new model, or open an existing model.
2. Use the plugin to open the 1103 bim file
3. Avoid clicking save, and use the plugin to save the file to a specified location instead

Now, the third step is unavoidable for saving to unsupported file types, and I have no issue with that. However, it would be great to be able to create a model in the plugin, rather than having to open an existing (1200+) model, or create a new model, every time.

**Comment by otykier** [comment]
Hi Anthony. I'd really like to flesh out the plug-in framework, to allow plug-ins to hook into the UI in more ways - but it's quite a daunting task, that will require reworking a lot of the current UI code. At the moment, I'm afraid I have to prioritise other stuff. Another thing about the plug-ins is that it's a rather "unsafe" way to extend Tabular Editor's functionality. I've heard of a number of instances where corporate anti-virus policy wouldn't allow Tabular Editor to be executed because of the dynamic loading of .DLLs. I'd like to look into this more, before extending the functionality of the current plug-in framework.

Support for 1103 models would be awesome, though - we still have a number of clients using them. Say, have you considered adding the support directly to the Tabular Editor source code instead of through a plug-in? I'd be very happy to see a pull request that would include this functionality!

Let me know if you need any assistance in that regard.

**Comment by otykier** [comment]
Closing this issue as plug-in support was dropped in newer releases. External DLLs can still be referenced through scripts if needed.
