### ISSUE TITLE
Build hangs on VSTS managed build agents

### ISSUE THREAD

**Issue by jsnape** [otykier/TabularEditor#154]
I'm trying to get this building on a VSTS build agent with an MSBuild script along these lines:

```XML
<Project DefaultTargets="Build" ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <PropertyGroup Label="Build paths">
        <OutputPath>.\output\</OutputPath>
    </PropertyGroup>

    <ItemGroup Label="Visual Studio Solutions and Projects to MSBuild">
        <TabularProject Include=".\src\*.Cube\database.json" />
    </ItemGroup>

    <Target Name="Build">
        <Exec Command="start /wait .\build\TabularEditor.exe %(TabularProject.Identity) -A -V" />
        <Exec Command="start /wait .\build\TabularEditor.exe %(TabularProject.Identity) -B $(OutputPath)Model.bim -O -V" />
    </Target>

</Project>
```

This builds just fine locally in a PowerShell console. However it hangs on a managed build agent. 

I have tried various permutations of the command including "cmd /c start /wait ... etc" however they all hang and the build times-out.

I'm assuming this works as there is a special -V flag to send VSTS compatible build messages.

Do you have a definitive command line I should be using?

**Comment by jsnape** [comment]
I upgraded from 2.7 to 2.7.1 and this no longer happens. Something must have been fixed :)

**Comment by otykier** [comment]
Hi James - yes, there was a bug with the -A switch in 2.7, that caused the Tabular Editor UI to be displayed, which would hang the caller when executed through a service (such as a managed build agent).

This was fixed in 2.7.1, so I'm closing this issue, but don't hesitate to let me know, if run into any other problems.

**Comment by eugeneniemand** [comment]
I'm also experiencing a hanging issue in VSTS. I use the Powershell task, I created some cmdlets and this is what its doing internally
# Cmdlet content
```PowerShell
Write-Host "Deploying SSAS using Tabular Editor at $TabularEditorPath `non Server $ServerInstance into Database $Database `nusing Model at $ModelPath"
  
Start-Process `
        -Wait `
        -filePath $TabularEditorPath `
        -ArgumentList @("$ModelPath", "-D", "$ServerInstance", "$database", "-O", "-V")
```

# Output on local machine
```
Deploying SSAS using Tabular Editor at C:\projects\WarehouseSSAS\lib\TabularEditor.exe
on Server (local) into Database TransactionsPTZ
using Model at C:\projects\WarehouseSSAS\src\TransactionsPTZ\Model.bim

Tabular Editor 2.7.6682.40635
--------------------------------
Dependency tree built in 88 ms
Loading model...
Deploying...
Deployment succeeded.
...
##vso[task.complete result=SucceededWithIssues;]Done.
```
# Output on VSTS
```
2018-05-16T13:20:01.8639180Z Deploying SSAS using Tabular Editor at C:\agent\_work\r4\a\_WarehouseSSAS\lib\TabularEditor.exe 
2018-05-16T13:20:01.8639562Z on Server z-azd1-sql-002 into Database TransactionsPTZ 
2018-05-16T13:20:01.8639934Z using Model at C:\agent\_work\r4\a\_WarehouseSSAS\src\TransactionsPTZ\Model.bim
```
This is where it hangs and I have to cancel the task

**Comment by eugeneniemand** [comment]
UPDATE: I tried running manually on the agent and got the error popup telling me I need the `TOM AMO libs v. 15.0.2.` libraries. This explains why it was hanging. 

It now runs but the next issue I'm trying to solve is that I'm getting no output from TabularEditor

**Comment by otykier** [comment]
Hi @eugeneniemand - in my experience, it is easier to use a "Command line" task in VSTS, instead of a Powershell task, to invoke Tabular Editor:

<img width="820" alt="screen shot 2018-05-16 at 09 30 18" src="https://user-images.githubusercontent.com/8976200/40130415-cbad5b84-58eb-11e8-8f73-a1987591bf16.png">

When using the -V switch, as above, VSTS will automatically react to errors reported by Tabular Editor:

<img width="714" alt="screen shot 2018-05-16 at 09 34 55" src="https://user-images.githubusercontent.com/8976200/40130617-73b525a0-58ec-11e8-90d4-2853c2df5ca5.png">

Or were there a specific reason why you had to use a PowerShell task for invoking Tabular Editor?

**Comment by eugeneniemand** [comment]
@otykier thanks for your response. It is part of a bigger PSake build script so I'm already inside of powershell with variables etc. Either way I got it working, as described above. Hopefully this helps someone or maybe I can add it to the readme

**Comment by otykier** [comment]
Necromancing this thread for future reference, to show that there's an easier way to call TabularEditor.exe through PowerShell, ensuring that the output is displayed and that the PowerShell task fails in case Tabular Editor returns a non-zero exit code (which happens when an error occurred inside Tabular Editor - for example if the deployment fails).

```powershell
$p = Start-Process `
        -Wait -NoNewWindow -PassThru `
        -filePath $TabularEditorPath `
        -ArgumentList @("$ModelPath", "-D", "$ServerInstance", "$database", "-O", "-V")

exit $p.ExitCode
```
