### ISSUE TITLE
Unable to see new Columns in Calculated Table

### ISSUE THREAD

**Issue by ategally** [otykier/TabularEditor#166]
I have created 3 new columns in a Date table and have deployed to my environment.  I have 4 different Calculated columns, one called Customer Membership Dates, which relate to the Date column in the Expression but the 3 new date columns do not show up in any of the 4 Calculated Columns.  I can see all 3 in all of my Tables in my Development environment but I can't see them in Tabular Editor.

**Comment by otykier** [comment]
There are 3 kinds of columns in SSAS tabular:

- Data Columns
- Calculated Columns
- Calculated Table Columns

I am not aware of any issues with the first two, but the third kind is tricky, since they are inferred automatically from the DAX expression of the Calculated Table. This is not something Tabular Editor can do, as it requires parsing the DAX expression of the table, so if you're working with a Model.bim file in Tabular Editor, then you're out of luck. Have you tried opening the deployed model directly in Tabular Editor? That would normally cause Calculated Table Columns to appear (provided there's no error in the DAX expression on the table).

**Comment by otykier** [comment]
Sorry, I was a little confused. Reading your post again, I think you meant to write "but the 3 new date columns do not show up in any of the 4 Calculated **Tables**". This sounds like you have one base table ('Date'), and then you have 4 calculated tables that all reference this base table in their DAX expression, which is a common pattern for implementing role-playing dimensions.

Now, naturally, when you add new columns to the 'Date' table, you expect them to show up automatically on all the calculated tables that derive from it. As mentioned above, this is not something Tabular Editor can currently do for you (as the DAX expression on the calculated table could be a lot more complex than simply referencing the 'Date' table directly).

However, there's a workaround: Once the model is deployed, open the deployed model in Tabular Editor (File > Open > From DB...) and then save it back as a Model.bim file. Now, the Model.bim file will contain the updated calculated tables with all the columns.

Hope this helps.

**Comment by ategally** [comment]
Good morning sir

Yes this is exactly what has happened.  Sorry if I caused confusion.

I will give this a go and let you know.

Many thanks once again.

Kindest Regards

Value Retail PLC employee
-----------------------------------------------------------
Ashraaf Tegally
BI Developer
Value Retail PLC
ATegally@valueretail.com<mailto:ATegally@valueretail.com>
Mob: +44 7900 737349

www.TheBicesterVillageShoppingCollection.com<http://www.thebicestervillageshoppingcollection.com/>
www.ValueRetail.com<http://www.valueretail.com/>

-----------------------------------------------------------

**Comment by ategally** [comment]
Thank you so much.  By saving the Deployed model from the Database to the Model.bin file all 3 new date columns now appears in in all the 4 Calculated columns.

Thank you so very much
