### ISSUE TITLE
Missing DLL dependencies

### ISSUE THREAD

**Issue by ccparkhill** [otykier/TabularEditor#167]
Despite installing the latest AMO library from the link in the error message I still get the error message with 2.7.2, any suggestions? Thanks.

**Comment by otykier** [comment]
It looks like Tabular Editor cannot properly pick up the DLLs from the GAC, even though you have the latest version. Other users have had success when [downloading the .msi file instead](https://github.com/otykier/TabularEditor/releases/download/2.7.2/TabularEditorInstaller.msi), since that includes the DLLs. Could you give that a try, please?

**Comment by ccparkhill** [comment]
That worked, thanks.
