### ISSUE TITLE
Import Table dialog improvements

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#171]
Import table feature is great! Should add an additional part that allows you to specify the table name within the import so it doesn't get named as 'New Table' (and the partition name should follow the table name). Thanks!

**Comment by otykier** [comment]
Great suggestion, thanks! I have plans to improve the Import Table feature, so that an annotation will be saved on the table, containing the source query used to obtain the metadata. That way, it will be easy to check for metadata changes that should result in addition/removal of columns or changed data types - similar to the good old "Refresh" button in SSAS multidimensional.

**Comment by otykier** [comment]
Closed, as the dialog was replaced by the new Import Tables UI in 2.8.
