### ISSUE TITLE
Ensure synchronizing serialization settings for a whole team

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#175]
This has happened to us now a few times. A new member of the team starts and they don't fully read/setup the serialization settings as per our dev setup guidance. This means that if not caught they make a huge number of changes to the model which obfuscates the commit for what they have actually changed. i.e. they just changed one file but there are hundreds of changes.

Of course we would try to prevent this by a pull request but sometimes they slip through and would be good to prevent by design.

I wonder if an easy way to solve this could be to have the expected settings alongside the database.json file (we use the folder method as we use source control). Tabular Editor could first check there when opening and this would guarantee that everyone is using the same settings.

**Comment by otykier** [comment]
Actually, Tabular Editor should save the serialization settings as annotations on the Model object the first time it is saved to folder. Could you try provide some more details on the steps taken that results in the model being saved in a different way than originally?

For example, if you open a model from a folder structure and simply hit "Save" (CTRL+S), it should serialize in exactly the same way as it was previously stored, causing no changes to the folder structure. However, if you use "File" > "Save as..." and overwrite the existing folder structure, then it will use the serialization settings in the users current preferences.

Perhaps it would make more sense to have "Save as" use the serialization settings in the annotations (if any), and then adding a button to the preferences dialog, in case you wanted to change the serialization settings of the current model (so that it won't happen by accident).

**Comment by o-o00o-o** [comment]
Ah, I see that thanks, so we are halfway there but somehow some of the team are bypassing this. I guess they may be opening from their development cube db and then saving as, or just using save as from a folder based store from source control.

So I guess to make this bulletproof I think that this check should occur on saving in any method regardless of where it is opened from. So when you save (using any method) over the top of an existing database.json at this point the serialisation settings in the annotations should be read and applied. 

I guess you might want have an advanced "override serialisation settings" options on the save as dialog but this would only be used in the rare occasion that these settings are intended to be changed for the whole project. It might just be simpler to document if you want to do this to just manually remove the annotation from the database.json before saving.

**Comment by otykier** [comment]
I added a checkbox to the "Save As..." and "Save To Folder..." dialogs:

![image](https://user-images.githubusercontent.com/8976200/44672591-c1421480-a9dd-11e8-8b79-d55d04749ae6.png)

This checkbox shows up whenever a model that was previously saved using Tabular Editor (and thus contains the special `TabularEditor_SerializeOptions` annotation), is saved using one of these dialogs. When checked (which is the default unless switching between saving as Model.bim / folder structure), the model is saved using the annotated settings. Only when you uncheck this, the serialization settings will be overridden using the settings in the Preferences dialog.

**Comment by otykier** [comment]
Available in [2.7.3](https://github.com/otykier/TabularEditor/releases/tag/2.7.3)
