### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by DaniilMaslyuk** [otykier/TabularEditor#177]
Can we please get HiDPI support? Otherwise the interface looks pixelated on HiDPI screens like Surface Book's.

**Comment by otykier** [comment]
Looks like [.NET framework 4.7 supports high-DPI for windows forms applications](https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms). Currently, Tabular Editor is using 4.6. I'll look into upgrading it to 4.7 as well as opting-in to high-DPI.

**Comment by otykier** [comment]
So I played around with the high-DPI settings in .NET 4.7, and while some stuff rendered great, it turns out that a lot of the native winforms controls (toolstrips, menus, etc.) are not hidpi aware, but instead scale up. In my opinion, this caused the application to overall look worse, than when everything is upscaled directly.

I'm afraid the only way to properly support high-DPI is to rework the frontend into something other than winforms. WPF or Universal Apps maybe - but this is a huge undertaking, that I don't currently have time for, unfortunately. I did have plans to overhaul the UI at some point, to provide features such as docking, multiple editor tabs that may be closed, etc. At this point, I will consider if it would make sense to swap to another UI framework - I'd just prefer not to have anything too bloated. I think one of the things people love about Tabular Editor is its small size and fast loading speed - it's the very opposite of Visual Studio in this regard. Thoughts?

**Comment by DaniilMaslyuk** [comment]
Daniel, thank you for explaining what's involved in enabling the HiDPI support. I am definitely in favor of keeping things as is rather than spending a lot of time and risking making things slower -- like Visual Studio 🙂

The HiDPI support is definitely a "nice to have" feature -- guess I was just spoiled by how good Tabular Editor is, and I don't have much else to wish for 😃
