### ISSUE TITLE
Enhancement: Add New Measure option to right click menu for a display folder

### ISSUE THREAD

**Issue by dgosbell** [otykier/TabularEditor#178]
We have a number of models with a large number of calculations organized into folders. At the moment we need to create new measures by right clicking on the table, then creating the new measure, then we move the new measure to the correct folder. It would be nice to be able to right click on the folder and create the measure directly in the folder in one action.

**Comment by SQLBent** [comment]
Hi Darren,

have you considered right-clicking and duplicating the measures when you create new ones ?
Below is a small example for this:

![display folder](https://user-images.githubusercontent.com/23612432/44507549-44e0c600-a6ab-11e8-8a2d-f2a3064aaac9.gif)

**Comment by otykier** [comment]
This will be fixed in the upcoming 2.7.3, as I agree it is the most intuitive way to add new objects to an existing folder. In the mean time, please use SQLBent's suggestion or alternatively, if you right-click on any object already inside the folder, any new objects created will be added to that same folder immediately.

**Comment by dgosbell** [comment]
@SQLBent - yes, I've been doing that, but it was not my first instinct. I see @otykier has figured out a simple fix - it's just a small improvement, but hopefully it will help out beginners.
