### ISSUE TITLE
deploy to PowerBI desktop is not working 

### ISSUE THREAD

**Issue by djouallah** [otykier/TabularEditor#18]
when i connect to PowerBI desktop, i can see the model and do modification, trying to deploy the model results in errors.

**Comment by otykier** [comment]
What error message are you getting, and what kind of changes did you make to the model? Also, which version of PBI Desktop are you using?

**Comment by djouallah** [comment]
I am using PBI Version: 2.41.4581.361 64-bit (November 2016), I did not modify anything, just connect to PowerBI desktop, then click deploy using the same server launched by PBI desktop, i can not copy the error, but it start with Query(269,77) the syntax for "yes" is incorrect.

**Comment by otykier** [comment]
In general, the Deploy option generates and executes a TMSL script, which I think is currently not supported by Power BI desktop. However, as you noticed, the "Save" option seems to work.

In my experience, it should be possible to do simple changes such as adding display folders and measures to a .pbix file, saving the changes from Tabular Editor, and then saving the .pbix file in Power BI Desktop. But in any case, this is not a feature that is supported in Power BI, so if it doesn't work with the changes you make, I'm afraid there's nothing we can do in Tabular Editor to fix it. I've wrote a mail to the Power BI Team to hopefully add support for TMSL script changes, etc. to models loaded in Power BI, so that this will work flawlessly in the future.

**Comment by djouallah** [comment]
thanks daniel

SSAS in _PowerBi Desktop run in a sharepoint mode, so backup and restore does not work, instead something like this should work https://msdn.microsoft.com/en-us/library/mt577156.aspx.

I know probably you have other priorities, but supporting Power BI desktop will be a "Killer feature"

thanks for adding automatic detection of port ID

**Comment by otykier** [comment]
Hi Mimoune,
I'm not sure I understand what this feature is supposed to do. I would love to help and improve support for Power BI. Could you please explain a little more detailed what it is you need?
Thanks in advance!

**Comment by djouallah** [comment]
I opened a separate issues, i will provide more information if needed
