### ISSUE TITLE
Breakdown of roles

### ISSUE THREAD

**Issue by SQLBent** [otykier/TabularEditor#180]
Hi,

i would like to request improvement to the way roles are handled. It would be great if there is a break-down of roles like tables where each table with row level security are child members of an role and the DAX can be edited in the expression editor.

This could as well enable better functionality around object level security.

**Comment by otykier** [comment]
So something like this?

![image](https://user-images.githubusercontent.com/8976200/44721755-c788cd00-aa7f-11e8-9490-1b5e2a3744dc.png)

...or is the main purpose of this suggestion to be able to edit the filter expressions within the Expression editor?

**Comment by otykier** [comment]
This is now fixed in [2.8.1](https://github.com/otykier/TabularEditor/releases/tag/2.8.1). ModelRole-objects can now be expanded to show all TablePermission-objects that have been defined in the model. TablePermission objects are automatically created when you assign an RLS expression on a role/table, or (Compatibility Level 1400+) when you set a non-default OLS metadata permission on a table or a column. The TablePermission will be shown in gray ("inactive"), if it does not hold an RLS filter or any non-default OLS metadata permissions.
