### ISSUE TITLE
Custom Actions now showing on context menu

### ISSUE THREAD

**Issue by simplesi** [otykier/TabularEditor#186]
I've just created a lot of custom actions to implement the time patterns here: https://www.daxpatterns.com/time-patterns/

However, now I've found that they're not showing up in the context menu when I right click on a measure (they are configured for measures). Everything in the `CustomActions.json` file does show up under `Samples -> Custom Actions` in the Scripting editor. When an action is missing, if I load it in the editor, and then re-save it as a custom action with the same name, it often appears in the context menu again - but then as I've re-added more and more this way, I've found my older actions dropping off.

I suspect this is a few different bugs:
- is there a maximum number of actions in a folder?
- are there reserved characters that can't be in an action's name?
- is there some caching going on somewhere?

*Problem*
On a clean install of Tabular Editor 2.7.3, if I create a `CustomActions.json` file with the following contents, I get no actions on the context menu when I click a measure, but two actions listed under `Samples->Custom Actions`

```
{
  "Actions": [
    {
      "Name": "Time\\Create AOA Measure",
      "Enabled": "true",
      "Execute": "// Creates a AOA measure for every selected measure.\r\nforeach(var m in Selected.Measures) {\r\n\r\n    String name = m.Name + \" AOA\";\r\n    String dax = \"[\" + m.DaxObjectName.SubString + \" MAT] - [\" + m.DaxObjectName.SubString + \" PMAT]\"; \r\n    String description = \"Moving Annual Total Over Moving Annual Total, \" + m.Description;\r\n    String formatString = m.FormatString;\r\n    String folder =  \"\\\\Time based\";\r\n    \r\n    \r\n    \r\n    m.Table.AddMeasure(\r\n        name,          \r\n        FormatDax(dax),\r\n        m.DisplayFolder + folder         \r\n    );\r\n \r\n    Measure created = m.Table.Measures[name];\r\n   \r\n    // Set additional properties\r\n    created.Description = description;\r\n    created.FormatString = formatString; \r\n    created.InPerspective.CopyFrom(m.InPerspective);\r\n}",
      "Tooltip": "",
      "ValidContexts": "Measure"
    },
    {
      "Name": "testxyz199",
      "Enabled": "true",
      "Execute": "foreach(var table in Selected.Tables) {\r\n    // table.IsHidden = false;\r\n}",
      "Tooltip": "",
      "ValidContexts": "Measure"
    }
  ]
}
```

*Expected behaviour*
Actions should display in the context menu, or there should be an error so I can fix the problem.

**Comment by otykier** [comment]
Thanks for reporting this.

First off, are you getting the following error message upon opening Tabular Editor?

![image](https://user-images.githubusercontent.com/8976200/45204881-df7efe80-b280-11e8-97eb-2cff275c5c59.png)

This usually indicates that the C# in your actions does not compile due to invalid syntax. Unfortunately, due to an oversigt on my part, the CustomActionsError.log file mentioned in the error message, is nowhere to be found. However, we can still see what error messages were produced by executing Tabular Editor from the command line.

1. Open a command prompt in the folder where TabularEditor.exe is located.
2. Execute Tabular Editor using the command:

```
start /wait TabularEditor.exe
```

When I took your actions and put them into my CustomActions.json file, I got the following output:

![image](https://user-images.githubusercontent.com/8976200/45205752-67660800-b283-11e8-9e56-2040ff46b87f.png)

So the solution here, seems to be to change `SubString` (camelcase) to `Substring` in your script actions. Remember, C# is case-sensitive :)

**Comment by simplesi** [comment]
Amazing, thank you. I hadn't noticed that status bar message (perhaps it's worth finding a way to make it more obvious in future?) - but that's just perfect. This isn't the first time that case-sensitivity has bitten me this week!

Suggested future improvement - attempt to compile the c# before letting someone save it as a custom action; I'd sort of assumed that my code was good because I could save it that way.

**Comment by otykier** [comment]
Yep - #136 is in the works :-) Thanks for the feedback.
