### ISSUE TITLE
upgrade to 1400 from database.json file

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#193]
Is it possible to upgrade to 1400 in tabular editor? if not, only option after saving to folder is to save back to .bim, open in SSDT, upgrade, save back to folder. Thanks!

**Comment by otykier** [comment]
I’m 95% sure you can upgrade a model by opening the database.json file in a text editor and change 1200 to 1400. Haven’t tested it, though. If it doesn’t work, I’ll provide upgrade functionality in 2.7.4.

**Comment by SQLBent** [comment]
I have done this on multiple occasions with success.

@otykier have you considered supporting this from a GUI perspective? I dont see any changes between the assembly version causing features to break during upgrade. Downgrade on the other hand will probably not work bot due to DAX and from a feature perspective.

**Comment by kalmenk** [comment]
@otykier amazing, it does work! It would be nice to have the functionality in the GUI. 
just have to delete the existing database on the server before deploying. can't overwrite 1400 on existing 1200 model.

**Comment by otykier** [comment]
Closed. Discussion continues on #200 .
