### ISSUE TITLE
Support for dataCategory JSON property

### ISSUE THREAD

**Issue by marcosqlbi** [otykier/TabularEditor#195]
The dataCategory property in JSON is not supported (see attached PBIT file).
[demourl.zip](https://github.com/otykier/TabularEditor/files/2449749/demourl.zip)

**Comment by otykier** [comment]
This is because the current build (2.7.3) has been compiled against [v. 15.1.0 of the TOM libs](https://www.nuget.org/packages/Microsoft.AnalysisServices.AdomdClient.retail.amd64/15.1.0), where they didn't have support for DataCategory on measures.

Next release (2.7.4) will be compiled against the newest version [15.5.0](https://www.nuget.org/packages/Microsoft.AnalysisServices.AdomdClient.retail.amd64/15.5.0) which seems to support the property (as well as the CL1455 used by Power BI) just fine.

**Comment by marcosqlbi** [comment]
Great - thanks for the update!

**Comment by danjenglish** [comment]
Was this enabled for Measures in the bim files? If so, where do I find it because I am using 2.7.4 and I don't see this at all. I was expecting to see it in the Metadata section like it is with columns, but maybe I am looking in the wrong spot or this simply isn't supported by VS/SSDT. Thanks!

**Comment by otykier** [comment]
Unfortunately, the property is only supported in the Compatibility Level 1455 (currently used only by Power BI). If you try to set the property in the Model.bim file directly, you will get an error upon deployment to SSAS, or when loading the file in VS/SSDT, as Analysis Services only supports CL up to 1400 for now.

**Comment by danjenglish** [comment]
Ok, that makes sense. So maybe something that will be available once we can publish models to the PBI workspaces then;) Seems odd to me that we can still use this feature for measures we create in PBI Desktop files against Live Tabular Connections. Oh well. Thanks for the update.
