### ISSUE TITLE
shuffling perspectives?

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#207]
Just opened the model and made a few changes and saved and every single file has been changed with the perspectives having been changed from

"value": "[\"Sales\",\"Customer Analytics\",\"VIP Exchange\"]"

to

"value": "[\"Customer Analytics\",\"Sales\",\"VIP Exchange\"]"

Not good. Is this at risk of happening repeatedly?

**Comment by o-o00o-o** [comment]
Perhaps this was caused by me setting alphabetical mode? Although surely this shouldn't change the serialization order?

**Comment by otykier** [comment]
This was changed in 2.7.4 (check the release notes), but we should probably have had a more explicit warning about this. It was made this way because some users were reporting that the perspective ordering in the annotations would sometimes change randomly. Sorting them alphabetically before serialising ensures a deterministic serialisation going forward (at least until a perspective is renamed/added/removed). 

Hopefully this didn’t cause you too much trouble. Now that you know the reasoning behind this you can plan accordingly in your version control environment. Rest assured that there will be no more changes made to model serialisation going forward, without providing opt-in functionality.

**Comment by o-o00o-o** [comment]
Ok thanks, I just wanted to make sure that it wasn't going to be random.
