### ISSUE TITLE
support saving changes to pbix

### ISSUE THREAD

**Issue by djouallah** [otykier/TabularEditor#21]
the changes made to PBI Desktop are not save in pbix, it will nice to implement this functionality. maybe using UI automation.

**Comment by otykier** [comment]
Thanks for this suggestion. I think UI Automation is a little outside the general scope of Tabular Editor, and in my experience, it is also difficult to test and maintain.

I would much rather see that Microsoft provides an API that allows to programmatically do everything Power BI Desktop can do, such as making supported changes to the data model, source queries, reports and saving the .pbix file. Then, Tabular Editor could use this API for exactly this purpose.

If you agree, I suggest you go and vote on [this idea](https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/7345565-power-bi-designer-api), suggested by Marco Russo.

**Comment by djouallah** [comment]
do you think https://msdn.microsoft.com/en-us/library/mt577156.aspx.  may work,  i presume the interaction between PowerBI desktp and SSAS is using standard AMO functions

have this project https://github.com/akavalar/SSAS-on-a-shoestring , it seems he manage to save a file even when it is on sharepoint mode ?

**Comment by otykier** [comment]
I will have to look into that, but I think this functionality is not related to streaming to and and from the .pbix file.

**Comment by marcosqlbi** [comment]
Just my two cents on that: the project https://github.com/akavalar/SSAS-on-a-shoestring provide a way to violate the Microsoft license agreement. Creating more tools of such a type is the easiest way to make Microsoft closing the door, and no longer provide a way to interact with Power BI Desktop. I asked to MS to make Power BI Desktop more open, providing an API to it, and I hope there will be more ways to interact with it, but it is not a good idea to workaround a license agreement.

**Comment by djouallah** [comment]
Marco 
sorry i reference that project only for this snippet of code

AMOImageLoadInfo=AMO.ImageLoadInfo("SomeDatabaseName","SomeDatabaseID", Stream, 0) # 0 = ReadWrite mode
AMOServer.ImageLoad(AMOImageLoadInfo)
AMOServer.Refresh()

all i wanted to know is how to backup a tabular instance if it is in share-point mode, i don't think it is illegitimate to ask for this ? I never suggested to launch an independent instance of SSAS as it is clearly in violation of the license

**Comment by marcosqlbi** [comment]
I was referring to this sentence: "the changes made to PBI Desktop are not save in pbix"
Technically forcing something through a TOM call could work, but it's unsupported and it could break the PBIX file. I would be careful in providing a tool that can destroy a pbix file (well creating a copy could be a workaround, but I don't think you can automate a Save As). I have seen a workaround using keystrokes - it's relatively safer, but it's not something I would rely on in a production environment. It could work for development.
Regarding the backup when you are in sharepoint mode: in theory, you don't need it, because PowerPivot for SharePoint is automatically manage by restoring an existing model, and keeping an updated version of the data in the SSAS database. However, a copy of updated data is pushed back in the Excel file already, so why you need to do a further backup of the SSAS Tabular database? 
Thanks!

**Comment by djouallah** [comment]
thanks for the explanation, the only reason i asked for sharepoint mode is, as you know ; the local instance of SSAS launched by PowerBI desktop is in DeploymentMode  = 1,  and I could not find any documentation regarding the backup and restore, i wanted just to know how it works, obviously my ultimate purpose was saving a pbix. 

so probably i was asking the wrong question,  but honestly i don't think there is harm in asking.

**Comment by djouallah** [comment]
Marco
really there is no malice intention here, I already proposed an idea to have a paid non throttled Power BI Desktop Pro edition 

https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/17636668-paid-power-bi-desktop-pro

PowerBI desktop is such an amazing product, it will be unfortunate to keep it only an authoring tool, in many situation SSAS or PowerBI.com are not an option.

**Comment by marcosqlbi** [comment]
I know, and don't worry, there are no wrong questions!
I just wanted to clarify why such a feature could be harmful for a tool like Tabular Editor and for many other community tools. In some way, we are always in a "gray area" by using unsupported feature. Crossing the line of legal actions would be an issue also for the "good" usages of these tools. For this reason I tried to address the discussion. If Microsoft don't want to make a feature open, we can discuss the issue with them, even in a strong way, but providing an easy way to hack the licensing term is definitely the wrong choice, because of the long term reaction that could affect anyone (including regular users that pay licenses and just want a more productive development environment).
I hope this clarify my position.

Thanks for your contribution - it's good having feedback and new ideas!

**Comment by djouallah** [comment]
Marco

I see your point,  sorry i never really thought about the side effect of this particular feature.  requested closed

**Comment by marcosqlbi** [comment]
No problem - thanks!

**Comment by otykier** [comment]
Hi Marco. Thanks a lot for your insight and comments - really appreciated, and I agree with everything said here. I've updated the docs to emphasise that using Tabular Editor to make TOM changes to a .pbix file is unsupported, and could corrupt the file.
