### ISSUE TITLE
-A command line doesn't honour BestPracticeAnalyzer_IgnoreRules?

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#218]
Trying to get my new checks into our CICD build and have deselected a few BARules that are not relevent right now. Clicking Analyse in the UI returns no errors but running with -A returns the errors. 

Any way to solve this without physically removing the rules from the database (which I think is what I am going to have to do)?

Once I remove them, any easy way to return them?

**Comment by otykier** [comment]
-A switch not honouring ignored rules is a bug. Will be fixed in upcoming release.

The rules are stored as JSON in the BestPracticeAnalyzer annotation on the Model, as you probably already know. So if you need to easily remove/restore the rules as a temporary workaround, I suggest simply copying the entire JSON from the annotation into a file. If you don't feel comfortable editing the JSON manually to remove rules, you can use [this online tool](https://jsoneditoronline.org/), which makes it easy to remove certain objects from a JSON array, etc.

**Comment by otykier** [comment]
Fixed in [2.8](https://github.com/otykier/TabularEditor/releases/tag/2.8)
