### ISSUE TITLE
Obtain any errors after deploy

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#230]
Right now when we deploy, if there are errors in measures etc we can see these by connecting a second tabular editor to the database. Could these be retrieved after deploy into a file based model  so we only need to have one tabular editor open?

The errors should not be serialised, just flagged and viewable in that session.

**Comment by otykier** [comment]
A better approach would be to change your workflow slightly, so that you work on a connected model (a development or “workspace” database - it need not hold any data), and hit CTRL+S whenever you want to check for errors. When you’re done, use the Save as... or Save to folder... option so that you can commit your work to source control. Thus, you would only be using the Deployment Wizard when actually deploying your model to a production database, or when loading changes from source control into your workspace model.

**Comment by o-o00o-o** [comment]
The problem with that workflow is that it encourages code to be changed outside of source control first which is not good practice in my experience. It is much easier for busy developers to change code, deploy, get it tested and then forgot to check in some of the changes that were tested. I've seen it too many times, so I don't agree that this is a better approach. Our development environments are not backed up and cannot be code reviewed etc. The suggestion I made seems to have the best of both worlds, encourages changes in source control first and also allows getting quick feedback on any errors.

**Comment by otykier** [comment]
I see. The main issue with your suggestion is a technical one: Tabular Editor uses the TOM to save changes when connected to a database, simply by calling the `Model.SaveChanges()` method. This feeds the errors (if any) directly back into the object model currently loaded within Tabular Editor, automatically populating the "ErrorMessage" property of measures, calculated tables, etc. making it very easy to surface these errors in the UI.

The Deployment Wizard uses the TOM to generate a "CreateOrReplace" TMSL script, which is then modified slightly, if the user decides not to deploy data sources, partitions, etc. Finally, the script will be executed against the database, when clicking the "Deploy" button. This operation can either succeed or fail. Getting the error messages back into the UI would require a lot more work, as I would have to manually loop through all objects of the destination DB, copying any errors over to the locally loaded model. This would also require that Tabular Editor maintains its own "ErrorMessage" layer, as the property exposed by the TOM is read-only. At the same time, the destination database might not even be in exactly the same state as the locally loaded model. For example, if you choose not to deploy model roles, you might have erroneous RLS filter expressions in your local model that do not exist in the deployed database, or vice versa, in which case no error would be surfaced in the UI.

If you're concerned that developers forget to save their model as code, I think a better solution would be, to have Tabular Editor provide an option for saving to the file system AND to a connected database simultaneously. In fact, it sort of already does this, if you enable the "Save Model.bim backup here", only this option always saves the model as a .bim file, and always to the same location.

![image](https://user-images.githubusercontent.com/8976200/49701472-113f9280-fbed-11e8-8139-97006fb30e57.png)

I guess this feature could be enhanced, so that when loading a model from a file/folder, you could specify your "workspace" database, which could then trigger an automatic deployment from the loaded file/folder, after which Tabular Editor would connect to the deployed database. Then, upon every CTRL+S, the changes would be applied simultaneously to the file/folder AND the connected database. It would be kind of similar to what Visual Studio does today, except that the developer would still be in control of when changes are synced to the workspace database.

Kindly let me know your thoughts on this.

**Comment by o-o00o-o** [comment]
Hi Daniel, interesting thanks for your thoughts on this. I think that your suggestion would be even better than what I suggested! I could imagine the workflow would be

- Open database.json from GIT working folder
- Prompt to optionally select a "workspace" database (server and database name) - in our case these are different for each feature). If cancelled then the current behaviour is used where saving only saves to the model 
** I guess that there could be an option if choosing "Save As" if you want to change your mind since you opened the file to save and deploy.
** note If this server/database doesn't already exists, this is ok - this gives us an easierway to deploy the first time
- on Saving the model, deploy automatically happens and errors are collected

This is better than the vs method as it is easier for us to choose the database server and name to use as the workspace (that we advertise to testers later on) and as you say it allows us to control when we deploy which is generally more time efficient.

Thanks!

**Comment by otykier** [comment]
Will have something coming up in the next major release that addresses this. Stay tuned! (closing this issue for now)
