### ISSUE TITLE
Provide way to reconnect to database

### ISSUE THREAD

**Issue by DBojsen** [otykier/TabularEditor#252]
If I open from database to do direct changes and testing, and my network becomes unstable - I am not able to save back to the database. 
My only option is to deploy, save to file/folder (and later deploy) or loose my changes.
It would be very nice to be able to reconnect and save the changes to the database.

**Comment by otykier** [comment]
Yeah, this is a known issue, which in my experience is especially prevalent when working with Azure Analysis Services. I have plans to run a background thread which will try to keep the connection alive on regular intervals, but there’s always a chance that the connection could be lost altogether.

Since I’m using the TOM to load the model metadata from a server, I’m not sure there’s any way to recover a lost connection. Doing a full deployment and reloading the model seems to be the only workaround. Unfortunately, this is not exactly the same operation as calling the TOM Model.SaveChanges() method, which is what happens whenever you click the save button, which is why I prefer that users manually do a deployment in that case (for example, you’d have to manually reapply Power Query credentials after each deployment - this is not necessary when calling Model.SaveChanges()).

**Comment by otykier** [comment]
[2.8.2](https://github.com/otykier/TabularEditor/releases/tag/2.8.2) now automatically reconnects every minute in the background, to keep the connection alive and refresh the auth token. Let me know if you're still experiencing any issues with this.
