### ISSUE TITLE
Native Query after removing columns

### ISSUE THREAD

**Issue by PedroReis-PBIPT** [otykier/TabularEditor#276]
Hi Daniel!

I am working on an SSAS 1400 compatibility model, using the Power Query Import Mode.
After doing the initial full table import with SSDT, I started working on the model shaping with Tabular Editor.

I tested deleting some table columns, and then went back to SSDT, and checked that the Native Query still held all the columns being imported.
When going to SSDT and removing the undesired columns, then my native Query is now just a select of the desired columns as expected.

Is there a way with TE to delete columns and passing this to the Native Query, so that Query Folding is optimal?

**Comment by otykier** [comment]
Unfortunately, that's not possible at the moment. Support for Power Query data sources is very limited in Tabular Editor because Microsoft has not provided an API for Power Query, so things like updating the native query or updating a table schema based on changes to an M script is not possible within Tabular Editor.

For this reason, I generally recommend that developers use Provider (aka. Legacy) Data Sources for their tabular models, if they can, as these are much easier to work with, and Tabular Editor even has an [Import Tables Wizard](https://github.com/otykier/TabularEditor/wiki/Importing-Tables) that works with most of the commonly used Provider Data Sources.
