### ISSUE TITLE
add an option in deploy data too

### ISSUE THREAD

**Issue by djouallah** [otykier/TabularEditor#28]
here is what's possible now

- Connect to Power BI Desktop
- Deploy the model to SSAS
SSAS Can not refresh as the data source is in M

it will be very useful, if there is an option to deploy Data too, so even the model can not be processes , still it can be used. 

so basically using PowerBI desktop to refresh the model and SSAS to host it.

**Comment by marcosqlbi** [comment]
While technically possible, this has several challenges:
1. All the connections should be changed to SSAS connections
2. Power BI Desktop should be "visible" from SSAS server - for licensing (and maybe technical) reasons, Power BI Desktop should run within the same PC of SSAS server
3. I'm not sure you can move in this way the BLOB fields (but I agree these could be ignored in 90% of the models)
4. And because all of this wouldn't be supported, every release of Power BI Desktop might break this behavior.

So I'm not sure it worth the effort...

**Comment by otykier** [comment]
Agree with Marco. I think it would be better to wait for SQL Server vNext, where a more "natural" migration path from Power BI to Analysis Services will surely become available.

**Comment by djouallah** [comment]
sorry probably i did not write it well

all what i am saying in the deploy option is there a *supported* way to deploy  Data too, 
Probably i don't understand how it works, but I imagine if there is data in SSAS, we don't need to process the model in SSAS ?

**Comment by marcosqlbi** [comment]
Yes but you don't have data in SSAS, you only deploy metadata on SSAS with Tabular Editor.

**Comment by djouallah** [comment]
Marco, yes I know :), I asked if it is possible to deploy Data too,  and you clarified it is not possible.

**Comment by djouallah** [comment]
Marco thanks for your reply, and Daniel thanks for explaining his reply, sorry for the noise again
