### ISSUE TITLE
the  displays problem of The DAX editor when has Chinese Charater

### ISSUE THREAD

**Issue by minren118** [otykier/TabularEditor#283]
Sorry I can't find out how to upload the picture, I can't show the screenshot.

**Comment by trivita** [comment]
i'm having this issue too. here's a screenshot
![image](https://user-images.githubusercontent.com/1425147/56875313-ad6e1700-6a72-11e9-9a44-42a9e50be8e3.png)

**Comment by otykier** [comment]
Thanks for reporting this. What does the actual DAX expression look like? Could you copy-paste it from the Model.bim source file? Thanks!

**Comment by minren118** [comment]
the measure like MAX([域账号]),but display like the below picture
[
![QQ截图20190430102236](https://user-images.githubusercontent.com/28550438/56938172-000f0800-6b33-11e9-91e7-4379fb4e5049.png)
](url)

**Comment by trivita** [comment]
> 
> 
> Thanks for reporting this. What does the actual DAX expression look like? Could you copy-paste it from the Model.bim source file? Thanks!

i think it has something to do with using the wrong font to display unicode characters.
and btw, i cant use chinese ime in editors.

**Comment by otykier** [comment]
This is an issue with the [FastColoredTextBox](https://github.com/PavelTorgashov/FastColoredTextBox)-component used for editing expressions/scripts. It seems that the textbox is not adding the necessary spacing between the characters, so that they are all "smudged" together.

I am currently migrating away from this component. Tabular Editor 3.0 will use Scintilla.NET, which (among other things) displays unicode characters properly:

![image](https://user-images.githubusercontent.com/8976200/58246588-c6a77200-7d57-11e9-8f13-0ce4acd28b34.png)

I will let you know when 3.0 is available.

**Comment by minren118** [comment]
thanks a lots
