### ISSUE TITLE
Some question about best practice using the tool

### ISSUE THREAD

**Issue by geirfo** [otykier/TabularEditor#284]
Hi!
I am quite new using Tabular Editor, and have a couple of question regarding the product.

First to say, I am using devops and git as source control, and want to hear what is the most practical way to use the tool starting from scratch. I have used visual studio 2017 and now 2019 to create an Analysis services project using power query data connections. But I have read that this is not possible now. Perhaps that does not matter, but in the end the AAS data model will be used in Power BI reports. So hopefully I can make use of RLS in the same way. My first question is when starting from scratch should I have start with an empty model.bim file from just created AS project in Visual Studio and then check in all the Tabular Editor files and not relying more on the model.bim file?

Next, I need to setup devops CI/CD. Could you tell me how to set up a build and deploy pipeline  (I guess I have to make use of a Command Line task that using the tabulareditor.exe executable, but that executable is on my machine and the agent is running elsewhere in the sky)

Last, I want to run unit tests. I have read some places that you prefer NBI. Can you just tell how you have set up a small unit test 

Thank you

regards

Geir F

**Comment by otykier** [comment]
That's a lot of questions for one post, but I'll try to cover as much as possible :-)

**Legacy vs. Power Query data sources**: If you intend to use Tabular Editor, avoid the Power Query data sources (use Legacy aka. "Provider" data sources instead). In Visual Studio, go to "Options" > "Analysis Services Tabular" > "Data Import" and check the "Enable legacy data sources" option. Then, when creating a data source in your model, choose "Import from Data Source (Legacy)": 
![image](https://user-images.githubusercontent.com/8976200/56891159-d7780700-6a7b-11e9-9d8f-2e99039810b4.png).

Tabular Editor only has limited support for power query data sources, so that's why I recommend avoiding them (in normal DWH/Tabular scenarios, you don't need them anyway).

**RLS in AAS with Power BI live connections**: This question is not related to Tabular Editor, but RLS would still work in this scenario.

**Migrating to Tabular Editor**: You can start with an empty model in Tabular Editor, or you can start from your existing Model.bim file - that's up to you. A common workflow is to initially import tables in Visual Studio and set up relationships between them in the diagram view. Then, switch to Tabular Editor to create measures, refine your models with display folders, format strings, etc.

**DevOps CI/CD**: If you're using Azure DevOps and you want to build and deploy your model through a hosted build agent, I recommend copying TabularEditor.exe and its dependency DLLs into source control (everything in the c:\Program Files (x86)\Tabular Editor folder, basically), so that your build agent can pull the program from there. Some people have a step in their build agent that downloads the latest version of Tabular Editor from Github, but this is not something I would recommend, as your build pipeline then relies on external code that could change without your acknowledgement.

**Unit testing**: I don't have much experience with NBI, sorry! For Tabular Model unit testing, I recommend setting up [Best Practice Analyzer rules](https://github.com/otykier/TabularEditor/wiki/Best-Practice-Analyzer-Improvements) to validate the model metadata. In your build pipeline, include a step that uses the CLI with the -A switch to validate the rules against your model. If you want to test calculations within your model, I'm sure something like NBI is great, if you have prior experience with it, but a simpler solution could be to use a PowerShell script with [Invoke-AsCmd](https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-ascmd?view=sqlserver-ps) calls to execute and verify DAX expressions. This last part is not really related to Tabular Editor, so that's why I haven't covered it before.

Feel free to reopen this issue if you have any further questions.

**Comment by geirfo** [comment]
Thanks for your excellent answers I will try your recommandations

Sendt fra min iPhone
