### ISSUE TITLE
Cant create/change names of new measures/columns when connected to an instance of powerbi

### ISSUE THREAD

**Issue by Tanner-Pettit** [otykier/TabularEditor#287]
i can create a new measure when connected to a local instance of power bi but as soon as i change the name it breaks and wont save. This is the same for calculated columns.

**Comment by Tanner-Pettit** [comment]
i see that there are several other threads relating to this, has there been any updated to it? This is the error i get.
![image](https://user-images.githubusercontent.com/50592399/57725261-b954fe00-765a-11e9-85a7-1a37a2be6d0c.png)

**Comment by otykier** [comment]
This is an issue on the Power BI side, because the metadata used is slightly different than SSAS. So there is no 100% guaranteed way to make this work, until Microsoft addresses this issue internally.

Most of the times, we're able to work around this issue by saving the Power BI model as a Power BI Template (*.pbit file), and then load and apply the changes to the .pbit file with Tabular Editor.

If that still doesn't work, it sometimes helps to clean up the metadata on the copied objects a little bit, by removing all extended properties and annotations. You can do that through the Tabular Editor property grid or use the following script, which will remove all extended properties and annotations from the objects that are currently selected (**warning: doing this may corrupt your Power BI model file, so make sure to keep a backup!**)

```csharp
foreach(var obj in Selected.OfType<IExtendedPropertyObject>())
{
    foreach(var xp in obj.GetExtendedProperties().ToList())
        obj.RemoveExtendedProperty(xp);
}

foreach(var obj in Selected.OfType<IAnnotationObject>())
{
    foreach(var an in obj.GetAnnotations().ToList())
        obj.RemoveAnnotation(an);
}
```

Hope this helps!

**Comment by Tanner-Pettit** [comment]
Thank you for the update! hopefully Microsoft can address this soon. Working with bim files and templates work but local instances are a bit handicapped.

**Comment by marcelodf-elad** [comment]
Hi, I have this issue, I realized that if I write in Hebrew I cannot save the file, but without Hebrew everything goes right.

![image](https://github.com/TabularEditor/TabularEditor/assets/127315138/e00dfcbe-3fc7-4cce-a3fe-224efb9cf992)


Then, I remove the Hebrew word, and I can save the file.
