### ISSUE TITLE
User has to press enter to return to regular command prompt

### ISSUE THREAD

**Issue by msdotnetclr** [otykier/TabularEditor#290]
**Issue** 
Since the program attaches to the console using AttachConsole(), at the end of the program - typically when the program exits in command line mode - user has to press Enter to return to the "regular" command prompt.

**Solution**
Send ENTER to the console window and free console upon exit.

**Comment by msdotnetclr** [comment]
With this issue, it seems that a build/release pipeline will get "stuck" whenever the Tabular Editor CLI decides to call Environment.Exit() for whatever reason, rendering the pipeline unstable.

**Comment by otykier** [comment]
I'm not sure I understand this issue. Could you provide an example showing what you mean?

For example, if I run `TabularEditor.exe localhost AdventureWorks -D localhost AdventureWorks2` from the command prompt, my prompt looks as follows, once the command is complete:

![image](https://user-images.githubusercontent.com/8976200/58176951-b33acf00-7ca3-11e9-82ee-42d62642349b.png)

Now, it may look like I have to press ENTER to return to the console, but this is only because I didn't use the `start /wait` trick, so Tabular Editor wrote its output to the console AFTER returning to the console. Indeed, it's not necessary to press ENTER before writing a new command as shown here:

![image](https://user-images.githubusercontent.com/8976200/58177148-188ec000-7ca4-11e9-8506-097a52da1791.png)

So I'm not sure why it's necessary to free/detach the console before exiting. Please enlighten me!

**Comment by msdotnetclr** [comment]
Indeed, this is less a technical *issue*, rather a cosmetic thing.

**Comment by otykier** [comment]
I see - thanks! Was worried that I was locking up some kind of OS resource even after exiting Tabular Editor. Will accept the pull request and include in next build.

**Comment by otykier** [comment]
Merged and included in [June 14th update of version 2.8.3](https://github.com/otykier/TabularEditor/releases/tag/2.8.3). Thanks!
