### ISSUE TITLE
Command Line Continuous Integration Placeholders

### ISSUE THREAD

**Issue by adamrobinson361** [otykier/TabularEditor#301]
Hi there,

I am looking to use tabular editor via the command line to set up on continuous deployment pipeline using azure devops.

I understand pretty well what I need to do apart from the how to update the data source using place holders as outlined in the wiki. I understand that I could put %database%, %server% etc in the model.bim but I'm not clear then what the development workflow is. I.e. if I am looking to continue to use visual studio how do I set %database% and %server% locally so that I can process, get new tables etc.

Any help appreciated and thanks for efforts on this. Looks great.

**Comment by otykier** [comment]
I generally recommend not to put a placeholder value in the connection strings within your Model.bim file. The reason is that Analysis Services will mask the entire connection string (*********), if it determines that it contains sensitive information OR if it can't parse the string (better safe than sorry). Once you add a placeholder to a connection string, it is likely that Analysis Services won't be able to parse it, and therefore, it will change the full string to ********** when you save the model to a .bim file. At this point, swapping placeholder values for their proper values using the Tabular Editor command line will of course no longer work... Also, as you've observed, working with Visual Studio to process tables will also not work properly, when you have placeholders in the connection string.

What I recommend, is to leave a valid connection string (without any placeholders) in your Model.bim file. This will ensure that you can still use Visual Studio to process the model just fine. In your deployment pipeline, you will use the -S switch with TabularEditor.exe, to change the entire connection string of your data source into a placeholder value. In the same command, you will also use the -D, -O and -C switches to actually do the deployment, over write data sources AND swap placeholders with proper connection strings, which you populate using variables in your Azure DevOps pipeline.

First, put the following script into a new file, ClearConnectionStrings.cs and add the file to source control:

```csharp
// This will replace the connection string of all Provider (legacy) data sources in the model
// with a placeholder based on the name of the data source. E.g., if your data source is called
// "SQLDW", the connection string after running this script would be "SQLDW":

foreach(var ds in Model.DataSources.OfType<ProviderDataSource>())
    ds.ConnectionString = ds.Name;
```

In your DevOps pipeline, use the following TabularEditor.exe command, to execute the script above and then replace the placeholders with proper values before deployment:

```bash
TabularEditor.exe "Model.bim" -S ClearConnectionStrings.cs -D "$(TargetServer)" "$(TargetDatabase)" -O -C "SQLDW" "$(SQLDWConnectionString)" -W -V -E
```

In the example above, I assume your model contains just a single data source called "SQLDW". At the same time, your pipeline should have at minimum 3 variables:

- TargetServer: The Analysis Services instance that you want to deploy to
- TargetDatabase: The ID of the database to be deployed
- SQLDWConnectionString: The actual connection string to use for the "SQLDW" data source within the model. Mark this as sensitive, if it contains username and password.

This way, you're only applying the proper connection string just-in-time, before deploying the model, without saving the connection string as plaintext anywhere - the only place it's stored, is as an Azure DevOps variable. For a release pipeline, you can even have multiple values for the same variable, depending on the stage - so for example, one connection string for UAT, one for PROD, etc...

**Comment by Surendra-thota1640** [comment]
what about if we have multiple data sources , where we need to update. How to change the Impersonation type and give username and password for that

**Comment by otykier** [comment]
You may also use a script to update properties on specific data sources, like so:

```csharp
// Assuming your model contains a provider (legacy) data source called SQLSrc:
var ds1 = (ProviderDataSource)Model.DataSources["SQLSrc"];
ds1.ImpersonationMode = ImpersonationMode.ImpersonateAccount;
ds1.Account = Environment.GetEnvironmentVariable("SQLSrcUsername");
ds1.Password = Environment.GetEnvironmentVariable("SQLSrcPassword");

// Assuming your model contains a Power Query (structured) data source called PQSrc:
var ds2 = (StructuredDataSource)Model.DataSources["PQSrc"];
ds2.AuthenticationKind = "UsernamePassword";
ds2.Username = Environment.GetEnvironmentVariable("PQUsername");
ds2.Password = Environment.GetEnvironmentVariable("PQPassword");
```

Here, I use `Environment.GetEnvironmentVariable` to assign the data source properties from environment variables. You can pass a DevOps pipeline variable into an environment variable as shown [here](https://tabulareditor.github.io/2019/10/17/DevOps4.html#step-2---schema-check). This is to avoid saving sensitive data in the script, and this solution is easier to manage than the one provided in my original answer above. So in other words, no need to use the connection string placeholder replacement options (after the `-C` switch) when calling TabularEditor.exe from the command line.

If you have many data sources that needs to be updated to use the same values, you can also just loop over them:

```csharp
foreach(var ds in Model.DataSources.OfType<ProviderDataSource>())
{
    ds1.ImpersonationMode = ImpersonationMode.ImpersonateAccount;
    ds1.Account = Environment.GetEnvironmentVariable("DataSourceUsername");
    ds1.Password = Environment.GetEnvironmentVariable("DataSourcePassword");
}
```

**Comment by Surendra-thota1640** [comment]
in the wiki , it is mentioned that "Remember that for this to work, the agent running the build pipeline must be able to reach the data source." our datasources are from onpremises , will it work with is method

**Comment by Surendra-thota1640** [comment]
without doing the schema check , is it possible to use   the .cs file to get the datasource values
-s setconnectionstringfromenv.cs

foreach(var dataSource in Model.DataSources.OfType<ProviderDataSource>())
{
    var evName = dataSource.Name.Replace(" ", "") + "ConnectionStringDev";
    var evValue = Environment.GetEnvironmentVariable(evName);
    if (evValue != null)
        dataSource.ConnectionString = evValue;
     dataSource.ImpersonationMode = ImpersonationMode.ImpersonateAccount;
    dataSource.Account = Environment.GetEnvironmentVariable("ServiceAccountUsername");
    dataSource.Password = Environment.GetEnvironmentVariable("ServiceAccountPassword");
   
}

**Comment by Surendra-thota1640** [comment]
I have updated the commandline task  and given below command and also given environment variables
TabularEditor.exe "$(Build.SourcesDirectory)/Tabular/AsqQuantificationTabular/AsqQuantificationTabular/Model.bim"  -S "$(Build.SourcesDirectory)/Tabular/AsqQuantificationTabular/AsqQuantificationTabular/config/Azure-cube-dev/SetConnectionStringFromEnv.cs  -D "$(ASConnectionString-dev)" "$(ASDatabase)" -O -C

but I am getting the fallowing error
##[error]Cmd.exe exited with code '1'

**Comment by Surendra-thota1640** [comment]
when I have command line 
TabularEditor.exe "$(Build.SourcesDirectory)/Tabular/AsqQuantificationTabular/AsqQuantificationTabular/Model.bim"  -D "$(ASConnectionString-dev)" "$(ASDatabase)" -O -C "$(Build.SourcesDirectory)/Tabular/AsqQuantificationTabular/AsqQuantificationTabular/config/Azure-cube-dev/SetConnectionStringFromEnv.cs

the deployment is happening but the datasources are not changing .

**Comment by Surendra-thota1640** [comment]
when we have given like this 
TabularEditor.exe "$(Build.SourcesDirectory)/Tabular/AsqQuantificationTabular/AsqQuantificationTabular/Model.bim"  -S  "$(Build.SourcesDirectory)/Tabular/AsqQuantificationTabular/AsqQuantificationTabular/config/Azure-cube-dev/SetConnectionStringFromEnv.cs" -D "$(ASConnectionString-dev)" "$(ASDatabase)" -O -C 

it is working fine , but how can we link the serviceaccount password from keyvault.

**Comment by otykier** [comment]
Linking a password from key vault is outside the scope of Tabular Editor. You should set up a variable group in Azure DevOps that connects to the key vault. Here’s an article with more details on how to do that: https://zimmergren.net/using-azure-key-vault-secrets-from-azure-devops-pipeline/

Please open a new GitHub issue if you have any further questions.

**Comment by arindamhazra** [comment]
Hi,

I am trying to run TabularEditor in Azure DevOps with switches -S , -C, -O and -D. I need to deplopy same Model.bim in 2 different environments. however, we want to change the DataSource for each environment. Eventhough deployment works , it does not change the ConnectionString in DataSources. I tried using -B switch to generate the updated .bim file, however, I don't see the affect of using -S and -C switrches. Please help here. Here is the masked Datasources from model.bim :

"dataSources": [
    {
      "type": "structured",
      "name": "Some Name for Data Source",
      "connectionDetails": {
        "protocol": "tds",
        "address": {
          "server": "Azure SQL Server FQDN",
          "database": "Azure SQL DW Database"
        },
        "authentication": null,
        "query": null
      },
      "credential": {
        "AuthenticationKind": "OAuth2",
        "kind": "SQL",
        "path": "Azure SQL Server FQDN;Azure SQL DW Database",
        "Expires": "Mon, 12 Jul 2021 16:40:35 GMT",
        "RefreshToken": "********"
      }
    }
  ],

with -C Switch I am trying to update the SQL Server and DW Database names using a valid connection string.
