### ISSUE TITLE
Batch rename with empty string replace leaves additional whitespace\trailing char at the end of measure name

### ISSUE THREAD

**Issue by leniel** [otykier/TabularEditor#319]
Using the latest version 2.8.5.

When I do a batch rename after duplicating some measures and try replacing "copy" word with an empty string it correctly replaces but leaves an additional whitespace\trailing char at the end of the measure name. Check **Rev 0 Hours E** measure in the 2nd printscreen.

<img width="1440" alt="Screen Shot 2019-09-06 at 16 54 19" src="https://user-images.githubusercontent.com/764854/64456617-00ae4100-d0c7-11e9-8d2f-c28874ed5665.png">

<img width="1440" alt="Screen Shot 2019-09-06 at 16 51 32" src="https://user-images.githubusercontent.com/764854/64456467-a7dea880-d0c6-11e9-84a5-41332a9d35a4.png">

**Comment by leniel** [comment]
The workaround right now is using the `Batch Rename` feature again selecting **User Regular Expressions**.

In Find, enter this:` [ \t]+$`
In Replace leave empty.

**Comment by otykier** [comment]
As far as I can tell from your screenshots, this is by design. You’re only replacing the word “copy” with an empty string - Tabular Editor will not trim the remaining string for you. To get rid of both the space and the word in one go, you should add a space in front of the word: “ copy” -> “”.

I believe this is default behavior in most search-and-replace dialogs.

**Comment by leniel** [comment]
You're absolutely right... subtle thing.

Let me take this opportunity to thank you for putting this tool together! 👏🏻

I wrote about it here: https://www.leniel.net/2019/09/automate-moving-measures-between-power-bi-files-pbix-renaming-finding-replacing-strings-dax-formula-expression.html
