### ISSUE TITLE
Any easy way to import from Excel?

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#333]
Hi Daniel, a bit of advice needed here

Our business process to create new tables/measures/columns comes through a Business Analyst and between them and a senior developer we work out the right technical design - this includes breaking changes and data dictionary type documentation on each object. 

All of this information is first collated in a spreadsheet which is a good place for it as it allows some element of data validation, conditional formatting and copy pasting as the ideas flow

Now we have this nailed down we really want to have a Custom Action in Tabular Editor that would allow selecting the excel spreadsheet to import and for a script to go through and create/update/delete the intended objects.

There is a powershell tool called Import-Excel that might do what we need, or perhaps at least convert this to a json document to allow newtonsoft to do the rest.. not sure if there is good support for calling powershell inside a custom action?

Alternatively any better ideas?

Thanks for your help!

**Comment by otykier** [comment]
I don't think there is any easy (as in "click here") way of doing this. That being said, you can certainly piece something together, if you're willing to invest some time in this.

Reading data directly from an Excel file is a little difficult due to the format of the file. A simple file format, such as a CSV, is much easier. Check out [this sample](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#generating-measures-from-a-file) for some inspiration.

You can also open a "Select file"-dialog from a script, which might be useful in this scenario:

```csharp
var filePath = string.Empty;

using (var openFileDialog = new System.Windows.Forms.OpenFileDialog())
{
    openFileDialog.InitialDirectory = "c:\\";
    openFileDialog.Filter = "txt files (*.txt)|*.txt|All files (*.*)|*.*";
    openFileDialog.FilterIndex = 2;
    openFileDialog.RestoreDirectory = true;

    if (openFileDialog.ShowDialog() == System.Windows.Forms.DialogResult.OK)
    {
        //Get the path of specified file
        filePath = openFileDialog.FileName;
        System.Windows.Forms.MessageBox.Show("Selected file: " + filePath);
    }
}
```

It is also possible to execute PowerShell from within a Tabular Editor script, by utilising [Process.Start](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netframework-4.8#System_Diagnostics_Process_Start_System_String_System_String_), for example:

```csharp
System.Diagnostics.Process.Start("powershell.exe", "-Command 'Write-Host Hello World!'");
```

Maybe there's some PowerShell lib that allows you to extract a CSV file from an Excel file?

I'm not sure converting to JSON is the best option for this, but I guess it depends on the workflow you are trying to create.

Regardless of which option you choose, you will have to write some code, one way or another. So I suggest you to experiment a little bit and choose the path that you are most comfortable with.

**Comment by otykier** [comment]
Closing this. Feel free to reopen if you need any further assistance.
