### ISSUE TITLE
(serious bug, new to 2.8.6) When renaming columns, dependend measures not properly updated

### ISSUE THREAD

**Issue by zenzeinet** [otykier/TabularEditor#346]
Hi,

Just got this new bug, that just appeared with 2.8.6., and that did not happen with 2.8.5. It totally incapacitates using 2.8.6 for me- we are reverting to 2.8.5

When renaming a column ( I was using a calculated column), the dependent measures' formula correction (automatic formula fix-up, which is ON ) just became buggy, and produces a wrong column name (similar, but not correct). and breaks the measure's formula.

The replacement by the way is also replacing the new column name in comments (is this intended?), also replaced with the wrong string.

If you need more testing happy to help

**Comment by otykier** [comment]
Thanks for reporting. Unfortunately, I am not able to reproduce this.

Could you provide a detailed step-by-step on how to reproduce this issue in 2.8.6? Thanks!

**Comment by zenzeinet** [comment]
Sure, I was re-resting it too as the behaviour was non consistent. I seem to be able to trigger it consistently the following way:

1-Open model
2-Go to calculated column. 
3-*Rename it*
4-*Save the model*  (sorry I missed these two pre-steps necessary to trigger the bug)
5-Rename it again
Outcome: Dependent measure gets incorrect new name (varies depending on the length of original and/or new column name)

I havent tried it with regular columns (too afraid to break live model ;), but I can do it in a test environment if it helps

Note: now that I follow these steps it looks like I'm able to trigger the bug also in 2.8.5? We didn't get into it before as we almost always close and re-open the model in TE every time we save modifications that are not measure-only changes...

**Comment by zenzeinet** [comment]
if you cannot trigger it, try with new name needs being longer, with spaces and Parenthesis "(" ")"

**Comment by otykier** [comment]
Thanks - I managed to reproduce it now. I was missing the "Save" step. Apparently, it happens only when saving to an instance of Analysis Services - not when saving to a Model.bim file. Looking into it.

**Comment by otykier** [comment]
### Important Update!

Please download the [updated version of 2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6).

So it turns out this is an issue that has existed since some of the very early versions of Tabular Editor. Most likely, a lot of people have been affected by it over the years, but probably just discarded it as random/flunky behaviour, since it's so difficult to reproduce. A couple of related issues also exist (see #233) but due to the difficulties of reproducing it, I have never gotten to the bottom of the issue.

To make a long story short, it turns out that Analysis Services **adds carriage return `\r` characters** to any line breaks within DAX expressions, when saving the model to a database (i.e., calling the TOM `Model.SaveChanges()` method). Tabular Editor normally removes the `\r` characters when editing an expression in the UI, and the Formula Fix-up engine builds the dependency tree based on DAX expressions that do not contain the `\r` characters. So when an expression is modified, and you subsequently save the model to a database, the `\r` characters added by Analysis Services, are not "indexed" by the dependency tree, and so when an object is later renamed, the fix-up screws up the DAX code.

The reason it's difficult to reproduce is that you need all the following steps to consistently provoke the behaviour:

- You need an object with a DAX expression that has line breaks
- The DAX expression should reference another object more than once, *on separate lines*
- You need to modify the DAX expression in the UI, to trigger Tabular Editors removal of `\r` characters
- You need to **Save** your model back to Analysis Services
- And only then - once you rename the object that was referenced by the DAX expression, you will see that the DAX gets broken.

Phew, what a bug!

Anyway, I published a fix to [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6).

Thanks again for letting me know!

**Comment by mtvessel** [comment]
Hi Daniel,

Just curious why TE would drop /r chars at all?  Seems like an odd thing to do, considering:

1) it would cause an unnecessary diff, and 
2) /r/n is the standard for newlines on Windows.  

Was there a rationale for this, or just the default behavior of a UI component?

Thanks!

**Comment by otykier** [comment]
It's a good point. I need to do some testing, but I believe there were some inconsistencies in whether /r would appear or not in some UI components, as well as when serializing/deserializing a bim file using TOM, so that's when I decided to get rid of /r's. In hindsight, it might have been better to always ensure that line endings were consistent with /r/n, but simply stripping all /r's was easier to implement.
