### ISSUE TITLE
no indication of broken Best Practice rules until deploy

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#384]
We had an unexpected experience last week with BP rules. I had changed a rule to have bad syntax and used IS NOT NULL instead of != null (doing too much SQL recently :)). However there were no errors given in the UI and actually the BP rule stopped returning the failing ones (so I assumed that it had solved the issue)

However on committing and deploying we found that the build was erroring. In fact it wasn't erroring it was warning so everything still seemed to work, with the issue now that we thought we had a BP rule in effect but it wasn't

So I think there are a couple of issues here that should be addressed

1. BP rule "Blah" with constraint "GetAnnotation("blah") is not null" doesn't indicate any error in the UI
2. When deploying even with -ERR, the BP errors are shown only as Warnings (warnings are my original errors not the Blah case as above, but you get the idea)

start /b /wait D:\a\1\s\build\TabularEditor\TabularEditor.exe  D:\a\1\s\src\VegaDW.Cube\database.json -ANALYZE -VSTS -ERR

        Tabular Editor 2.9.1 (build 2.9.7282.17172)
         --------------------------------
         Loading custom actions from: C:\Users\bgerhardi\AppData\Local\TabularEditor\CustomActions.json
         Dependency tree built in 1555 ms
         Loading model...
         Running Best Practice Analyzer...
         =================================
         ##vso[task.logissue type=warning;]Error on rule 'Prevent Hidden or Numeric columns to Be Available in MDX': Operator 'AND' incompatible with operand types 'Boolean' and 'String'
         ##vso[task.logissue type=warning;]Error on rule 'Sorted Columns Should Not Be Hidden': Operator 'AND' incompatible with operand types 'Boolean' and 'String'
         ##vso[task.logissue type=warning;]Error on rule 'Columns Used to Sort Others Should Be Hidden': Operator 'AND' incompatible with operand types 'Boolean' and 'String'
         =================================

**Comment by otykier** [comment]
The UI actually displays an error when the expression editor loses focus:
![image](https://user-images.githubusercontent.com/8976200/72733241-bfab5a80-3b97-11ea-9728-0cc236bc9f64.png)
Unfortunately, if you hit the "OK" button you might not have noticed the error message, as the dialog closes immediately. Would it be better to display a confirmation box in case an expression has an error when the "OK" button is clicked?

Also - do you think the BPA UI (below) should display rules that have an error in their expression?
![image](https://user-images.githubusercontent.com/8976200/72733720-b242a000-3b98-11ea-99c9-c8562168bb2b.png)

Regarding #2, I can certainly change the type to be "error" instead of "warning". I don't recall the rationale behind only showing them as warnings previously.

**Comment by o-o00o-o** [comment]
Yeah i think it would be most obvious if it showed in the BP errors (and included in the count of BP errors in the status bar). A warning dialog on exit would also be good, but easily missed so the persistent error covers that angle.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by otykier** [comment]
Fixed in [2.9.3](https://github.com/otykier/TabularEditor/releases/tag/2.9.3)
