### ISSUE TITLE
Can't keep changing of Data Type

### ISSUE THREAD

**Issue by Klimkiv** [otykier/TabularEditor#396]
1. In TE I can change Date Type from source and deploy model.bim
2. If I need to refresh table metadate I see 
model data type - int
source data type - curr or string
3. I do apply and after that get source data type

**Comment by otykier** [comment]
Hi @Klimkiv 
Sorry, I don't understand the issue here. Could you please provide a few more details:

- What is the expected behaviour?
- What behaviour are you currently seeing?

**Comment by Klimkiv** [comment]
1. change Date Type from source and deploy model.bim, it's ok
2. in some time i need to add some fields to the table
3. refresh table metadate I see
model data type - int
source data type - curr or string
and some new fields
4. I think that I do something with new fields and apply changes, but after applying I get only Date Type from source for old fields

**Comment by otykier** [comment]
> I think that I do something with new fields and apply changes, but after applying I get only Date Type from source for old fields

Sorry, I don't understand this part.

Let's say I change the data type of [ProductAlternateKey] in my source SQL database to NVARCHAR(255) where as previously it was BIGINT. This is the expected behaviour when I click "Refresh Table Metadata" for the Product table in my Tabular model:

![image](https://user-images.githubusercontent.com/8976200/74911798-b511fa00-53bd-11ea-8f6d-c27c158f00c4.png)

When I click "Apply", Tabular Editor changes the data type of the imported column to String, since Int64 is not compatible with the NVARCHAR(255) data type of the source:

![image](https://user-images.githubusercontent.com/8976200/74911873-dd015d80-53bd-11ea-80a0-94bea16ccdde.png)

So what is the issue?

**Comment by Klimkiv** [comment]
sorry
I've got this after refreshing table metadata and if I do apply I get
![image](https://user-images.githubusercontent.com/57611080/74912415-0348ec80-5402-11ea-9c21-ef437dda2c2e.png)
after refreshing
![image](https://user-images.githubusercontent.com/57611080/74912565-4905b500-5402-11ea-9536-72d976d02eb8.png)
If I only change data type and deploy it's ok

**Comment by otykier** [comment]
So do you intend to keep the columns as Int64 or what is the issue?

Tabular Editor maps source column data types according to the [rules defined here](https://github.com/otykier/TabularEditor/blob/f958da44553c97b915f0caaf12341ec7cd6acbd3/TabularEditor/UIServices/TableMetadata.cs#L113-L191). So if the source data type is any of the following, Tabular Editor will map it to Decimal:

- currency.type
- decimal.type
- currency
- decimal
- numeric
- money
- smallmoney

**Comment by Klimkiv** [comment]
thank you, Daniel
I did think that if chage date type it's for all times
now I see
