### ISSUE TITLE
Cannot delete a Format String Expression on a Calculation Item

### ISSUE THREAD

**Issue by jorgemlesteves** [otykier/TabularEditor#421]
Opening a Tabular Model from an existing database (AAS), from Tabular Editor 2.9.6, and after changing a Format String Expression of a Calculation Item to “0.00%” (just as an example):

![image](https://user-images.githubusercontent.com/31868867/78174206-cdf7db80-7450-11ea-82fa-0bc4da5194c1.png)

you could not reverse and delete the expression that was previously set and It raises this error on save:

![image](https://user-images.githubusercontent.com/31868867/78174223-d2bc8f80-7450-11ea-9f35-4bc89619e30a.png)

,and after that, you could not save the changes to your model:
![image](https://user-images.githubusercontent.com/31868867/78174238-d7814380-7450-11ea-94bf-1e23493e7526.png)

**Comment by otykier** [comment]
This seems to be an issue in TOM. I'll raise a bug with the product team.

There are two options for a workaround:

- Save the model as a .bim file, open the .bim file in a text editor and locate the "formatStringDefinition" JSON property. Remove the entire property, so that the only the calculation item's "name" and "expression" properties are left.
- Alternatively, use the following string as the Format String Expression in Tabular Editor: `SELECTEDMEASUREFORMATSTRING()` - this would simply reuse the same format string that is applied to the current measure.

**Comment by o-o00o-o** [comment]
Note that option 2 will mean that power bi stanard visuals (except table and matrix) will not honour the format string for *any* measure in your model.

So for that reason I would go with workaround 1

Daniel, that is strange as that used to work quite recently as that is what we had to do to solve that issue and I don't remember having a problem removing the format string

**Comment by otykier** [comment]
The issue appeared in Tabular Editor 2.9.2 (released on February 6th), which was the first version to target AMO 18.4.0.5, which had another similar bug regarding DetailRowsDefinitions (issue #400). I fixed this issue with an ugly reflection hack, and it looks like I have to do the same thing for FormatStringDefinitions, until the product team provides an updated AMO without these issues (the reason we're not yet targetting AMO 18.4.8 is because of yet another bug in this version, that affects all models with perspectives...)

**Comment by jorgemlesteves** [comment]
Thanks, Daniel, until the issue gets resolved I'll use one of the workarounds you suggested.

**Comment by otykier** [comment]
Fixed in [2.9.7](https://github.com/otykier/TabularEditor/releases/tag/2.9.7)
