### ISSUE TITLE
upgrade SSAS database compatibility level 

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#424]
Hi Daniel,
hope you are doing well.
I think it will be awsome if you add this feature to Tabular Editor. for now, the only way is to use SSDT.
Kind regards,
Arman

**Comment by o-o00o-o** [comment]
Interestingly we have done this twice, once from 1200 to 1400 and then from 1400 to 1500, each time we just changed the single json property in the file and it just worked without problems. 

We did it using SSDT and that was literally all it changed, so definately worth a shot unless anyone knows of any catastrophic issue it can cause.

**Comment by zenzeinet** [comment]
Hi,

FYI, you can update live directly from SSMS via xmla. Follow the
instructions below. Just be sure to have ssas2019 CU2 or later if you are
upgrading to comp 1500

https://www.thisintelligentlife.net/upgrading-ssas-tabular-2016-2017

**Comment by otykier** [comment]
[Version 2.11.0](https://github.com/otykier/TabularEditor/releases/tag/2.11.0) now allows you to modify the compatibility level of a model directly. Please note that AS still not not let you execute a CreateOrUpdate TMSL script on a database with a modified compatibility level. So in order to do an in place upgrade:

1. Open your model from the existing database, File > Open > From DB... (Ctrl+Shift+O)
2. Set the Compatibility Level to the new value under Model properties > Database > Compatibility Level (note, only upgrades are allowed!)
3. Save the model back to the database, File > Save (Ctrl+S)
