### ISSUE TITLE
Any way I can use the TOMWrapper outside TE?

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#430]
Hi, I'd like to write a "smart process" tool in PowerShell that you give the main table you want to process and a number of levels deep and it will traverse through the dependencies and process all the tables.

It occurred to me that it would be much easier if I could reuse the TOMWrapper that is in Tabular Editor. Is there a way that I can load the model to a wrapper outside Tabular Editor?

**Comment by otykier** [comment]
I haven’t tried, but since it’s a .NET lib, you should be able to create an instance of the TabularModelHandler class from TOMWrapper.dll directly from PowerShell. However, if your objective is to refresh calc tables after refreshing one or more base tables, a simple ProcessRecalc at the model level should take care of that. Or are you talking about refreshing tables based on following relationships?

**Comment by o-o00o-o** [comment]
Yeah, we have a big cube and usually for development we only want/need to process directly related tables to the fact that we are working on

What is the method to initialise the TOMWrapper with a folder? I think I've asked before but I think the TOMWrapper doc is out of date on the wiki, it would be great if this could be updated. I noticed the other day that the objecttype enum doesn't have calculation groups in etc.

**Comment by otykier** [comment]
`var handler = new TabularModelHandler("c:\\MyRepository\\MyAsDatavaseFolder`);
