### ISSUE TITLE
Allow running XMLA scripts

### ISSUE THREAD

**Issue by asocorro** [otykier/TabularEditor#433]
XMLA scripts can be generated but there does not seem to be a way of executing them.  Useful for copying objects from one model to another.

**Comment by otykier** [comment]
A better way of copying objects from one model to another is to have two instances of Tabular Editor running, and then simply pressing CTRL+C / CTRL+V to copy objects.

XMLA scripts are intended to be handed over to your DBA for deployment to Analysis Services - they are not intended for execution inside Tabular Editor. The reason is that the scripts could potentially contain refresh instructions and other operations not supported at the metadata level.

Alternatively, if you need to compare/synchronize two models, I recommend using another free tool called [ALM Toolkit](http://alm-toolkit.com/) which does just that.
