### ISSUE TITLE
error deploing directquery mode model to ssas 2019

### ISSUE THREAD

**Issue by Klimkiv** [otykier/TabularEditor#435]
1.make a dq mode model, level 1500
2. minimal actions, source, some tables
3. get this error
4.model is deploying anyway and seems working
5. after some time there is not 1500 label on ssas 2019 side

![image](https://user-images.githubusercontent.com/57611080/79101713-18a81a80-7da4-11ea-8f02-14ffeb7d7f2f.png)

**Comment by otykier** [comment]
This seems to be an issue with AMO/TOM, although I'm not completely sure.

Are you able to execute the following PowerShell script against the server without error? Note, this assumes you have the Microsoft.AnalysisServices

```powershell
## Replace with the path to the location where Tabular Editor is installed:
Add-Type -Path 'C:\Program Files (x86)\Tabular Editor\Microsoft.AnalysisServices.Tabular.dll'

## Replace with your server name or connection string:
$serverName = "YourSSASserverOrConnectionString";

## Replace with database name giving an error when compatibility level should be shown in Tabular Editor:
$databaseName = "PolPredDQ";

$server = New-Object Microsoft.AnalysisServices.Tabular.Server;
$server.Connect($serverName);
$database = $server.Databases[$databaseName];
Write-Host $database.CompatibilityLevel
```

**Comment by Klimkiv** [comment]
Daniel, good day
I've done the script but the same error was left
Deployment succeeded anywhay and no error if I deploy from VS
Thank you

**Comment by otykier** [comment]
[2.9.8](https://github.com/otykier/TabularEditor/releases/tag/2.9.8) contains an updated version of TOM/AMO. Could you please try this version and let me know if the issue perists?

**Comment by Klimkiv** [comment]
Daniel, good day
I've done with the new version but the same error persists
but all is working regardless of error

Daniel, 
may I ask you one question?

If you need to do a Power BI file with Direct Query and make it available on the PBIRS how would you do it?  
Build a model and link Power BI file to this model or build the Power BI file linked to SQL Server?
May be you know when composite models will be available in PBIRS?
it's not 1 question :)

thank you very much

**Comment by otykier** [comment]
@Klimkiv are you using on prem Analysis Services? In that case, which build number of SQL Server / AS? I believe this is a bug in the product itself, not in Tabular Editor. What happens if you try to script the PolPredDQ or PolPredDQ_v001 models through SSMS?

Regarding your question I'm afraid I don't have an answer - I've got close to no experience with DirectQuery and PBIRS. I also don't know the timeline for composite models in PBIRS, but since it's just been announced today for PBI Desktop, and will probably not hit preview until the fall, I wouldn't expect composite models to be available in PBIRS until next year.

**Comment by Klimkiv** [comment]
Daniel, good day
SSAS version 15.0.32.52 and PBIRS january  2020

thank you very much
