### ISSUE TITLE
command line -F flag

### ISSUE THREAD

**Issue by bbongagus** [otykier/TabularEditor#440]
Gello! thank ou for that great app, its saving a lot of time!

i have a question about -**F** flag:
I understand correctly, that it should work like a "Save to Folder" in GUI? Because when i specifyed that flag in CLI i got only **database.json** file without folders.

**Comment by otykier** [comment]
This is because of the serialization settings on the model.

Try to open the model inside Tabular Editor's UI. Then, go to File > Preferences > Current Model. Set checkmarks on the items that you'd like to have serialized into individual folders/files:

![image](https://user-images.githubusercontent.com/8976200/79425706-6306e280-7fc2-11ea-90ef-bcf91bcc6604.png)

This will add an annotation at the Model level. The annotation stores the preferences for the current model:

![image](https://user-images.githubusercontent.com/8976200/79425859-9cd7e900-7fc2-11ea-8321-d2abda93d2d9.png)

Save the model (CTRL+S).

The next time you run the CLI with the -F flag on this model, you should see the serialization happen according to the preferences you set.

Feel free to raise another issue if this doesn't solve the problem.

**Comment by bbongagus** [comment]
Great, understood. 
Yesterday i checked all types of objects and CLI -F works properly, but today i removed some types  and in annotations i still have all that was before. 
![image](https://user-images.githubusercontent.com/22669964/79553774-b1d97880-80a5-11ea-8599-8846ed3b54b0.png)

**TabularEditor_SerializeOptions**: `{"IgnoreInferredObjects":true,"IgnoreInferredProperties":true,"IgnoreTimestamps":true,"SplitMultilineStrings":true,"PrefixFilenames":false,"LocalTranslations":true,"LocalPerspectives":true,"LocalRelationships":true,"Levels":["Data Sources","Roles","Tables","Tables/Calculation Items","Tables/Columns","Tables/Hierarchies","Tables/Measures","Tables/Partitions"]}`


P.S. Can i build Model.bim file from CLI using folder, like "Open folder" in GUI?
