### ISSUE TITLE
 Get the pbix fullpath in the scripts

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#446]
Hello Daniel,
When Tabular editor is connected to a pbix instance, is there a way to get the pbix fullpath in the scripts ?
Thanks in advance !

**Comment by otykier** [comment]
I'm afraid this is not possible, as PBI Desktop does not store the path of the pbix anywhere within the model metadata, which is the only information that Tabular Editor has access to (since it's loading the model metadata through the XMLA endpoint provided by the AS engine running under PBI Desktop). PBI Desktop seems to use the name of the pbix file as the name for the AS instance, but this is as far as we can get ("AdventureWorks new.pbix"), but the full path is not available to us:

![image](https://user-images.githubusercontent.com/8976200/80035154-d7c0ac00-84ef-11ea-8a31-4c04137b6e85.png)

**Comment by otykier** [comment]
May I ask what scenario you have in mind, where you need to have this information within Tabular Editor?

**Comment by didierterrien** [comment]
I export translatable objects with a script. Then I import and translate them in Excel. While I'm in Excel, I would like to grab visuals metadata from the pbix file (visuals titles, visual header tooltips, textbox text, ...). So I will be able to translate them automaticaly in the same xlsx file. Visuals metadata translations will be read by the pbix file. Then I will be able to use measures in conditional formating.
I use Excel to simplify the validation process of translations. This is very important because automatic translations require validation for the initialization step but also for evolutions. Excel is perfect for validations because everybody is familiar with Excel and it provides powerful functionalities like search & replace, filters, colors,  ...
Pity that the model doesn't provide it's client which in this case is the pbix file.
As TE will be launched from the pbix file in the future "tools" menu, will it be possible to get its path ?

An other use case is the documentation of a model belonging to a pbix. I think it will be necessary to document the file also (full path, dates, size, creator, ...)
