### ISSUE TITLE
Default Source Column to have the name of the Column

### ISSUE THREAD

**Issue by awbarbeau** [otykier/TabularEditor#447]
As an enhancement, when creating a new column, can the Source Column property default to copy in the Name property of the Column object?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by otykier** [comment]
Tabular Editor generally doesn't set default property values on new objects that are created. This is by design, as people who are used to working with TMSL/TOM might otherwise complain that properties have been initialised unexpectedly.

There's a very easy solution, however. Once you've added all the data columns you need to a table, select all the columns and run the following script from the Advanced Scripting tab. You can even [save this script as a custom action](https://github.com/otykier/TabularEditor/wiki/Custom-Actions), to make it very easy to reuse.

```csharp
foreach(var c in Selected.DataColumns) c.SourceColumn = c.Name;
```
Alternatively, if you need to put brackets around the name, use this script:
```csharp
foreach(var c in Selected.DataColumns) c.SourceColumn = "[" + c.Name + "]";
```

**Comment by awbarbeau** [comment]
I think the solution you’ve proposed is the better option, thanks for the fast response! Please feel free to close this issue as resolved. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
