### ISSUE TITLE
Allow Sorting of Columns in Model Sort

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#46]
Hi,

it would be very much appreciated to able to sort columns. For attributes in dimensions this does not matter as they are ordered alphabetically. However, for columns in a fact table this is important, as the drill through depends on the model sort.

I would want to sort the following columns:
![grafik](https://cloud.githubusercontent.com/assets/908734/25305959/e15adce8-2784-11e7-9db9-894f4793f782.png)

Thanks a lot

**Comment by otykier** [comment]
Can you elaborate a little more what it is you'd like to achieve? Do you want to change the order of columns in the model metadata? I think the metadata order doesn't matter for client tools (Excel, Power BI), since they will always order attributes/hierarchies/measures alphabetically, so not sure what you would need this feature for?

**Comment by otykier** [comment]
Reading your comment again, I see you explicitly mentioned drillthrough, and for that it makes sense that the model outputs the columns in metadata order.

I will see what is feasible in Tabular Editor regarding changing column order in the metadata, and get back to you.

**Comment by otykier** [comment]
Hi Felix.
I noticed that the Column objects have properties called "Display Ordinal" and "Table Detail Position". Have you tried changing these, to see if that affects the sort order in which columns are outputted during drillthrough?
Best regards,
Daniel

**Comment by fmms** [comment]
hi @otykier,
no both of the above attributes just influence the default field set for PowerBI, for the drill through the only option is the sort in the Model.bim file.
For more information see my MSDN discussion: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/bf04f7fc-756b-459a-ae47-19c59764b993/how-to-change-sort-order-of-tables-and-attributes-in-ssas-tabular?forum=sqlanalysisservices#33c063ef-fbaf-405d-85bf-69f36da4bcca

Thanks

**Comment by otykier** [comment]
From the comments in the MSDN discussion, it seems that not even rearranging the columns in the metadata will solve the problem in all cases (another user mentions that you have to delete the database, restart the SSAS instance, etc.). For this reason, I am hesitant to add this as a feature to Tabular Editor, as I would like to keep everything in TE compliant with features supported by SSAS.

That being said, there is one workaround to rearrange columns inside the metadata, without actually editing the Model.bim file:
1. Make sure your "Save to Folder" preferences are set to save columns as individual .json files.
2. Save your model using "Save to Folder..."
3. Rename the files representing columns, such that you prefix them with a number to indicate the sort order you need, e.g.: "01 MaterialKey.json", "02 CustomerKey.json", "03 CalendarKey.json", etc...
4. Load the model from this folder structure in Tabular Editor and save it back as a normal Model.bim or deploy it to your SSAS instance.

When you use "Open from Folder", files are combined into the complete TOM in alphabetical order based on the filenames, but the filenames themselves are not used for anything in the model (the object names appear in the json inside the files).

Hopefully, this will make it easy enough for you to change metadata ordering, to cover the scenario you need. If Microsoft provides better support for column reordering in SSAS in the future, I will be happy to support this in Tabular Editor as well.

**Comment by fmms** [comment]
Hi,

I would very much prefer to just sort the columns by drag and drop directly in the bim file. We are doing this with a text editor for now. That the SSAS instance has to be restarted to reorder columns seems to be a  bug to me.

I think we are by now actually talking about two issues:
1. Reading this ticket I think this might be a conceptual problem of the "save to folder" as the conversion Model.bim -> jsons -> Model.bim rearranges all objects alphabetically. Maybe it would be a good idea to prefix every element with integer for the oder. i.e. 001-first.json, 002-second.json. Without that we wil not be able to use it.
2. Even if client tools do sort the columns I see a value in having being able to arrange the model sort to logically group them. For example to allways have the key in the first column and technical columns just used for internal measure definitions of the table.

Thanks

**Comment by otykier** [comment]
The reason I'm a little hesitant to add this feature, is that the TOM does not expose any properties or methods that can be used to manipulate the column order in the metadata. So far, Tabular Editor's code does not directly modify the JSON of the Model.bim file anywhere - all changes go through the TOM. One exception of course, is the Save to/Open from folder, but this has been designed in a way that carefully ensures that a Model.bim -> Folder -> Model.bim conversion always yields the exact same JSON as before **except that objects may be rearranged alphabetically due to the order that files are read**.

So if I should stick to this design decision, I cannot offer drag and drop functionality in the UI (in fact, the UI or the TOMWrapper library behind the UI doesn't even know about the JSON data - it only knows about the TOM). What I can do, however, is to prefix all files outputted with the "Save to folder..." functionality with a number indicating what their current order in the metadata is. This preserves the order when the folder structure is loaded back in, and better yet, it allows you to change the order permanently, by simply changing the prefixes.

To accomodate your point #2, I would be happy to add an option in Tabular Editor that at least makes sure that objects are displayed in metadata order, instead of alphabetically.

How does this sound to you?

**Comment by fmms** [comment]
that sounds good to me.

**Comment by otykier** [comment]
Hi Felix,

A new toggle option has been added to the toolbar (and inside the "View" menu). This allows you to toggle between alphabetical ordering, or metadata ordering. Default is alphabetical:

![image](https://cloud.githubusercontent.com/assets/8976200/25519041/8f6736cc-2bf6-11e7-8c6b-eca3330ff26a.png)

Additionally, in the preferences dialog under the "Save to Folder" tab, you can now choose to have metadata order indices prefixed to every filename that is outputted. This ensures that objects are added to the metadata in the same order as they were stored, and it let's you change the metadata ordering by changing the prefix on the files:

![image](https://cloud.githubusercontent.com/assets/8976200/25519080/b6350b44-2bf6-11e7-9f23-a3dc2af21ad0.png)

![image](https://cloud.githubusercontent.com/assets/8976200/25519126/e2fbe5c6-2bf6-11e7-81fc-f6309ed0915f.png)

This is available in the latest release, [build 2.3.6327](https://github.com/otykier/TabularEditor/releases/tag/2.3.6327).
