### ISSUE TITLE
Commandline deployment crashes if target database does not exist

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#47]
Hi,

I just tried to deploy with the TabularEditor commandline 
```
C:\Users\fmoeller\Desktop\TabularEditor.exe  my.bim -D server newDatabase -O
```

This results in a crash:
```
Tabular Editor 2.3.6321.31331
--------------------------------
Loading model...
Dependency tree built in 90 ms
Deploying...
Deployment failed! Object reference not set to an instance of an object.
```

Felix

**Comment by otykier** [comment]
I'm not able to reproduce this error. Could you send me a copy of the .bim file you are trying to deploy? Does deployment through the UI work?

**Comment by fmms** [comment]
Will reply on wednesday the latest, will have to produce a minimal test case or remove some information from the files.
Thanks for your fast replies.

**Comment by fmms** [comment]
Hi @otykier for me it never works. I created a very simple model with just a single table and it crashes as well:
[TabularProject1.zip](https://github.com/otykier/TabularEditor/files/958452/TabularProject1.zip)

I do nothing but execute the deploy.bat within the zip file.

What information do you need to further debug this? I could run any special version with more logging, etc,

**Comment by otykier** [comment]
Hi Felix - thanks for taking the time to create a simple test case, this helped me identify the issue. It turned out to be a bug that occurs only when you deploy a model that has no roles through the command-line or with the "Deploy Roles"-option unchecked in the Deployment Wizard.

Resolution options:
* [Download latest pre-release build](https://github.com/otykier/TabularEditor/releases/tag/2.3.6325) or
* Add an empty role to your model

**Comment by fmms** [comment]
works indeed. Thanks.
