### ISSUE TITLE
Creating a relationship with a calculated table fails

### ISSUE THREAD

**Issue by basland** [otykier/TabularEditor#484]
I created a calculated table in my model, added the column coming from the DAX query that defines the calculated table. 

Then I want to create a relationship with another table in my model, and get the following error during deployment: 
"Relationship __hex code__ uses an invalid column ID 16056" where actually the code generated looks correct.
I serialised my model, and the generated JSON file for the relationship is fine. 
The server I want to deploy to is SSAS 2019.

Please help. Thanks in advance.

**Comment by otykier** [comment]
Thanks for reaching out. I suspect this is because of a change in the DAX expression on your table, causing one of the columns participating in the relationship to be "deleted" during deployment.

This can easily happen if you're not connected to AS while developing the model (i.e., you loaded the model metadata from a .bim file or a .json folder structure), as Tabular Editor has no way to parse the DAX expression to determine which CalculatedTableColumns should be added, so you have to manually add the CalculatedTableColumns and assign their SourceColumn property.

Could you please test the DAX expression of your calc table in a tool like SSMS or DAX Studio, and make sure it outputs **exactly** the same column names as those specified in the SourceColumn property of the columns defined on your calc table:

![image](https://user-images.githubusercontent.com/8976200/84225351-34e3e180-aadf-11ea-9679-67821d8de6d3.png)

Alternatively, if you connect directly to AS (File > Open > From DB...), add the calc table to the model with a DAX expression, and without explicitly specifying the CalculatedTableColumns, then Tabular Editor should update the list of columns when you hit File > Save (CTRL+S).

**Comment by basland** [comment]
I did load the model from a JSON folder indeed. The strange thing is, I created the query in DAX Studio before creating the calculated table to make sure the statement was valid. Anyway, you suggestion of working directly on the database seems to work. Maybe there was a typo in my column source after all. Thanks for the support!
