### ISSUE TITLE
Help us understand linq filter issues

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#491]
I wanted to filter for columns that were type int64 and also only if they were referenced by a measure that had a particular value in one of their annotations

I tried a few things around

```
:DataType == "int64" && ObjectType="Column" && ReferencedBy.Where(x => x.GetAnnotation("AutoDerivatives").Contains("%")).Count() > 0
```
etc.. not sure if it is even possible. Often it returns nothing but it isn't obvious whether it is returning nothing because there are no matches or whether the linq doesn't make sense/syntactically correct etc.

It would be good if we give an insane linq expression to tell us as much as possible so we can adjust. Right now we aren't told it isn't a good expression as the catch is empty! 

![image](https://user-images.githubusercontent.com/13693159/84681048-7df6c400-af2b-11ea-9744-1260b6ada8e1.png)

It would perhaps be good to provide some simple and complex examples to the user in this catch block and what is/isn't possible here to aid discovery and learning. I've found this a few times when I wanted to do non-trivial filtering and it would really help.

**Comment by otykier** [comment]
Good point. Will consider showing an error message if the linq filter does not compile against any of the types of objects considered.

On your particular expression, there are two issues:

1. The ReferencedBy object is a list of IDaxDependantObject. These do not necessarily have annotations, so the call to GetAnnotation cannot compile. There is a syntax in Dynamic LINQ for performing explicit casting, but since you're only interested in measure references, you can use the `.Measures` property of the ReferencedBy object, to only get the list of all measure referenced.
2. In Dynamic LINQ, we don't use lambdas. Instead, everything you type inside the LINQ functions (Where, Any, Select, etc.) is evaluated directly against the base object of the collection, so change `.Where(x => x.y)` to `.Where(y)`.

One additional (minor) thing is that `.Where(x).Count > 0` is identical to `.Any(x)`:

```
:DataType="Int64" && ObjectType="Column" && ReferencedBy.Measures.Any(GetAnnotation("AutoDerivatives").Contains("%"))
```

**Comment by otykier** [comment]
Error message when LINQ cannot compile against any of the searched object types is now in [2.11.0](https://github.com/otykier/TabularEditor/releases/tag/2.11.0). Thanks for reporting!
