### ISSUE TITLE
Roles & RLS Advanced Scripting Output

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#512]
When I run the script below, it shows a visible row for each table that has RLS - and also a hidden row for each table that doesn't have RLS. I believe it should only show rows for tables that have RLS, correct? You can see how in the screenshot, the Geography table's RLS shows in the second row position. There are 2 more 'hidden' rows below it if you click on them (to complete the 4 tables in the model).

Model.Roles["Reader"].RowLevelSecurity.Output();

![image](https://user-images.githubusercontent.com/29556918/86053384-1713f780-ba61-11ea-9c56-0ea64dfe9ee3.png)

**Comment by m-kovalsky** [comment]
Using this to capture which tables and which roles have RLS. I think the code below should do the job but the where clauses don't actually filter anything because of the issue pointed out in my earlier comment.

foreach (var t in Model.Tables.Where(t => t.RowLevelSecurity.Count()>0))

foreach(var r in Model.Roles.Where(r => r.RowLevelSecurity.Count()>0))

Thanks!

**Comment by otykier** [comment]
The issue here is that the RowLevelSecurity object on the role holds an empty string for all tables in the model where RLS has not been applied. Same thing for the RowLevelSecurity object on tables (which holds an empty string for all roles in which that table does not have RLS).

This is by design, since the RowLevelSecurity object simply indexes the available TablePermissions. You can get the specific RLS expression for a table and a role by typing `table.RowLevelSecurity[role]` (or `role.RowLevelSecurity[table]` which does the same thing). The result is a string. If it is null or empty, no RLS has been set up for the combination of that table and role.

The following script loops through all combinations of tables and rows, outputting the RLS expressions that have been set up:

```csharp
var rlsInfo = "";
foreach (var t in Model.Tables) {
    foreach(var r in Model.Roles) {
        var rls = t.RowLevelSecurity[r];
        if(!string.IsNullOrEmpty(rls)) {
            rlsInfo += "Role " + r.Name + " RLS on table '" + t.Name + "': " + rls + "\r\n";
        }
    }
}
rlsInfo.Output();
```

**Comment by m-kovalsky** [comment]
Ah got it. Actually I just did the same workaround with the !string.IsNullOrEmpty(rls) :)

Thanks!
