### ISSUE TITLE
Help with deployment Script

### ISSUE THREAD

**Issue by fmms** [otykier/TabularEditor#52]
Hi,

this is not an issue but just asking for some advice -- adding some links so this is helpful for others in the future.  I am currently looking into automatic deployment (https://github.com/otykier/TabularEditor/wiki/Advanced-features#command-line-deployment)  and have some questions about the script (https://github.com/otykier/TabularEditor/wiki/Advanced-Scripting).

* I'd like to change the DataSource Connection String during deployment. `Model.DataSources["DWH"]` does not seem to have any usefull attributes. How can the connection String be set?
* I'd like to set `Model.Description` with the current time and user name. Is this possible?
* Is there any way to set the Database Description? I can see this in SSMS. However, to my understanding in tabular I am scoped to the model...?
* Is my understanding correct, that processing the cube is out of scope of tabular editor? (cf #22)

Thanks for your help.

**Comment by SQLBent** [comment]
Hi,

the first two questions is definitely possible. For the remaining two you will have to get your handsdirty and use PowerShell to do the scripting yourself.

1) When editing the datasource you should ensure to cast the object to a ProviderDataSource. Due to the introduction String should ensure to be casting the object to ensure that it is ProviderDataSource:
(Model.DataSources["DWH"] as ProviderDataSource).ConnectionString = "<ConnectionString>";
2) Setting the model description is possible by using the advanced scripting functionality:
Model.Description = "Test"
3) @otykier will get back to you on this one in more details.
4) Processing is not a feature of the Tabular Editor. There are multiple option to process the model by either using PowerShell (i have added an example below)

At the moment  i am working on some more detailed blog posts on how to utilise these features together with automated deployment. Stay tuned for the beginning of next week.

In case you have any further questions do not hesitate to reach out.

```
# Environment definitions

$TABULAR_SERVER = "Servername"
$TABULAR_DATABASE = "ModelName"

# Connect to modelet

[Reflection.Assembly]::LoadWithPartialName("Microsoft.AnalysisServices");
[Reflection.Assembly]::LoadWithPartialName("Microsoft.AnalysisServices.Core");
[Reflection.Assembly]::LoadWithPartialName("Microsoft.AnalysisServices.Tabular");
$as = New-Object Microsoft.AnalysisServices.Server
$as.connect($TABULAR_SERVER)
$db = $as.databases[$TABULAR_DATABASE]

# Update model

$db.Process();

# Save changes

$db.model.SaveChanges();

```

**Comment by otykier** [comment]
Thanks @SQLBent 

As for point 3, it is currently not possible to set this through Tabular Editor, as the Database object is not currently accessible in TE (it's read-only). I will look into the possibilities of making this object accessible in TE. However, if you're going to use PowerShell anyway to process the model or parts of it after deployment, you might as well use that to set the database description too. 

In @SQLBent 's example, you'd just have to add the following line before calling `$db.model.SaveChanges();$:
```powershell
$db.Description = "Your Description Here";
```

**Comment by fmms** [comment]
Thanks for your help!

**Comment by fmms** [comment]
Hi,
I have one more question. What do i have to do to actually get the model description CHANGED? It works perfect for the first time. However, on subsequent deployments it is not changed again. If i just change the name of the database I deploy to, it works again...

Any hints?

Overwritting connections works great (after adding -C...).

Thanks

**Comment by otykier** [comment]
Hi Felix
Not sure about the issue with model description. Can you provide a little more details on what you're doing? (Script and command-line syntax used).

**Comment by DanShrader** [comment]
I tried the example code for processing above and received this error at the `$db.Process();` step:

`This command cannot be executed on database 'ModelName' because it has been defined with StorageEngineUsed set to TabularMetadata. For databases in this mode, you must use Tabular APIs 
to administer the database.`

I checked and all of the options on the model 'seem' right, compatibility: 1200, direct query off.

Any thoughts?

**Comment by otykier** [comment]
Hi @DanShrader 
I need to investigate why Tabular Editor changes the value of the StorageEngineUsed attribute. As a workaround, could you try to edit your model.bim (or database.json if you are saving to a folder structure), before loading and deploying? It should look something like this:

```json
{
  "name": "MyDatabase",
  "id": "MyDatabase",
  "storageEngineUsed": "InMemory",
  "compatibilityLevel": 1200,
  [...]
```
In other words, explicitly setting the storageEngineUsed to "InMemory" should solve the problem.

**Comment by DanShrader** [comment]
Hi @otykier ,
First off - thanks for the response. I gave setting the storage engine direct a try, but got the following error in both TabularEditor and Visual Studio 2015

> Unrecognized JSON propert: storageEngineUsed. Check path 'storageEngineUsed', line 3, position23.

I don't think that its TabularEditor setting the property, because I tested a 'new' model which was purely in Visual Studio 2015 and thru PowerShell got the same 

> StorageEngineUsed set to TabularMetadata

error message when trying to use $db.Process(); 

I can call the the following:
```
$db.Model.RequestRefresh('Full');
Try {
    $db.Model.SaveChanges();
} 
Catch {
    $_.exception.Gettype().Fullname;
    $_.exception.Message;
}
```

Which triggers a process. I can also do the following:
```
$table = $db.Model.Tables.Find("TableName");
$table.Partitions.Find("PartitionName").RequestRefresh('Full');
Try {
    $db.Model.SaveChanges();
} 
Catch {
    $_.exception.Gettype().Fullname;
    $_.exception.Message;
}
```

I think that I'm just going to chock it up to the way that 2016 interacts with PowerShell.

**Comment by otykier** [comment]
Thanks for the details @DanSchrader.

@SQLBent, didn't you have a similar problem last week? Did you find a solution?
