### ISSUE TITLE
Refresh all the metadata and not only the model

### ISSUE THREAD

**Issue by Jin7281** [otykier/TabularEditor#532]
Hello,

I used the functionality "Refresh Table Metadata..." (it's very useful!) but the metadata of the calculated tables doesn't refresh.
Surprisingly, it's not a problem for Visual Studio. It refreshes the model code the next time we click on the save button.
But when there is a perspective that contains a calculated table, the metadata of the perspective doesn't refresh either and there is an error when opening the model in Visual Studio: `A PerspectiveColumn in table 'XXX' in perspective 'XXX' refers to a column 'XXX' that has been deleted`.

Is it possible to also refresh the metadata of the calculated tables and the perspectives with the functionality "Refresh Table Metadata..."?

Thank you!

**Comment by otykier** [comment]
The problem is that Tabular Editor currently is not able to parse the DAX of a calculated table, so it doesn't "know" which columns will result from a given DAX expression. Parsing DAX code to understand the static output is no trivial matter.

Say for example you have the following tables in your model, which are used to implement a role-playing date dimension:

- Imported table **Order Date** with columns such as [Date], [DateKey], [MonthName], [FiscalYear], etc.
- Calculated table **Due Date** with the following DAX expression (same columns as 'Order Date'):
  - `'Order Date'`
- Calculated table **Ship Date** with the following DAX expression (only two columns, [Date] and [DateKey]):
  - `SELECTCOLUMNS('Order Date', "DateKey", 'Order Date'[DateKey], "Date", 'Order Date'[Date])`

Let's say that you included all columns of each table in a perspective. Then, you modify the partition query of 'Order Date' in order to remove or rename a few columns. When you run the "Refresh Table Metadata" the following happens:

1. Tabular Editor detects that a number of columns have been removed from the source partition query, and deletes these columns from 'Order Date' accordingly. It doesn't know that the two calc tables may also be impacted. Of course, in our example, 'Due Date' would definitely be impacted, while 'Ship Date' would only be impacted if either [Date] or [DateKey] was renamed/deleted.
2. When Tabular Editor deletes a column, it also removes that column from participating in any perspectives. But this only happens for the imported table, so the column metadata for the two calc columns is unchanged at this point. Normally, this is not an issue, as Analysis Services would just get rid of column metadata for calculated table columns that are no longer present. But the issue here, is that you have a perspective that references these columns! And this is something Analysis Services can't fix on its own.
3. You try to save the model to an instance of AS, deploy it, or open the .bim file in Visual Studio (which causes an immediate deploy to your workspace database). You get the error shown, since the model metadata still specifies that the columns on the calc tables (which may have been removed), participate in a perspective.

To work around this limitation, make sure you delete all Calculated Table Columns (not Calculated Columns) from your model before saving the .bim file, whenever you made a change that could potentially impact the columns returned from the DAX expression on the calculated tables.

Alternatively, change your workflow to "connected mode", in which you open your model metadata directly from an already deployed (development) database. This allows you to view the impact on calculated tables immediately when hitting save (CTRL+S), as Tabular Editor retrieves the updated set of columns from Analysis Services after saving the changes.

Lastly, if indeed you're using calculated tables to implement role-playing dimensions, consider using imported tables instead. You don't gain anything by using calc tables for this, and your processing times may be slightly longer since calculated tables are only refreshed AFTER imported tables.

Feel free to reopen this issue or post a new one if you have any additional questions.

**Comment by KoenVerbeeck** [comment]
This is driving me insane. I've inherited a model with a lot of calc tables as role playing dimensions and changing anything in the base tables is a nightmare. Btw, you cannot delete a column from a calc table.

**Comment by otykier** [comment]
Hi @KoenVerbeeck
Working offline / metadata-only is tricky in Tabular Editor. No DAX validation and no automatic inference of data types, calc table columns, etc. You are not supposed to delete calc table columns manually (and as you've seen, Tabular Editor doesn't even allow this), since they are generated by AS based on the DAX expression on the table.

So as mentioned on twitter, this is a matter of workflow:

1. Ensure [automatic metadata backups](https://github.com/otykier/TabularEditor/wiki/Advanced-features#metadata-backup) are enabled under File > Preferences
2. The first time you open model metadata, you open the Model.bim file in Tabular Editor (or Database.json if you used folder-based serialization)
3. Then, deploy the model metadata as a new, empty database to an instance of AS. This is now your "workspace database".
4. Open that workspace database in Tabular Editor (File > Open > From DB...)
5. Make your changes - calc tables, measures, etc. Hit CTRL+S to synchronise the changes to the AS database. At this point, calc columns will get updated and you will be presented with any DAX syntax/semantic errors directly in Tabular Editor's UI.
6. If you decide to process your workspace database with actual data, you may even test the calculations using Excel or Power BI connected to the workspace DB at this stage, if you like.
6. When you're done working/making changes, and you want to persist the changes back to the source Model.bim or Database.json file, use File > Save as... or File > Save to Folder...
7. If you ever forgot to manually save to disk (step 6), just locate the metadata in the backup location that you specified in step 1. A backup file is generated whenever you hit CTLR+S while connected to the workspace database.

**Comment by KoenVerbeeck** [comment]
Hi Daniel,

thanks for taking the time to write this very complete answer :)
Connecting live to the SSAS Dev server works. However, when deploying to the UAT environment through CI/CD (which uses the ASDeployment Wizard), the deployment fails with the error "Failed to execute XMLA. Error returned: 'The column 'mycolumn' in table 'mytable' has invalid bindings specified." This was a calculated column which we replaced with a database column. Connecting live to UAT or Prod is not an option. (why is deploying Tabular so hard sometimes, just overwrite dammit).

**Comment by otykier** [comment]
This is unfortunately an issue with the AS Deployment Wizard. That is why I recommend to use Tabular Editor’s CLI for automated deployment. If you must use AS Deployment Wizard, you will have to perform two deployments: One where the original column is removed, then another deployment with the new column added to the model. Tabular Editor doesn’t have this issue as it generates a two-step TMSL script when detecting that a column has changed from calculated to non-calculated or vice verse.
