### ISSUE TITLE
Syntax error in partition

### ISSUE THREAD

**Issue by duanzy47** [otykier/TabularEditor#538]
Hello, I have a tabular model created in TabularEditor with tables' schemas copied from PowerQuery of Excel. After the creation of tables, each table was automatically associated with an empty partition, so I've tried to add the SQL query into the setting of partition. After all partition set-up done, I used the Deployment Wizard to deploy my model. However, I received always a syntax error in partition like `Syntax error in partition xx in table xxx. Token semicolon expected. Failed to excute XMLA`. 

I tried to deploy with and without putting a semicolon at the end of query, neigther of them worked. I supposed that there may be something else went wrong... One thing I noticed is that, the partition type is marked "m" (I think it is because I got the tables from PowerQuery m expression). But I found that it should be "query" in some SMSS tutorials. I want to know how can I change this type if this is the cause.

**Comment by otykier** [comment]
If you want to use a SQL statement directly in your partition queries, you must add non-Power Query partitions to your tables instead of the M Partitions. Please see this blog with instructions how to do just that: https://tabulareditor.com/2019/07/03/TabularEditorTricks2.html

Feel free to open a new issue if you have any questions or if you get stuck.

**Comment by duanzy47** [comment]
Thx for the reply. Problem solved ;)
