### ISSUE TITLE
Q: Difference between Private and Hidden for a selected table

### ISSUE THREAD

**Issue by JBJ2110** [otykier/TabularEditor#540]
What is the difference between the Private and Hidden fields when a table is selected? I have attached a screen shot below:
![Hidden vs Private](https://user-images.githubusercontent.com/12281621/88095178-aee99a80-cb62-11ea-888a-ce5f15e6ab4b.jpg)

**Comment by otykier** [comment]
I belive "Private" is not documented anywhere in the Analysis Services documentation. It may be used internally by Power BI Desktop. In any case, please use only the "Hidden" property, if you want to hide a table, column or measure.

**Comment by marcosqlbi** [comment]
Just some clarification.
When you enable Auto Date Time there is a DateTemplate calculated table that is used to create the automatic Date tables. This table is set to Private and it is never shown by Power BI.
The actual automatic date tables have Private=false and are not shown by Power BI because they are accessible through the Variations syntax (like Sales[Order Date].[Year] ).

If you mark a table as Private=TRUE, Power BI never show that table to the user, not even in the diagram view where you can see hidden tables.

**Comment by JBJ2110** [comment]
Thanks to you both. So appreciate the insight!

**Comment by danmeissner** [comment]
Putting a note here since I haven't found a better reference for what "Private" tables are used for...  

When using semantic link in Fabric notebooks, tables that are marked "Private" don't get exposed in functions like "list_tables" (likewise with included columns or measures in "list_columns" and "list_measures"
