### ISSUE TITLE
Saving Calculation Groups to pbix removes sigma symbols against integer fields

### ISSUE THREAD

**Issue by gooranga** [otykier/TabularEditor#544]
Hi,

I was experimenting with the new ability to add calculation groups to power bi desktop using External Tools functionality and I have noticed that when it saves the group it then removes all the sigma symbols against integer fields in th emodel so they cannot be used in visualisations on their own. They can continue to be used in measures without any problem. I don't get this when just adding measures though it's just calculation groups.

I am on the latest version of both power bi and tabular editor.

[https://community.powerbi.com/t5/Desktop/Tabular-Editor-edit-and-lost-sigma-icons-against-whole-number/m-p/1242516](url)

Below are before and after shots. Refreshing doesn't help and once this has happened I can't seem to get the sigmas back.

![error_evening](https://user-images.githubusercontent.com/18531348/88258321-c71efe00-ccb7-11ea-864f-32477ccaa0b2.png)
![error_evening_after](https://user-images.githubusercontent.com/18531348/88258318-c6866780-ccb7-11ea-93d8-23d527648c5a.png)

**Comment by otykier** [comment]
This is by design.

In order to add a calculation group to a model, the Analysis Services engine requires that the DiscourageImplicitMeasures-property on the model be set to False. Tabular Editor does this for you automatically when you add the first calculation group. Once this property is set to False, all numeric columns will no longer be treated as implicit measures by Power BI. This is perfectly fine, as the best practice is to create explicit measures anyway. By the way, these can [easily be scripted with Tabular Editor](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#create-measures-from-columns).

Check out the official [documentation for Calculation Groups](https://docs.microsoft.com/en-us/analysis-services/tabular-models/calculation-groups?view=asallproducts-allversions) for more information.

**Comment by marcosqlbi** [comment]
@otykier do you mean that DiscourageImplicitMeasures must be true to enable calculation groups?

**Comment by otykier** [comment]
Yes - I believe the engine throws an error if you try to add a calc group with DiscourageImplicitMeasures set to false.

**Comment by ArnonErez** [comment]
@otykier does that also affect text columns?
After adding a calculation group I can't put text columns as tooltips (or some other fields) in visuals.
Normally it'll automatically display "First [Column Name]".

**Comment by kadirkkkk** [comment]
Some visuals like Drilldown radial barchart stop working after creating calculation groups.

**Comment by otykier** [comment]
@kadirkkkk see #380. Long story short: This is an issue in Power BI Desktop.
