### ISSUE TITLE
Editing Power Query M Expressions on a .pbit file

### ISSUE THREAD

**Issue by lucb-pc** [otykier/TabularEditor#559]
I'm trying to edit a .pbit file and modify all table Power Query M expressions to change the data source database. It worked in theory because I can see the changes in the unzipped .pbit file in the DataModelSchema file.

But when I open the pbit file with Power BI Desktop, the old values are still there. 
How can this be explained ?

**Comment by otykier** [comment]
1) Are you using the Enhanced Metadata preview feature?
2) Do you see any references to the original database in the DataModelSchema file, after modifying the .pbit with Tabular Editor? If not, then it must mean that Power BI stores database information in other places than the DataModelSchema file, in which case you are out of luck, as this is the only content of the .pbit file that Tabular Editor can edit.

**Comment by lucb-pc** [comment]
> 1. Are you using the Enhanced Metadata preview feature?

Yes

> 2. Do you see any references to the original database in the DataModelSchema file, after modifying the .pbit with Tabular Editor? If not, then it must mean that Power BI stores database information in other places than the DataModelSchema file, in which case you are out of luck, as this is the only content of the .pbit file that Tabular Editor can edit.

The DataModelSchema file contains only the new string in the M expressions, no references to the old database. But when I open the pbit with Power BI and open the Power Query editor, the old expressions are still there.

So if I understand correctly this is just not supported yet ?

**Comment by otykier** [comment]
Editing PBIT files with Tabular Editor has never been supported :-)

So it would seem that they are indeed storing source metadata in other areas of the .pbit file, in which case there's nothing we can do from inside Tabular Editor. Maybe the [Power BI API](https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/updatedatasources) can help you (at least for pbit/pbix files that have already been published to the service)?

There's also [this article about hot swapping data sources](https://powerbi.tips/2020/05/hot-swap-power-bi-report-connections/), but this is also completely unsupported territory so use at your own risk.

Anyway, I'm closing the issue here, as this is outside the scope of Tabular Editor.
