### ISSUE TITLE
Report file fullpath in the external tools json file

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#561]
Hello Daniel,
Including external tools in Power BI desktop is amazing. 
At the moment, it is possible to include the server and database names in the command line of the application we launch. Is it planned to add the report file fullpath ? It could be great for layout analysis.
By the way, do you plan to add other information in the command line ?
Sorry, this question doesn't concern directly Tabular Editor.
Regards

**Comment by otykier** [comment]
There are no plans to add the file path as one of the parameters to be sent to the external tool.

The reason is that the pbix file format itself is proprietary, and Microsoft does not have any plans to document the format or the contents of the file. For this reason, they cannot support any tools that work by examining the contents of the file, even less so for tools that modify the file (I don't even think that's possible).

If you think this is a valid use case, please submit it as an idea to ideas.powerbi.com or raise it on the Power BI forums to gain attention.

**Comment by didierterrien** [comment]
Hello Daniel,
There are other use cases. External tools might save files or look for files in the directory where the pbix is stored. I will submit an idea and will ask to the community.
Have a good day
