### ISSUE TITLE
possible metadata mismatch?

### ISSUE THREAD

**Issue by ImkeF** [otykier/TabularEditor#566]
I'm missing annotations for a model in the newest TE version (2.11.7). 
They are simply not visible.

Also, when opening the workbook with a newer version of Power BI all the format strings that had been applied through TE will get lost. Turns out that the application of the format strings in TE had set the format-fields in the annotations to "Text".
As those measure formats were number formats, a possible mismatch would probably have caused them to be dropped, I could imagine.  (my version is 2.83.5894.881 and the delinquent version is  2.83.5894.961 ) 

Format strings are greyed out subsequently in the UI of PBI.

Anything that can be done about this?
Thanks!

**Comment by otykier** [comment]
In general, Tabular Editor does not touch the annotations on objects. Do you have calc groups in your model? I noticed that the data type on measures can sometimes change to “Variant” depending on the complexity of calc group calculations. If this happens, I’m afraid PBI Desktop has an issue where it treats all measures as Text, which would explain the annotation (since this annotation is entirely controlled by PBI).

You may be able to enforce the format string set in Tabular Editor by removing all these annotations from your model. You can do this easily using a script in TE:

```csharp
foreach(var m in Model.AllMeasures)
{
    m.RemoveAnnotation("Format");
}
```

Kindly let me know if this helps.

**Comment by ImkeF** [comment]
Thanks, you're a saviour ;)
Variants they are, indeed.

**Comment by otykier** [comment]
Regarding annotations not being visible - try to put a checkmark in "Allow unsupported Power BI features" under File > Preferences.

**Comment by ImkeF** [comment]
Thanks Daniel,
will test this out later on a sample file. But as long as working with customer files, I won't go the unsupported route.
Thanks for flagging it to the team!

**Comment by otykier** [comment]
Heads up: [2.12.0](https://github.com/otykier/TabularEditor/releases/tag/2.12.0) now ensures that all the numeric format string options are still displayed, even if measures have decayed to the Variant data type (where as previously, you could only set a custom format string in Tabular Editor). This doesn't fix the issue on the Power BI Desktop side, though.
