### ISSUE TITLE
Is there any news about retaining credentials when not deploying connections?

### ISSUE THREAD

**Issue by samusaran** [otykier/TabularEditor#596]
I'm currently using Tabular Editor functions for unattended deploying of tabular models, but we currently have a problem about passwords.

We have strict regulations about saving passwords somewhere to be used by scripts.
Is there any support from you or is it a limitation that cannot be overcome?

Thanks

https://github.com/otykier/TabularEditor/blob/5cd487a3de07c6b4b6a43d79bf8db241c0c0aa64/TOMWrapper/TOMWrapper/TabularDeployer.cs#L415

**Comment by otykier** [comment]
So far, I have not been able to find a way in which we can deploy a model (through TMSL or other means), with a Power Query data source, while retaining credentials stored in the server.

How are you orchestrating the automated deployment? If you're using Azure DevOps, for example, you should be able to store the credentials securely in a Key Vault, and then retrieve them as variables to be applied in a script during deployment. This is the standard approach that many of our customers are using, since it does not require you to store credentials in scripts or version control.

**Comment by samusaran** [comment]
Sadly we are 100% on premise. Right now we are using a C# CLI that basically wraps around your TabularDeployer, with the password being requested to the DBA every time, so that means that the utility is not 100% unattended, and that the DBA should know the password of every data source.

**Comment by otykier** [comment]
Being on-premise does not prevent you from storing passwords in a secure location, such as a key vault. In that case, you would have to augment your C# application to read the passwords from that location on-the-fly.

Of course, it would be better if we could just set the credentials once on the Tabular Model and then don't worry about it on subsequent deployments, but it just seems that it is simply not possible with Analysis Services. Credentials MUST be specified every time you deploy changes to a model. This is why we prefer to use service accounts, etc., whenever possible.

**Comment by samusaran** [comment]
Ok, that's fair.

Is there any builtin Windows key vault beside the Windows Credential Manager?

**Comment by otykier** [comment]
I’m unfortunately not knowledgeable in that area (windows key vault), but if you’re using a custom C# app anyway, which is executed by your DBA, why not prompt for passwords the first time, then store the passwords encrypted with the user key (this is standard functionality in .NET), so the DBA doesn’t have to enter the passwords next time the app is executed?

**Comment by samusaran** [comment]
Yeah that's the approach we might use, with either Windows Credential Manager or DPAPI.

Thanks for your suggestions.
