### ISSUE TITLE
Skip minor revisions when checking for updated version on startup

### ISSUE THREAD

**Issue by mario-octosgt** [otykier/TabularEditor#608]
Every time I launch Tabular Editor it checks for an updated version, which is great. The new releases have been pretty active lately (which is also great), but it has become annoying constantly having to update the software, or put up with the notification every time Tabular Editor starts (which is pretty often now with the Extenal Tools ribbon in Power BI).

A quality-of-life feature in Tabular Editor would be to be able to skip minor revisions from the auto update check on startup. This could be accomplished in two ways:
1. Having a checkbox in the preferences dialog to skip minor revisions on the auto update check on startup.
2. When the auto update dialog notifies about a new version, have the option to skip this update (and have it stop any further notifications until a newer version is available).

These current alternatives, none of which are ideal:
1. Update Tabular Editor every time a new version is released (including minor revisions, even if this is several times a week).
2. Decide to skip an update and put up with the (annoying) notification every time I launch Tabular Editor.
3. Turn off auto update check, and check manually every once in a while.

**Comment by otykier** [comment]
This is now fixed in [2.12.4](https://github.com/otykier/TabularEditor/releases/latest). You must put a checkmark in "Skip patch builds" to avoid seeing a notification on these releases. Semver is [Major.Minor.Patch], so 2.12.3 -> 2.12.4 is a patch update:

![image](https://user-images.githubusercontent.com/8976200/93223034-e85c1200-f76f-11ea-8b0a-3a4155ee5878.png)

**Comment by mario-octosgt** [comment]
Thanks!
