### ISSUE TITLE
Switch positions of the "Accept changes" / "Cancel changes" buttons in the Expression editor  

### ISSUE THREAD

**Issue by erapade** [otykier/TabularEditor#609]
**Is your feature request related to a problem? Please describe.**
When switching back and forth between tabular editor and the Power BI Desktop GUI the positions of the "Accept changes" / "Cancel changes" buttons are in the opposite positions, making it easy to push the wring button

**Describe the solution you'd like**
Since Tabular Editor now are kind of integrated with Power BI Desktop, it would be nice if these buttons are placed in the same order

**Describe alternatives you've considered**
Alternative just let it be as it is ;-)

**Additional context**
See attached screenshots
![image](https://user-images.githubusercontent.com/17324892/93171838-1e76a300-f72a-11ea-9804-9add7328e0ca.png)
![image](https://user-images.githubusercontent.com/17324892/93171922-3a7a4480-f72a-11ea-80c1-eeb9d2787835.png)

## Poll
Please use the 👍  or 👎  reactions to indicate if you agree or disagree with this change

**Comment by otykier** [comment]
This is one of those issues that is likely to break more workflows than it solves. Let's have a poll to determine what Tabular Editor users in general think:

/polls "Swap the Reject and Accept buttons to align UI with Power BI Desktop" "Keep the buttons as-is"

**Comment by marcosqlbi** [comment]
In PBI Desktop the "confirm" check is the nearest position to the cursor because the checkbox is on the left of the textbox.
In Tabular Editor the "confirm" check is above the textbox and not aligned - this means that it would be harder to center with the mouse cursor compared to the current position.
I would keep the UI as-is because even though the position is different if you read left-right, it is easier to find moving your eyes (and the mouse) from the textbox area. Moreover, changing this UI after 3 years is certainly going to break a lot of habits.
