### ISSUE TITLE
Errors during deploy when a data column is changed to a calculated column (or vice versa)

### ISSUE THREAD

**Issue by otykier** [otykier/TabularEditor#61]
If a data column is deleted and a calculated column with the same name is created on a table (or vice versa), SSAS will throw the following error upon deployment, or when changes are saved directly in the TOM:

`The JSON DDL request failed with the following error: Failed to execute XMLA. Error returned: 'The column 'TestColumn' in table 'TestTable' has invalid bindings specified.`

While it could be argued that this is a bug in SSAS, there could be a way for Tabular Editor to handle this, by first checking if any existing data columns have been changed to calculated columns (or vice versa) in the version which is about to be deployed. In that case, an intermediate rename of existing columns before deploying the new version, should avoid this error being thrown from SSAS.

Edit: Intermediate rename might not be the best option, when the model contains cultures/translations. Using TMSL, it is possible to change a column from type:"Calculated" to type:"Data", without renaming it. Maybe this approach could be used instead? Alternatively, investigate if there's a standard way to handle this through the TOM API.

**Comment by otykier** [comment]
Same issue applies to Calculated Tables. For example, if a regular table 'Table A' is renamed to 'Table B', and a new Calculated Table is created using the name 'Table A', then an error is raised from the TOM when attempting to save the changes. To workaround, temporarily rename the new calculated table to 'Table Ax', save changes and then rename it back to 'Table A'.

**Comment by otykier** [comment]
As of 2.7.4, this is no longer an issue (likely resolved in an updated version of the AMO/TOM)

**Comment by ZicoSailcat** [comment]
I ran into an issue where I was unable to deploy a tabular model to a QA environment.
In this particular case we were deploying through CI/CD, however, the issue was the same when we tried to deploy manually.

Description of the issue:

When deploying we got the following error. _The JSON DDL request failed with the following error: Failed to execute XMLA. Error returned: 'The column 'Column' in table 'Table' has invalid bindings specified._

What caused the issue it turned out was that the existing model we were trying to overwrite had a column name “Column” which we had replaced by a calculated column with the same name. So basically, the same error as described above only with columns instead on tables.

In this case we handled the fix manually by connecting to the existing model and changed the name to “Column1”. Afterwards we were able to deployment without any errors.

**Comment by otykier** [comment]
This issue has now been fixed in [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6) for both calculated columns and calculated tables.

**Comment by ZicoSailcat** [comment]
Fed! Du er en guttermand! Nogle ville sige MVP 🥳

________________________________
Fra: Daniel Otykier <notifications@github.com>
Sendt: lørdag, oktober 19, 2019 3:17 PM
Til: otykier/TabularEditor
Cc: ZicoSailcat; Comment
Emne: Re: [otykier/TabularEditor] Errors during deploy when a data column is changed to a calculated column (or vice versa) (#61)


This issue has now been fixed in 2.8.6<https://github.com/otykier/TabularEditor/releases/tag/2.8.6> for both calculated columns and calculated tables.
