### ISSUE TITLE
Installer download link not working

### ISSUE THREAD

**Issue by PhilippeCand** [otykier/TabularEditor#622]
Hi, I want to download the installer but nothing happen when I click the link.

**Comment by otykier** [comment]
This sounds like some network infrastructur/firewall/antivirus policy issues on your side. In any case, I'm afraid there's nothing I can do about it, since I'm just using GitHub for hosting the files. Are you able to download files from other GitHub repositories, for example [ALM Toolkit](https://github.com/microsoft/Analysis-Services/releases/tag/5.0.9)?

**Comment by otykier** [comment]
@PhilippeCand do you have an update on this or can we close this issue?

**Comment by PhilippeCand** [comment]
HI, I am able to download the installer, both the msi and the zip. Problem closed.

Thanks,

Philippe
