### ISSUE TITLE
-SC / -SCHEMACHECK with Power Query Data Sources

### ISSUE THREAD

**Issue by jasonhendrix** [otykier/TabularEditor#626]
Does -SC / -SCHEMACHECK work with Power Query Data Sources or is it planned for the future?

**Comment by otykier** [comment]
Schema check cannot be performed for Power Query data sources, since there is no way Tabular Editor can parse or execute the M partition queries. There is no plans to add this functionality, since that would require some kind of API that would allow Tabular Editor to interact with the Power Query / Mashup engine, and this is proprietary Microsoft technology which is not available for 3rd party usage.

**Comment by jasonhendrix** [comment]
Ok, thanks for the help!

**Comment by otykier** [comment]
**Update**: If your Power Query / M expressions are simply loading data from a SQL-based data source, without applying any transformations, you can use [this script](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#replace-power-query-data-sources-and-partitions-with-legacy) with the -S switch of the CLI, to transform the partitions into legacy partitions before running the schema check.
