### ISSUE TITLE
Right click context menu option to create relationship

### ISSUE THREAD

**Issue by liveandletbri** [otykier/TabularEditor#63]
When I right-click on a column, under the Create New sub-menu, it would be very useful if there was a Relationship option, so that I could quickly create a relationship from the column list rather than having to navigate to the Relationship section. Most often when I do this, I am clicking on the columns of a newly imported fact table, so it seems that the field I'm clicking on should default to populating the "From Column" property.

**Comment by otykier** [comment]
This is a good suggestion. I'm admittedly not too happy about the way relationships have to be created today.

Perhaps it would be even more useful, if the popup menu could be expanded like this:

```
Right-click on a column
   Create new >
        Relationship to >
              Table A >
              Table B >
              Table C >
                    Column 1
                    Column 2
                    Column 3
```

The submenus could be populated dynamically, based on the column you click on, so that only columns with a matching data type, and only columns in other tables than the current column are shown. This would make creating a new relationship more or less a one-click operation. Thoughts?

**Comment by liveandletbri** [comment]
That would be amazing! Love the pre-filtering to matching data types. My only concern is deciding which direction the relationship goes in. 

As I said above, I typically am clicking on the "From" and then the menu would have options for "To", but it's entirely possible that somebody is right-clicking the "To" and going the opposite direction. Maybe the default could be set to one direction and the relationship is flagged with a question mark to indicate it needs validation. Or maybe there is another option in the submenu ("Create New > Relationship From"?) that would allow the user to choose this on the fly.

**Comment by otykier** [comment]
New feature in latest build:
![image](https://user-images.githubusercontent.com/8976200/27773533-f43473e0-5f7b-11e7-9d6d-a6b819e75e12.png)
Only columns of matching data types in tables that are not already related to the current table are shown. Columns where part of the name matches the selected column will be shown at the top, as shown on the screenshot.
