### ISSUE TITLE
DAX Formatter - option to show error when there is an issue with the DAX

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#639]
**Is your feature request related to a problem? Please describe.**
When using the FormatDax() method, it would be great for it to be able to produce an error if the DAX is invalid. Currently it shows a message about invalid DAX in the bottom left of the screen.

**Describe the solution you'd like**
Perhaps this is already possible and I just don't know how to invoke the error message. If not, perhaps a parameter with such an option.

**Describe alternatives you've considered**

**Additional context**

**Comment by otykier** [comment]
The [current implementation of `FormatDax`](https://github.com/otykier/TabularEditor/blob/bf9e6d86bd29fb7733a5ad3f6aaf9edb9815649f/TabularEditor/Scripting/ScriptHelper.cs#L216-L232) absorbs all errors and returns the original DAX expression in case of an error. I'm hesitant to change this behavior too much at this point, since it could break existing scripts.

However, you can "go one step deeper" and call the [`FormatDax` method on the DaxFormatterProxy class](https://github.com/otykier/TabularEditor/blob/810fee59b92cf24e11f02534a336296604180b90/TabularEditor/UIServices/DaxFormatter.cs#L87-L99). This method does not handle errors, so if your DAX contains an error, the FormattedDax property of the returned object would be blank. So you can do the following:

```csharp
var myFormatDax = new Func<string, string>(orgDax => {
    var result = TabularEditor.Dax.DaxFormatterProxy.FormatDax(orgDax, useSemicolonsAsSeparators: false, shortFormat: true);
    if(string.IsNullOrEmpty(result.FormattedDax)) throw new Exception("Unable to format DAX");
    return result.FormattedDax;
});

// Throws an exception if Selected.Measure.Expression is not a valid DAX expression:
Selected.Measure.Expression = myFormatDax(Selected.Measure.Expression);
```

**Comment by m-kovalsky** [comment]
this is great, thanks!

**Comment by otykier** [comment]
So turns out I had to change the behaviour of `FormatDax` for the [reasons provided here](https://docs.tabulareditor.com/FormatDax.html), so above script will no longer work as of 2.13.0.

Closing this issue, however, since Tabular Editor V3 (coming soon) will make this obsolete.

**Comment by m-kovalsky** [comment]
Just to confirm - there's no way to modify the code you wrote above so that this will work in 2.13.0?

**Comment by otykier** [comment]
Well, anything is possible, but before I provide the solution I'd like to know how you're using the script.

Specifically, if you need to call FormatDax across many objects in a loop or in an automated/scheduled way. In that case, we have to be careful that we don't create one web request for each object, which is the very reason why I had to deprecate the FormatDax function in the first place.
