### ISSUE TITLE
DAX Formatter for all measures in model

### ISSUE THREAD

**Issue by marhyno** [otykier/TabularEditor#653]
Is there a way to run DAX Formatter for all measures in the model with one click ? If not this would be nice feature.

**Comment by otykier** [comment]
Save [this script](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#format-dax-expressions) as a custom action, to make it available as a single click. Or change `Selected.Measures` to `Model.AllMeasures` in order to run DAX formatter across all model measures (instead of only those that are currently selected).
