### ISSUE TITLE
Roles can be added to a PBIX data model, even when "Allow unsupported features" is disabled

### ISSUE THREAD

**Issue by tobimax** [otykier/TabularEditor#656]
Hi,

In Tabular Editor 2.12.4 when you have connected to a local PBIX Data Model.

When you add a new Role. It is called "New Model Role"

1. You cannot add expressions to it
2. You cannot rename it.
3. You cannot copy, edit the JSON and paste it back.
4. You cannot add roles using Model.AddRole("Role Name"); it just add a Role called "New Model Role"

Is it possible to have these capabilities in TE?

**Comment by otykier** [comment]
Thanks for reporting. 

The bug is that Tabular Editor even allows you to create the role in the first place, since model roles are not among the [supported write operation for Power BI Desktop external tools](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations). I will make sure this is fixed in an upcoming release, so that roles can not be added/modified/deleted, until this functionality is supported.

However - as with all other unsupported write operations - you can unlock everything by checking the "Allow unsupported Power BI features" under File > Preferences.

**Comment by otykier** [comment]
As an addendum, new role members can also be added but their properties can not be set.

**Comment by otykier** [comment]
[2.13.0](https://github.com/otykier/TabularEditor/releases/latest) has a fix such that role members cannot be added, unless "Allow unsupported Power BI features" is enabled.

**Comment by tobimax** [comment]
Thanks Daniel, I was able to get around this by using the Advanced Scripting to programmatically create the roles and filters with the "Allow unsupported Power BI features". It seems to work well even deploying to Power BI (Premium).

**Comment by otykier** [comment]
Yes, I believe the primary issue with adding roles to a Power BI model through Tabular Editor, is that it doesn't work if you publish the model to Power BI Report Server (see issue #649).
