### ISSUE TITLE
Incorrect display of dates

### ISSUE THREAD

**Issue by lzhang812** [otykier/TabularEditor#657]
After connecting to the Tabular Editor, the month number of dates for Today() function became like this "00/xx/xxxx". Day and Year numbers are displayed correctly. The month number only works correctly when I add the FORMAT() within the DAX. Anyone has any idea why this would happen? The dates were correct before I added a calculation group into the model. 

![Today Incorrect](https://user-images.githubusercontent.com/56655228/96748247-44c9d700-1397-11eb-8588-4a1468239dc3.JPG)
![Today Correct](https://user-images.githubusercontent.com/56655228/96748338-65922c80-1397-11eb-8b70-aa883bedc86f.JPG)

**Comment by otykier** [comment]
Most likely your calculation group contains one or more calculation items that may change the return type of your measures.

For example, if you have measures that return an `Integer` data type, and one of your calculation items does a year-over-year calculation with a division, then suddenly all of your measures would decay to return the `Variant` data type. Now unfortunately, measures with the `Variant` data type do not play well with Power BI formatting.

Other users have had been able to work around this, by removing the special "Format" annotation applied by Power BI: #566 and then specifying an explicit format string on the measure itself (using Tabular Editor).

**Comment by MHEnsslen** [comment]
I have the same issue.  
Upon first creating a measure returning a date I get this result...
![image](https://user-images.githubusercontent.com/60151451/99093761-ef04db00-25a0-11eb-95db-a42d544e8f55.png)

In Tabular Editor if delete the format I get the correct date (as it is reverting to the date field format)

![image](https://user-images.githubusercontent.com/60151451/99093909-1eb3e300-25a1-11eb-9fae-02c877f6d795.png)
![image](https://user-images.githubusercontent.com/60151451/99094042-4c009100-25a1-11eb-86c9-c1582663cbef.png)

Then if I go back to PBI Desktop and apply one of the formats, nothing happens, it still is in the format above.

![image](https://user-images.githubusercontent.com/60151451/99094295-9e41b200-25a1-11eb-95ed-4d4c14c0b716.png)

However, back in Tabular Editor the format now reads as I had selected.

![image](https://user-images.githubusercontent.com/60151451/99094501-e82a9800-25a1-11eb-990c-f78aad42eecc.png)

I then save changes in Tabular Editor (not actually making any changes, just saving).  Then refreshed my visuals in PBI Desktop, and now I have this result.  The Year and Day are correct per the formatting that I selected, but the Month is incorrect.  

![image](https://user-images.githubusercontent.com/60151451/99094789-49eb0200-25a2-11eb-819c-b01931d3822d.png)


If I go back to Tabular Editor and select from the Date Format dropdown, notice that it default highlights what I have entered EXCEPT the highlighted value has MM instead of mm.  Then scrolling through all of the available options, there are none with mm.  If my date field the measure is calculating against had a time, the minute number would be there in place of the 00 where month should be.
Selecting this new value yyyy-MM-dd does correct my issue and shows the datevalue for the measure in the format I selected.  

![image](https://user-images.githubusercontent.com/60151451/99094997-8fa7ca80-25a2-11eb-9ca9-b6527799bc8c.png)
![image](https://user-images.githubusercontent.com/60151451/99095348-06dd5e80-25a3-11eb-9029-a2b252e93260.png)


I do have calculation groups as part of my model, as I tried the same above without Calc Groups and didn't have the result, so I will try the suggested fix above as well.

My calculation group is to convert currencies between multiple formats.
`Expression: SELECTEDMEASURE()`
`Format String Expression: 
VAR MeasureFormat = SELECTEDMEASUREFORMATSTRING() 
VAR SkipConversion = ( SEARCH ( "$", MeasureFormat, 1, 0 ) > 0 )
RETURN
IF ( SkipConversion,
"$#,##0,.K",
SELECTEDMEASUREFORMATSTRING()
)`

**Comment by otykier** [comment]
I believe the February version of Power BI Desktop addresses the issue in how the dates are rendered in Desktop.

For now, please ignore the "Example" string in Tabular Editor, as this uses .NET formatting which is not exactly the same format string format used internally by Analysis Services.

If the issue is not solved, please feel free to reopen the question.
