### ISSUE TITLE
TabularEditor command line - partitions and scripts

### ISSUE THREAD

**Issue by mst42a** [otykier/TabularEditor#659]
I have 2 questions

**What are you trying to achieve?**
I want to deploy **only partitions**  using Command-line-Options is this even possible (without data structure)?

Can I provide multiple scripts in one command line?
For example, I have one script to modify partitions and a second to modify some columns properties. Something like?

"c:\Program Files (x86)\Tabular Editor\TabularEditor.exe" BI1-P-POZ\TABULAR STORES -SCRIPT "$(System.DefaultWorkingDirectory)\Tabular\TabularArtifact\s\ModifyWhereConditions.csx" 
-SCRIPT "$(System.DefaultWorkingDirectory)\Tabular\TabularArtifact\s\ModifyWhereConditions.csx" 
-D BI1\TABULAR DEPLOY_STORES -O -P -C -E -V

**Comment by otykier** [comment]
I suggest you create a new script that applies only the changes that you actually want to deploy (for example, adding new partitions, or modifying WHERE statements on partitions). Then, since you're loading the model metadata from the target model, you can simply use the `-D` switch without any additional parameters, to save the changes applied by the script, back to the target model:

`"c:\Program Files (x86)\Tabular Editor\TabularEditor.exe" BI1-P-POZ\TABULAR STORES -S "$(System.DefaultWorkingDirectory)\Tabular\TabularArtifact\s\ModifyWhereConditions.csx"
-D -E -V`

It's unfortunately not possible to execute several scripts in one CLI call. So either you'd have to combine the scripts into a single file, or run the CLI multiple times (however, in your example, it looks like you want to run the same script, ModifyWhereConditions.csx, several times?)

**Comment by mst42a** [comment]
In my example I paste two times the same scripts by mistake (but in certain I want to run 2 different); Unfortenatly i can't merge those scripts, because I use the first one also in my second pipeline where I don't want to make changes from second script.

I have one thought, if I first deploy 
"c:\Program Files (x86)\Tabular Editor\TabularEditor.exe" BI1-P-POZ\TABULAR STORES
-D BI1\TABULAR DEPLOY_STORES -O -P -C -E -V -SCRIPT "here first one"

then next

"c:\Program Files (x86)\Tabular Editor\TabularEditor.exe" BI1-P-POZ\TABULAR **DEPLOY_STORES** 
-D BI1\TABULAR **DEPLOY_STORES** -O -P -C -E -V -SCRIPT "here second one"

Logic:
from Stores -> to Stores Deploy script1
From Stores Deploy -> to Stores Deploy script2
those it should work as I expected?

**Comment by otykier** [comment]
Yes, as I mentioned above, one option is to run the CLI multiple times - once for each script. However, to ensure you don't get other structural changes from BI1-P-POZ over to BI1, you should load the model metadata from the destination database, and then use the `-D` switch without specifying a different destination (to only save metadata changes applied by the scripts):

`"c:\Program Files (x86)\Tabular Editor\TabularEditor.exe" BI1\TABULAR DEPLOY_STORES
-D -E -V -SCRIPT "here first one"`
`"c:\Program Files (x86)\Tabular Editor\TabularEditor.exe" BI1\TABULAR DEPLOY_STORES
-D -E -V -SCRIPT "here second one"`

You can do the above, or you can combine both scripts into a 3rd script to use with a single CLI...

**Comment by mst42a** [comment]
Thanks for clarification
