### ISSUE TITLE
Alternative for Dax Stuido DMV $SYSTEM.DISCOVER_CALC_DEPENDENCY in Tabular Editor

### ISSUE THREAD

**Issue by anbudhanush** [otykier/TabularEditor#663]
**What are you trying to achieve?**
In Daxstudio one can use select * from $SYSTEM.DISCOVER_CALC_DEPENDENCY to find all objects in the models used in measures.  This DMV does not work in daxstudio, if the pbix file has parameters. To find alternative, i tired this [advanced script ](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#exporting-dependencies-between-tables-and-measures).  It shows the Measure Name ,  Dependent Table Name. I wonder if this can also show the Column Name used in the measures.

**Comment by otykier** [comment]
Yes - absolutely. Here's an updated script that shows all direct dependencies for all model measures (tables, columns and measures).

```csharp
string tsv = "Measure\tObjectName\tObjectParentName\tType"; // TSV file header row

// Loop through all measures:
foreach(var m in Model.AllMeasures) {

    // Get a list of objects referenced by this measure (only direct references):
    var allReferences = m.DependsOn.Select(r => r.Key);

    // Output TSV rows - one for each table reference:
    foreach(var r in allReferences)
        tsv += string.Format("\r\n{0}\t{1}\t{2}\t{3}", 
            m.Name,
            r.Name,
            r is ITabularTableObject ? (r as ITabularTableObject).Table.Name : "Model", 
            r.GetType().Name
        );
}
    
tsv.Output();   
// SaveFile("c:\\MyProjects\\MeasureDependencies.tsv", tsv); // Uncomment this line to save output to a file
```

Note that there are some corner cases where this technique produces an incorrect result, since it's based on simple DAX tokenization, and not a full semantic analysis (like the CALC_DEPENDENCIES DMV). For example, if your DAX declares a temporary column with the same name as a measure: 

```dax
[Sales Amount less Tax] :=
SUMX(
    ADDCOLUMNS(
        'FactSales',
        "Sales Amount", 'FactSales'[SalesAmount] * 0.9
    ),
    [Sales Amount]
)
```

In this case, Tabular Editor would think that [Sales Amount Less Tax] depends on a measure named [Sales Amount] (if such a measure exists), even though the iteration refers to the [Sales Amount] temporary column. For this reason, a best practice is to [explicitly name temporary columns in a way to differentiate them from measures](https://www.sqlbi.com/articles/naming-temporary-columns-in-dax/).

**Comment by anbudhanush** [comment]
Awesome. Thanks a bunch. I works great and also thanks for flagging the limitation.
