### ISSUE TITLE
Formatting changes go away with Power BI monthly update

### ISSUE THREAD

**Issue by getwrenchy** [otykier/TabularEditor#666]
I have formatted many fields in a PBI model using Tabular Editor 2.12.4 by either changing the format type or by using advanced scripts on selected fields.  While the changes that I make work fine, when I install the monthly update to PBI all the fields resort back to their original and I must go back and reformat all the fields again after the update.

Ultimately I want to change many fields to simply stay as currency with zero decimals.  It seems that if tabular editor could change the format type in PBI to reflect currency then maybe it would stay after I update to a newer version of PBI each month.

See attached document with screen shots.

[Tabular Editor Bug - Formatting.docx](https://github.com/otykier/TabularEditor/files/5469359/Tabular.Editor.Bug.-.Formatting.docx)

**Comment by otykier** [comment]
Could you try to remove the "Format" annotation on the measures where you explicitly set the format string through Tabular Editor?

I think the issue is that Power BI Desktop stores some metadata in this annotation, and then upon model upgrade (which happens every now and then, when a new Power BI Desktop version is released), they basically revert the FormatString property based on the content of the "Format" annotation.

You can use the following script to get rid of the annotation on all currently selected measures:

```csharp
foreach(var m in Selected.Measures)
{
    m.RemoveAnnotation("Format");
}
```

You may need to enable experimental Power BI features under File > Preferences before you can alter the annotations on the model.

I would greatly appreciate if you can test this technique to see if this solves the problem once and for all. Thanks!

**Comment by otykier** [comment]
@getwrenchy do you have an update on this, or can we close this issue?

**Comment by getwrenchy** [comment]
> @getwrenchy do you have an update on this, or can we close this issue?

I was going to test during the next monthly PBI update.  In other words, save my model, do a bunch of formatting changes, upgrade to the next version of PBI, then see if that update removed all the formatting.  I don't see any other way to truly test since the only time I've had an issue is during every monthly update.

**Comment by getwrenchy** [comment]
Go ahead and close the issue.  Although this month's PBI Desktop didn't seem to impact the formatting changes, I believe your solution above would fix the issue.
