### ISSUE TITLE
Grouping Metadata

### ISSUE THREAD

**Issue by systemnova** [otykier/TabularEditor#680]
**What are you trying to achieve?**
I've enabled experimental features in tabular editor in the hopes of creating a calculated column that functions as a "groups/grouped data/binnedgrouping" column ie. contains grouping metadata in extended properties.

**What have you tried so far?**
I think the following script gets me close, but would love guidance on how to set the extended properties correctly.

var targetTable = Model.Tables["Table1"];
//targetTable.AddMeasure("Test3", "SUM(Table1[Column1])");
targetTable.AddCalculatedColumn("Test3", "SUM(Table1[Column1])");
targetTable.Measures[Test3].ExtendedProperties =

**Comment by otykier** [comment]
I'm not sure how the extended properties should be set, in order to mimic the behaviour of groups/bins created through Power BI Desktop, but you can use the `SetExtendedProperty` method to apply an extended property to an object.

ExtendedProperties come in two different flavours - strings and JSON values (however, it looks like Microsoft has removed the public documentation for these - I've no clue why!)

```csharp
// Use this to set a string value as an extended property:
targetTable.Columns["Test3"].SetExtendedProperty("ExampleString", "Value", ExtendedPropertyType.String);

// Use this to set a JSON value as an extended property:
var json = "{\"Property\":\"Value\"}";
targetTable.Columns["Test3"].SetExtendedProperty("ExampleJson", json, ExtendedPropertyType.Json);
```

Remember that you can also set Extended Properties through the UI - that might be an easier way to experiment:

![image](https://user-images.githubusercontent.com/8976200/99182789-6ec4ae00-2737-11eb-946c-15aee2a30985.png)

However, if you're working on a model in Power BI Desktop, you'd have to enable experimental Power BI features under File > Preferences before any of this will work. Always keep a backup of your .pbix file before making changes to it through Tabular Editor, once you enable experimental features!
