### ISSUE TITLE
Issue with M-Query View 

### ISSUE THREAD

**Issue by devaccount89** [otykier/TabularEditor#696]
In previous version of Tabular editor, there was an dropdown for to expand the m-Query of the current table. 
This is somehow missing in the current version which requires to the the changed m-Query a single line. 
Where the red box is, there was a drop down / expand window in the earlier versions. 
![image](https://user-images.githubusercontent.com/25116639/100464039-24471800-30cd-11eb-9b44-b452dbcb889d.png)

**Comment by otykier** [comment]
I don't think was ever a version where you could see a dropdown of the M Expression, but this is definitely an oversight. You're probably thinking of the Query property for legacy partitions, or the Expression property for measures, calculated tables, etc.

Anyway, I will provide a fix for this. In the mean time, remember that you can view the full M expression in the main editor by clicking on the partition in the explorer tree instead of opening the Partitions Collection Editor:

![image](https://user-images.githubusercontent.com/8976200/100874158-72309700-34a4-11eb-9a0b-29267bcf376e.png)

**Comment by devaccount89** [comment]
@otykier  Thanks a lot Daniel, that is exactly what I was looking for sorry for me overseeing this and bothering you. Form my perspective this is all what is needed :) 
Thank you.

**Comment by otykier** [comment]
Fixed in [Tabular Editor 2.13.2](https://github.com/otykier/TabularEditor/releases/latest)
