### ISSUE TITLE
BPA - apply custom fixes

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#721]
**Is your feature request related to a problem? Please describe.**
Allow the ability to create scripts which apply fixes or script fixes for a given BPA rule.

**Describe the solution you'd like**
Currently, the 'apply fix' or 'script fix' is only available for limited scenarios. It would be great to have the ability to write a script that can be associated with the BPA rule that can be executed to 'script the fix' or 'apply the fix'. The script would likely be saved as a custom action. Actually, it could just be an option to reference one of the custom actions.

**Describe alternatives you've considered**

**Additional context**

**Comment by otykier** [comment]
While I like the idea, I'm hesitant to add this feature without further investigation, as malicious users could use this feature to "hide" code inside a Best Practice Analyzer rule file or even inside an annotation of the model (since Tabular Editor allows rules to be stored as annotations).

So far, Tabular Editor does not allow execution of custom code unless you explicitly load a script into the Advanced Editor text box, or modify your CustomActions.json file. It would be too easy for someone to send a gullible consultant a Model.bim file containing a malicious piece of code hidden as a best practice fix and then say, "Hey could you take a look at this file". The consultant might then attempt to fix any best practice violations, not being aware that custom code would then be executing.

This is why the current restrictions on the "apply fix" functionality for the Best Practice Analyzer exists, since it only allows changing a single property.

So for now, I'll close this issue. If at some point Tabular Editor has an option to "warn" users before outside code is executed, I'll consider this (see discussion on #428).

**Comment by m-kovalsky** [comment]
I clearly see your point with regard to security. However, perhaps we can slowly expand the scope of the FixExpression. As an example, if there is a rule to catch single-partition tables where the partition name is different than the table name. The fix for this (to change the partition name to match the table name) is pretty simple however it currently isn't feasible. 

The code would be something like this:
Partitions[0].Name = Name

or this:

Partitions[0].Name = Partitions.[0].Table.Name

I think that things like this should be added (as long as security is not compromised). Essentially, right now it seems you're only allowed one reference to the object in question (the left side of the formulas above). A second reference is not allowed (the right side of the formulas).

Thanks!

**Comment by otykier** [comment]
[2.16.1](https://github.com/otykier/TabularEditor/releases/tag/2.16.1) now allows to use the `it` keyword in the FixExpression. This should allow you to create a FixExpression that sets a partition's name to the name of the parent table. See my comment on #846.
