### ISSUE TITLE
2.4 issue when opening

### ISSUE THREAD

**Issue by kalmenk** [otykier/TabularEditor#74]
When I open the program I get an error: 'The object does not have any child collections'

![tabeditsnip](https://user-images.githubusercontent.com/29556918/27744791-ccb6e670-5d75-11e7-9f60-c3f1c7ce9403.png)

**Comment by otykier** [comment]
This was fixed in the latest update to [version 2.4](https://github.com/otykier/TabularEditor/releases/tag/2.4). Turned out to be an issue with models containing KPIs (thanks @rwforest). I've added KPIs to my test model to hopefully avoid regressions in the future.

Feel free to reopen the issue if you have questions.
