### ISSUE TITLE
Unable to export to Power BI Desktop (.pbix) format

### ISSUE THREAD

**Issue by jasonlaw997** [otykier/TabularEditor#743]
Two months ago, I used the tabular editor to modify the dataset on the powerbi server, and the pbix file could be downloaded. Today I modified another dataset and found that it could not be downloaded. The information displayed was [Unable to export to Power BI Desktop (.pbix) format]
I simply modified a dax, [test:=1] ->[test:2]. The version of the tabular editor is 2.13.2.
What should I do to download the modified report?
Looking forward to your help

**Comment by jasonlaw997** [comment]
![image](https://user-images.githubusercontent.com/37357651/106102210-04d67500-617a-11eb-9b56-a827f3855677.png)

Last time I connected to the powerbi server dataset, I saw that the options are the same as the local file, but now they are different. Is there any way to change them to be consistent?

**Comment by otykier** [comment]
By "powerbi server dataset", are you talking about the Power BI Service (through the XMLA endpoint)? As per [this warning](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools#enhanced-metadata), you will not be able to download a dataset from the service, after making changes to it through the XMLA endpoint. It has nothing to do with Tabular Editor.

As for your second question: The differences shown in Tabular Editor is caused by the fact that Power BI Desktop [does not support all modelling operations](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations), so by default, Tabular Editor limits which properties you can change to only allow changing those that are actually supported by Power BI Desktop. You can unlock the full set of modelling operations by going into File > Preferences > Allow unsupported Power BI features, but keep in mind that this will let you make changes that are not supported by Power BI Desktop, which could potentially break/corrupt the pbix file or cause Power BI Desktop to crash.
