### ISSUE TITLE
Unable to Change Table Properties

### ISSUE THREAD

**Issue by cztaylor** [otykier/TabularEditor#75]
In SSDT I can update a Table Properites Query, which will then update the Annotaions, QueryEditorSerialization, and Partitions. In Tabular Editor, I have found how to edit Partitions, but I have not found any way to edit the Annotiations or QueryEditorSerialization.

**Comment by otykier** [comment]
Annotations are not currently exposed anywhere in the UI, but it is actually possible to access them by using the Advanced Scripting tab. Every object in the TOM that supports annotations has a GetAnnotation and SetAnnotation method.

You can use the following script to output the current value for the QueryEditorSerialization on the currently selected table in the Explorer Tree:

```csharp
throw new Exception(Selected.Table.GetAnnotation("QueryEditorSerialization"));
```
(In the current build, there is unfortunately no other way of outputting a message from a script, than to throw an exception - that is bound to change in a coming release.)

Another example, to change an annotation of a specific table, use the following code:
```csharp
Model.Tables["FactInternetSales"].SetAnnotation(
    "QueryEditorSerialization",
    "<New annotation value>"
);
```
Of course you have to put in a meaningful value for the QueryEditorSerialization, otherwise SSDT will not be able to properly show the Table Properties Query UI.

While I have no plans to support a query UI that automatically updates QueryEditorSerialization, I do however plan to expose all annotations in the Tabular Editor UI, making it easier to inspect and make changes to annotations as needed. I will let you know once this functionality is available.

**Comment by otykier** [comment]
Annotations have been exposed as a new property in [release 2.5](https://github.com/otykier/TabularEditor/releases/latest). Thereby, this issue will be closed.

Feel free to reopen the issue if you're still having problems.
