### ISSUE TITLE
How to deploy datasource credentials with model?

### ISSUE THREAD

**Issue by IvanovOleg** [otykier/TabularEditor#750]
**What are you trying to achieve?**
I would like to know if it possible to deploy Azure SQL database credentials to the powerbi service using the tabular editor? I don't want to add those credentials to each datasource manually.

**What have you tried so far?**
 I've created a basic model using the tabular editor with a legacy datasource that looks like this:
![tab](https://user-images.githubusercontent.com/9047397/106733511-a4808100-661a-11eb-9bfd-ea08b79dd629.PNG)
I can connect to the datasource in the tabular editor and import tables, but when it comes to the model deployment, I get an error in the powerbi service that the imported datasource doesn't contain credentials to access the database. I tried different impersonation modes, but without success.

**Comment by otykier** [comment]
I don't think the Power BI Service supports legacy data sources. You'll have to use Power Query data sources instead. Unfortunately you'll lose the ability to automatically import/refresh table metadata with Tabular Editor, since it can only do that for legacy data sources. However, there's a workaround: https://docs.tabulareditor.com/Importing-Tables.html#manually-importing-schema-metadata - another solution is to temporarily add the legacy data source just for importing tables/refreshing table metadata, and then change back to power query data sources once you're done.

**Comment by IvanovOleg** [comment]
@otykier  I've tried the next datasource configuration:
![tab2](https://user-images.githubusercontent.com/9047397/106744200-1f9c6400-6628-11eb-8796-0fb679b64885.PNG)
In the powerbi service, when I select parameters of the datasource I get the same notification about missing credentials.

**Comment by otykier** [comment]
Try to create a simple pbix file using Power BI Desktop, which imports just one or two tables from your Azure SQL Database. Then, publish that file to the PBI service and afterwards open the dataset in Tabular Editor to see how Power BI Desktop has configured the data source and partitions on the model. Then, try to mimic that configuration on the model you want to deploy with Tabular Editor.

**Comment by IvanovOleg** [comment]
@otykier I tried to create a sample pbix file with only one table imported in the powerbi desktop. I was able to authenticate a connection to an appropriate database there and publish that file to the powerbi service. When I open that datasource in the powerbi service I see the same credentials issue. I've tried to open that datasource using the tabular editor and the datasource section was empty.

**Comment by otykier** [comment]
Yes, indeed Power BI does not use Data Sources - instead, each partition query contains an M expression with the SQL server and database names, but without any credentials. The Power BI service manages the credentials entirely outside of the model metadata. But you should be able to use this same technique in your model, by specifying the partition queries in the same way as Power BI is doing. You could even create a shared expression in your model, so that you only need to store the server name and database name in one place, making it easy to switch i.e. between dev/test/prod SQL servers:

In Power Query, it would look like this:
![image](https://user-images.githubusercontent.com/8976200/106750405-19a68300-6628-11eb-999e-1b56f9384b5e.png)

In Tabular Editor, it would look like this:
![image](https://user-images.githubusercontent.com/8976200/106750506-3773e800-6628-11eb-839f-70819fb69afd.png)

**Comment by IvanovOleg** [comment]
@otykier Thanks for the information. I was able to update the datasource credentials using this [API](https://docs.microsoft.com/en-us/rest/api/power-bi/gateways/updatedatasource). I've added the datasource patch step to my pipeline right after the model deployment.
