### ISSUE TITLE
Prevent Model.Database.Name changes entering version control

### ISSUE THREAD

**Issue by gavingc** [otykier/TabularEditor#758]
Hi,

Tabular Editor "Save to Folder" on a Power BI Desktop model, serializes the database name.
This name is a generated GUID and changes on every restart of Power BI Desktop.

Seeking a way to prevent this change noise entering source version control, e.g. on Git commits.

In Git it's not particularly easy to ignore a single line change in a tracked file, and the database.json file is required to be tracked for the overall solution.

I've tried using Advanced Scripting to revert the name just before save to folder, but that seems to cause a cascade of problems.

**Comment by otykier** [comment]
Fixed in [2.14.1](https://github.com/otykier/TabularEditor/releases/tag/2.14.1). The "Save as Folder" will now use the name of the PBIX file as the database name when serialising the files, when the model metadata was loaded from an instance of Power BI Desktop. This should prevent noisy changes in your source control.

**Comment by gavingc** [comment]
That should work perfectly.

However something seems to be up with the build/release, as when I download the msi and (upgrade or reinstall), the new version number is shown but I'm not getting the new behavior. Also the release web page has some 2.14.0 change log blended into it. Let me know if I can provide any more info please.

PS. we are very much looking forward to grabbing a handful of floating licenses for Tabular Editor 3 when released.

**Comment by gavingc** [comment]
@otykier please see above.
Could this issue be reopened please, or a is it a new issue?

**Comment by otykier** [comment]
@gavingc sorry for not replying sooner. Turns out there was a bug in the implementation of this in 2.14.1, so that it doesn't work when you launch Tabular Editor through the External Tools ribbon of Power BI.

Until I get this fixed, could you please try the following:

1. Launch Tabular Editor directly
2. Open Power BI Desktop with the PBIX file you intend to store as a folder structure
3. In Tabular Editor, go to File > Open > From DB...
4. Choose the PBIX file in the "Local instance" dropdown:
 ![image](https://user-images.githubusercontent.com/8976200/108813110-a6ea5100-75b0-11eb-8161-1fcb3d1f6f47.png)
5. Now use File > Save to Folder...

This should cause the PBIX file name to be used as the "name" property of the database.json file, instead of the GUID generated by Power BI Desktop:

```json
{
  "name": "Procurement Analysis Sample PBIX",
  "compatibilityLevel": 1520,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US"
}
```

**Comment by gavingc** [comment]
No worries. GitHub doesn't have any better way to signal that an issue needs to be reopened other than mentioning / tagging a maintainer or raising a new issue.

Yes! Launching Tabular Editor directly does indeed perform the new behavior.

**Comment by gavingc** [comment]
Further, if using the file name, need to remove/cleanse special characters from the string.

I just ran into an exception where the file name contained a "+" symbol and this throws an unhandled exception.

**Comment by otykier** [comment]
[2.15.0](https://github.com/otykier/TabularEditor/releases/tag/2.15.0) should now work properly use the pbix file name as database name even when Tabular Editor is launched from PBI Desktop. In addition, invalid database name characters are automatically stripped.

**Comment by gavingc** [comment]
Confirmed working as designed Tabular Editor 2.15.1
