### ISSUE TITLE
tabular editor and SSDT?

### ISSUE THREAD

**Issue by TinyTimothy2** [otykier/TabularEditor#761]
Would there be issue if you use this tool AND SSDT for same project?

**Comment by otykier** [comment]
Generally no, however some users have reported issues with SSDT not being able to load a model that was initially created with Tabular Editor - this is most likely due to SSDT expecting certain annotations to be present on the file. If you have trouble loading a file in SSDT that was previously altered with Tabular Editor, you can always deploy the model metadata to Analysis Services using Tabular Editor, and then import the database to SSDT as a new project - that approach always seems to work.
