### ISSUE TITLE
Unable to load Relationships after Cloning a Table

### ISSUE THREAD

**Issue by JoeTombazzi** [otykier/TabularEditor#765]
Hello,

I created a script that clones a table (for ease in creating Role Playing dimensions). It will delete the table if it already exists, and optionally re-apply prior existing relationships. It runs great the first time, but if I try to re-run the script, it fails. If I save the .pbit and re-open it, I can once again run the script once, but it will once again fail the second time. 

**To Reproduce**
Run the attached script twice. Line 13 is where the failure will occur the second time the script is run, which I don't understand (error screenshot below). I would expect this script to be able to re-run as many times as you want?
[Clone Table Tabular Editor Script.txt](https://github.com/otykier/TabularEditor/files/5996231/Clone.Table.Tabular.Editor.Script.txt)

**Observed behavior**
![Error Message](https://user-images.githubusercontent.com/79208195/108216224-39e24180-7100-11eb-95cf-b5af742d6333.png)

**Application specifics**
 - Tabular Editor version: 2.14.7712.29256
 - Semantic Engine used: Power BI Desktop (version 2.88.1682.0 (20.12))
 - Model Compatibility Level: 1520

Thanks! Feel free to contact me for more info (jtombazzi@vizion360.com).

**Comment by otykier** [comment]
When I run the script against an Analysis Services (non-Power BI Desktop) model, it runs fine after multiple executions. However I had to change line 6 to: `if(Model.Tables.FindByName(newTableName) != null)` as I would otherwise get an unrelated error if there was no table with the name `newTableName`.

So I am pretty sure that the issue you're seeing is caused by the current limitations of the External Tools integration for Power BI Desktop. Specifically, adding tables/relationships is [not among the supported write operations](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-external-tools#supported-write-operations).

**Comment by JoeTombazzi** [comment]
Thank for the update! Understandable that the issue is caused by the current limitations of External Tools integration.
