### ISSUE TITLE
Use Service Connection Principal Context as Authentication from DevOps Pipeline

### ISSUE THREAD

**Issue by datadu-de** [otykier/TabularEditor#773]
Hi Daniel,

We're running deployments from Azure PowerShell Tasks in DevOps pipelines to dedicated capacities.

Instead of providing username/password from env variables/from key vaults it would be extra sweet/much easier, if the TabularEditor executable had an option to use the context of the service principal of the Service Connection that is selected in the pipeline task (see screenshot).

This user/Service Principal is already authenticated and authorized to deploy to the dedicated capacity workspaces we try to target. Also, the pipeline task is executed as this user anyways - so, as far as I can understand all of this authentication-voodoo, no further auth should be reuired if the context of the task can be "re-used"

![image](https://user-images.githubusercontent.com/49077745/108737780-3e10c380-7533-11eb-997e-c117a5162f6d.png)

Of course, this ties in perfectly with your post at https://tabulareditor.com/2020/06/02/PBI-SP-Access.html - which is exactly what we're trying to achieve, reducing the secret handling tremendously

Appreciate your thougts on this one!
Cheers and thanks,
Frank

**Comment by otykier** [comment]
So I'm not aware if there's any way an executable (TabularEditor.exe) can access the SP context of the pipeline in which it is being executed - will have to look into that. If someone can provide an example of how other tools do this, or maybe a PowerShell script, etc., that would be really helpful.

The reason I recommend using environment variables are that these are not logged anywhere, so one can safely pass credentials in these.

Even if the pipeline task is running as the authenticated user, then I don't think authentication can just work "out-of-the-box" since Tabular Editor still needs an access token to connect to the AAS/PBI XMLA endpoint. Integrated Authentication only works for Windows AD users, so fully seamless authentication would only work for a 100% on-premises set up (both pipeline agent and SSAS running on VMs connected to the same Windows AD).

**Comment by datadu-de** [comment]
Thanks for your feedback - I was not aware, that there is no method to "inherit" the execution context, and an access token will always be required, so it will never be seamless in a way as I imagined.

Handling of SPs is a quite struggle when dealing with dozens of projects in parallel with DEV/INT/UAT/PROD each which was the cause for this suggestion. However it still seems to be the best way forward.

Cheers!
Looking forward to TE3 :-)
