### ISSUE TITLE
Move Calculated Column to Data Column

### ISSUE THREAD

**Issue by debashish10** [otykier/TabularEditor#777]
**What are you trying to achieve?**
I am trying to convert all calculated columns to data columns by moving them to DB view side.
Name of the column is kept the same while moving to view.
While deploying the model and overwriting the existing model i keep getting the error as below :

![image](https://user-images.githubusercontent.com/55327056/109119020-1fe0d880-776a-11eb-8320-7a53efc7e73a.png)

Manual deployment also gives the same error.

**What have you tried so far?**
I tried a fresh deployment without overwriting and it works perfectly.
I believe this is the issue with AAS engine which is not able to bind columns properly.

I would like to get some advice on the best way to manage this change of Calculated columns to data columns in Tabular Editor when using a Power Query Data source in the model.

**Comment by otykier** [comment]
Which version of Tabular Editor are you using in your deployment pipeline? I made a fix to Tabular Editor a while ago, such that it would generate a two-step `createOrReplace` TMSL. The first step deletes the original object, the second step creates the new object. This was necessary since a `createOrReplace` TMSL can't change a column from being calculated to imported or vice versa in a single step (however, if memory serves, one used to get a different error message in that case).

In any case - make sure you're using the latest version of TE, and let me know if it still doesn't work. Perhaps try to export the TMSL using Tabular Editor's Deployment Wizard, and see if you can execute the TMSL without issue from inside SQL Server Management Studio - if that also doesn't work, it certainly hints at an issue with AAS, in which case you should reach out to Microsoft Support.

**Comment by debashish10** [comment]
@otykier  : In deployment p[ipeline we are not using the latest version of TE but in my local machine i have the latest version where i was getting the same error . I will do some more testing and let you know further.

**Comment by otykier** [comment]
Possibly related to #527
