### ISSUE TITLE
Error when adding a member to a hierarchy

### ISSUE THREAD

**Issue by kbl42** [otykier/TabularEditor#78]
When I click Add in Level Collection Editor, I get the following error:

"Constructor on type 'TabularEditor.TOMWrapper.Level' not found."

**Comment by otykier** [comment]
Thanks for reporting this. Could you try to add a level by dragging a column into the hierarchy instead? Alternatively, there should be an option for adding a column as a level in a hierarchy, if you right-click on the column.

**Comment by kbl42** [comment]
Thanks, both these options works.

But now I can't remove a column from a hierarchy. It seems the only way is
throgh the Level Collection Editor?
And when i remove a column there, and click OK, I get the following error,
and then all columns are removed from the dialog window.

[image: Billede indsat i tekst 1]

2017-07-13 10:06 GMT+02:00 Daniel Otykier <notifications@github.com>:

**Comment by otykier** [comment]
You should be able to remove a level from a hierarchy by simply deleting it in the tree. That is, select the level you want to remove and hit DEL or right-click and choose delete.

I think I enabled the Level Collection editor by mistake in the latest build. In previous builds, it wasn't available at all, but you could still get by using the tree. I'm not sure what benefits the collection editor has over directly adding/removing levels in the tree, so I might remove it again instead of fixing the current issues.

**Comment by kbl42** [comment]
I don't get a right-click menu on a level in a hiearchy, and nothing
happens, when pressing DEL.

2017-07-13 11:07 GMT+02:00 Daniel Otykier <notifications@github.com>:

**Comment by otykier** [comment]
That's also a bug in the latest release. Will provide a fix ASAP. In the meantime, you can use the following script to delete a level:

`Selected.Level.Delete();’

Run the script while the level you wish to delete is selected in the tree.

**Comment by otykier** [comment]
[Issue fixed in release 2.5](https://github.com/otykier/TabularEditor/releases/latest).

Feel free to reopen the issue if you're still having problems.
