### ISSUE TITLE
Export Model to PBIT, SSAS

### ISSUE THREAD

**Issue by tobimax** [otykier/TabularEditor#804]
Hi,

I would like Tabular Editor to be able to Export my Data Model to a PBIT, at the moment with Premium and Remote Models it is not easy to keep a local PBIX model in sync.

Also having a feature that could open a local PBIX or Remote Dataset and export to SSAS and vice versa would be really useful as well. 

Thanks

Toby

**Comment by otykier** [comment]
Are you requesting being able to export a SSAS model as a .pbit file? I'm afraid that's not possible, since a .pbit contains a lot more than just the data model, and Microsoft did not provide an API for creating blank .pbit files. Best you can do at the moment is copy/paste between instances of Tabular Editor (one with your SSAS model, the other with an existing .pbit file).

Migrating the other way is also not trivial, since Power BI adds modelling features that are not supported by SSAS. For example, they just added the LineageTag property (see issue #803), which is causing compatibility level issues, when added to a SSAS model.

I'd like to understand why you have the need to migrate back and forth between PBI and SSAS? I could understand if you had to do a migration from one to the other once for each model, which is where the copy/paste I mentioned above works well. But in general, this should not be something that you'd need to do very often (unless of course you have a large number of models that needs to be migrated).

**Comment by tobimax** [comment]
Thanks, I see what you mean. It would be nice to be able to develop a PBI model as a service locally (aka SSAS) with full model compatibility and then deploy to the remote PBI service when ready.
