### ISSUE TITLE
Integration with Source Control to ensure new items get added

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#82]
We are moving to Tabular Editor for the save to Folder capability which provides 3 way merging safety and simplicity.

However one tradeoff is that for new objects (tables, columns, measures etc) the files require remembering to "Add" to the workspace otherwise these parts of the model are forgotten on the merge. It would be great if somehow this could be solved as we have given safety and efficiency with one hand but taken away with the other.

Of course full source control integration might be overkill but some support for at least TFS and GIT would be greatly appreciated

**Comment by otykier** [comment]
Yes, we're facing the same issue internally at one of our clients. Since apparently this is a useful feature, I will investigate if there is some easy way to enable better source control integration with Tabular Editor. See also issue #67. Perhaps Tabular Editor can somehow "detect" that it's saving files back to a source controlled folder and then ensure that new files are automatically added to the TFS/git workspace. Will get back to you when I have an update.

**Comment by otykier** [comment]
Highly recommend using Git together with the Save to Folder option, as Git automatically detects file additions/deletions, where as TFS/TFVC does not... Tabular Editor will not get support for TFS/TFVC, as Git is the more popular source control system. Tracking Git integration on issue #104. Closing this issue.
