### ISSUE TITLE
Precedence of duplicate BPA rules when running via Command Line

### ISSUE THREAD

**Issue by alwortman** [otykier/TabularEditor#821]
I'm attempting to integrate BPA rules with our Azure DevOps build pipelines (using the -V param to output to the pipeline log). We have a custom rules file in source control that we run all models against. However, some model developers have already added rules to their .bim file directly.

What I'm observing is that when a rule is already defined in a .bim file, that rule takes precedence over the same rule in an external file. Specifically, the severity for that rule seems to be taken from the rule in the .bim file instead of the externally provided rules file.

Is this intended? Is there any way to ignore rules embedded in the model, or change which rules have priority in case of overlap?

**Comment by alwortman** [comment]
I found this from the documentation:
```
Note that the rule ID’s must always be unique. 
In case a rule within the model metadata has the same ID as a rule in the %AppData% or %ProgramData% folder, the order of precedence is:

Rules stored locally in the model
Rules stored in the %AppData%\Local folder
Rules stored in the %ProgramData% folder
```

So that _partially_ answers my question, now I think my request would be to make external file rules have the highest precedence.

**Comment by otykier** [comment]
With [2.16.0](https://github.com/otykier/TabularEditor/releases/tag/2.16.0), you can now use the -AX / -ANALYZEX flag instead of -A / -ANALYZE. This will cause Tabular Editor to only check the rules in the rulefile provided in the command line, and ignore any rules specified within the model.

I believe this is the best way to solve this issues, as model authors can always change the precedence order of rules defined within the model metadata. With the new flag, you can completely ignore rules specified in the model metadata, while providing your own external rule file.
