### ISSUE TITLE
Allow setting Open from Folder default open path and allow copy/pasting path

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#83]
It is no fun to have to use the "Open from folder" dialog that always starts from the desktop.

Please 
1. Change this to be a standard file open control and ensure folder selection. This will allow me to copy/paste folder into a box to save repetition, if I am already looking at the folder in Win Explorer
2. Allow setting a default path that this dialog starts at
3. (perhaps instead of 2) Remember the last location I was in

This would be a more beautiful user experience!  :-)

**Comment by otykier** [comment]
Great suggestions - will make sure they are put into the next release. By the way, did you know you can use the standard "Open from file" and then point to the database.json file in the root of your folder structure instead of using "Open from folder"? Perhaps this can be used as a workaround in the meantime.

**Comment by o-o00o-o** [comment]
Thanks for the tip on open from file. wasn't obvious although I have to change the type each time there (but is still better). Could this auto-detect to save having to select the type so that both .bim and .json are shown by default and you pick the deserialisation method according to the extension?.. just a though.
