### ISSUE TITLE
Syntax issue with saving a Custom Action 

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#833]
**Describe the bug**
Saving a custom action with a double forward slash in quotes (//) causes it to be stored in the CustomActions.json file with an error. This leads to issues when running Tabular Editor through the command line interface.

**To Reproduce**
1. Type the following into the Advanced Scripting window 

string urlPrefix = "https://google.com/";
string x = "hello";

2. Save this as a Custom Action
3. See how this is saved in the CustomActions.json file (when seen in Notepad ++ part of the code shows in red as shown below).

![image](https://user-images.githubusercontent.com/29556918/115702973-3bcfb780-a372-11eb-93fa-31a5fc5e9e33.png)

**Expected behavior**
I believe something needs to be changed with the way Tabular Editor handles this syntax when saving a Custom Action.

**Observed behavior**
This also causes a strange error when running Tabular Editor from the command line. However it doesn't actually error out and fail (which is good). See the issue below.

https://github.com/m-kovalsky/ProcessingManager/issues/2

**Application specifics**
 - Tabular Editor version: 2.16.0

**Comment by otykier** [comment]
Took me a while to understand what's going on. Turns out your ProcessingManager.cs file contains zero-width space characters (unicode 8203). For example try to copy [this code](https://github.com/m-kovalsky/ProcessingManager/blob/a657b23c80af5cd82c361120895bbaad61bc906f/ProcessingManager.cs#L845-L854) into a text editor.

Here, I'm using Programmer's Notepad with ANSI encoding, which turns the unicode 8203 char into a question mark:

![image](https://user-images.githubusercontent.com/8976200/115709105-142c1f80-a371-11eb-9bb3-8e7ee25adddc.png)

Same thing happens when Tabular Editor is running the script pre-processing, which explains the weird "token recognition error at: '?'" output (in fact, you get this output when running the script interactively as well, just try to launch TabularEditor.exe from a command line, then copy paste your script and execute it with F5).

Anyway, since there is no real error (the script / custom action is still being executed, after all), I suggest that you update your script to get rid of the zero-width space characters. In the mean time, I'll see if I can somehow make the script pre-processor ignore zero-width space characters.

**Comment by m-kovalsky** [comment]
Wow that's so weird. Not sure how they even got there. Thanks for catching this! I'll update the code.

**Comment by otykier** [comment]
Pre-compiler in version [2.16.1](https://github.com/otykier/TabularEditor/releases/tag/2.16.1) has been fixed, so it now properly ignores the zero-width blanks (same as the C# compiler used to actually compile the script).
