### ISSUE TITLE
Administrator role in tabular editor

### ISSUE THREAD

**Issue by maruthibo24** [otykier/TabularEditor#839]
**Is your feature request related to a problem? Please describe.**
It's will be a problem with large organization with 50 to 60 developers to control them on what features to use in tabular editor.
Example: if any body is using preview or unsupported features we cannot control them.we are aware that it's not a online service or something like other.
It's a small application but powerfull and very huge to.
And if use preview features or unsupported something might happens to datasets.then there wil be rework.

**Describe the solution you'd like**
Is it possible to create a role of administrator who can control what other users are using like restrict the preview features or others which we can do on bpa.

**Describe alternatives you've considered**
Then we need to give only to pro or advanced users only if there is no administrator to control.

**Additional context**
It will be helpfull for individual Powerbi users who works on maily import mode.

you can ignore if it doesn't make sense.😀
Just let me know if you need more information.
And understand my explanation.

Cheers,
MP

**Comment by otykier** [comment]
I don't have any plans to restrict what features Tabular Editor allows, since users will be able to work around these limitations using other tools or scripts. Remember that Tabular Editor doesn't let you do things that are otherwise not possible - it just provides an easy interface for the TOM API that Microsoft provides. [Related article](https://www.sqlbi.com/articles/development-tools-for-tabular-models-in-2021/).

However, if you would like to disable the External Tools ribbon inside Power BI, [that's possible to do with a Group Policy](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#disabling-the-external-tools-ribbon).
