### ISSUE TITLE
Adding Calculation Group Breaks Aggregated Columns

### ISSUE THREAD

**Issue by bobctown** [otykier/TabularEditor#843]
Adding a Calculation Group in Tabular Editor from Power BI Desktop breaks non-calculated measures. In PBI report view, the often-times hidden columns that are used to build measures have a Sigma next to them. They can be dragged into Values section of a visual and are aggregated. Opening in Tabular Editor, creating a simple Calculation Group, and saving, makes these Sigmas/aggregation types disappear. The columns can no longer be added to the Values section.

**To Reproduce**
1. Go to existing model in PBI Desktop report view.  
2. Right-click on the fields and select 'View Hidden' and verify Sigmas exist next to measure columns.
3. Go to External Tools-->Tabular Editor.
4. Right-click on Tables and add Calculation Group.
5. Save and the measures no longer have a Sigma or behave as metrics in Desktop.
6. Create a table visual and select a column that should be aggregated. It works in a table.
7. Switch the table to a bar or line chart. The fields are no longer aggregations.

**Expected behavior**
No change to metric behavior.

**Observed behavior**
Measure columns no longer have a Sigma or behave as metrics in Desktop.

**Application specifics**
 - Tabular Editor version: 2.16.0
 - Power BI Desktop version: 2.92.943.0 64-bit (April 2021)

**Additional context**

**Comment by jeffersonrand** [comment]
Yes, but the data model I submitted was an Import mode model.  I thought that this only applied to Live Connect.  In any case, I appreciate that it is best practice to not use implicit measures in the solution, but during development and validation, it is useful for users (not developers) to drag a column into a visual.  Perhaps MS recognizes this, since on their site, they say "at this time" when discussing this situation.  Thanks, Daniel, for your stellar work - I appreciate your reply.  Sorry I did not realize that this was already address here.
