### ISSUE TITLE
Tabular Editor not supporting create Hierarchy on Advanced Scripting

### ISSUE THREAD

**Issue by dirceuresende** [otykier/TabularEditor#852]
**Describe the bug**
I'm trying to create a new hierarchy using Advanced Scripting on Tabular Editor 2.16.1, but I receive an error message: CS0143 - The type "TabularEditor.TOMWrapper.Hierarchy" has no constructors defined

**To Reproduce**
1. Go to 'Advanced Scripting'
2. Try the following code: 
var h = new Hierarchy(){
    Name = "Test",
};

3. See error

**Expected behavior**
Tabular Editor allowing me create hierarchies dynamically. I'm using this post as an example: https://andydcutler.wordpress.com/category/analysis-services/tabular-object-model/

**Observed behavior**
Error message: CS0143 - The type "TabularEditor.TOMWrapper.Hierarchy" has no constructors defined

**Application specifics**
 - Tabular Editor version: 2.16.1
 - Semantic Engine used: Azure Analysis Services
 - Model Compatibility Level: 1500

**Comment by otykier** [comment]
Scripting in Tabular Editor is not entirely identical to scripting using TOM. The `Hierarchy` class in Tabular Editor, is a wrapper of the `Hierarchy` class in TOM, for example. Tabular Editor doesn't let you manipulate the TOM objects directly, because this would prevent Tabular Editor from tracking what changes have been applied, and thus features like Undo/Redo would not work.

One of the consequences of this, is that the TOMWrapper classes used by Tabular Editor's scripting, does not have constructors you can call. Instead, to create new objects, you will be able to find `.AddXXX(...)` methods on the parent object.

So for example, if you wanted to add a new hierarchy to table "MyTable", use the following code:

```csharp
var h = Model.Tables["MyTable"].AddHierarchy("Test");
h.AddLevel("Column1");
h.AddLevel("Column2");
```

See [Advanced Scripting](https://docs.tabulareditor.com/Advanced-Scripting.html) for more information.

**Comment by gregoryjkramer** [comment]
does being direct lake mode change anything about creating hierarchies w/ TE?

**Comment by otykier** [comment]
Not in TE2, but there could be limitations within DirectLake itself. Haven’t tested whether hierarchies actually work in a DirectLake model.
