### ISSUE TITLE
Saving a model with non-existing or renamed "source column"  does not throw an error

### ISSUE THREAD

**Issue by cosminioan** [otykier/TabularEditor#857]
**Describe the bug**

I am saving an SSAS Tabular 2019 (latest CU) model for which I know that for some attributes, the "Source Column" or "sort column"  has been renamed in the datasource (view),

Saving the model proceeds without any warning or error. Deploying a model with source column or sort column renames also produces no error.  What makes it harder is that even a full processing of the ssas cube throws a non-descript error message, such as:

Executed as user: xxx. Microsoft.AnalysisServices.Xmla.XmlaException: The current operation was cancelled because another operation in the transaction failed.   at Microsoft.AnalysisServices.Xmla.XmlaClient.CheckForSoapFault(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)   at Microsoft.AnalysisServices.Xmla.XmlaClient.CheckForError(XmlReader reader, XmlaResult xmlaResult, Boolean throwIfError)   at Microsoft.AnalysisServices.Xmla.XmlaClient.SendMessage(Boolean endReceivalIfException, Boolean readSession, Boolean readNamespaceCompatibility)   at Microsoft.AnalysisServices.Xmla.XmlaClient.SendMessageAndReturnResult(String& result, Boolean skipResult)   at Microsoft.AnalysisServices.Xmla.XmlaClient.ExecuteStatement(String statement, String properties, String& result, Boolean skipResult, Boolean propertiesXmlIsComplete)   at Microsoft.AnalysisServices.Xmla.XmlaClient.Execute(String command, String properties, String& result, Boolean skipResult, Boolean propertiesXmlIsComplete)   at Microsoft.SqlServer.Management.Smo.Olap.SoapClient.ExecuteStatement(String stmt, StatementType stmtType, Boolean withResults, String properties, String parameters, Boolean restrictionListElement, String discoverType, String catalog)   at Microsoft.SqlServer.Management.Smo.Olap.SoapClient.SendCommand(String command, Boolean withResults, String properties)   at OlapEvent(SCH_STEP* pStep, SUBSYSTEM* pSubSystem, SUBSYSTEMPARAMS* pSubSystemParams, Boolean fQueryFlag).  The step failed.

**To Reproduce**
1.  Change a source column in the view.
2.  Save the model. That should be invalid, for the table, at least throwing a yellow warning for the respective column, I would hope.

**Expected behavior**
Should at least get a yellow warning that the column no longer exists.

 - Tabular Editor version: [e.g. 2.16.0]
 - SSAS 2019 latest CU
 - Model Compatibility Level: 1500

many thanks for any thoughts,
Cos

**Comment by otykier** [comment]
Unless I'm misunderstanding your post, I'm afraid that validation of the source column is not possible to enforce on the client side. To validate the source column, Tabular Editor would need to be able to access the data source, execute the partition query and evaluate whether the resulting dataset corresponds to the source columns specified in the table.

For relational databases specified as legacy data sources in the tabular model, and where Tabular Editor can physically access the database, it is possible to [manually perform a schema check](https://docs.tabulareditor.com/Importing-Tables.html#refreshing-table-metadata), but there are many reasons why I don't want to enforce this check upon every deployment. For example, the client machine might not be able to physically reach the data source, due to firewalls, missing credentials, etc. or it could be a data source type that is not supported by Tabular Editor (remember that Power Query supports more than 100+ data sources, which is not something that's possible to re-implement in Tabular Editor).

If you happen to use a relational database as your data source, you should consider setting up automated build and deployment of your tabular model using Tabular Editor's command line interface, since this allows you to check the schema as part of a build pipeline, before performing a deployment. Read [this blog](https://tabulareditor.com/2019/02/20/DevOps1.html) for more information on that.

**Comment by cosminioan** [comment]
thanks bunches Daniel, for the thorough explanation.  Yes, this is helpful to mitigate the concern.  many thanks and keep up the awesome job.  Issue can be closed.
