### ISSUE TITLE
Deploying to on-prem SSAS tabular model whilst retaining data?

### ISSUE THREAD

**Issue by Acronarch** [otykier/TabularEditor#862]
**What are you trying to achieve?**
Hi, I'm new to Tabular Editor and fairly new to SSAS. Need help with deployment using Tabular Editor to an on-prem SSAS model.
I usually use MS Visual Studio 2019 SSDT to deploy my SSAS model to an on-premise SSAS server. Data is pulled/(processed full on partitions) from a seperate MS SQL server 2019 DB every 15 minutes throughout the day, so having live uninerrupted processing and live feed to the PowerBI dashboards throughout the day is important. Everytime I deploy with VS, data would be retained on the dashboards/SSAS model. I would only need to process full on newly added tables or new columns after deployment, all other data is retained.

Using Tabular Editor for the first time, I opened the model.bim file and deployed to the SSAS server. Noticed all charts on the dashbaords errored indicating that there is no data. I suspect that all data is cleared. Does this mean that I must always perform full-process on the DB after deployment? (issue is it would take 3-4 hours) Or is there a way around this? Maybe I'm missing something?

**What have you tried so far?**
I have deployed with only "Deploy Model Structure" ticked. Also tried with everything else ticked.

Forgive my ignorance,
Thanks in advance!

**Comment by otykier** [comment]
A couple of questions to clarify:

- Does the model.bim file hold the same partitions as are defined on the server? If not, be aware that if the "Deploy Partitions" option is checked, the partitions on the server (including the data) will be removed.
- If "Deploy Partitions" is unchecked or if the model.bim file holds the same partitions as those on the server, then a deployment could still cause data to be dropped or objects to become "unqueryable", in the following cases (there may be more):
  - A table is renamed
  - A columns is added to a table or renamed
  - Relationships are modified
  - Calculated column / calculated table DAX expressions are modified

Please note for the latter two items, it is usually sufficient to perform a "Calculate Refresh" on the server, since no data has been dropped, but some structures have to be recalculated before you can query the model (if you don't do this, Power BI dashboards would indicate an error).

**Comment by Acronarch** [comment]
Thank you! It’s working now.
