### ISSUE TITLE
Slow performance when right clicking on a Column

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#87]
When right clicking on any column in our model I get about a 10 second delay before the menu appears.

Measures are instant, calculated columns are <1 sec or so but Columns are frustratingly slow.

Not sure if it is the size of our model (120 tables, 5k measures) or this is general but let me know if you need anything to act as a repro

**Comment by TabularEditor** [comment]
I suspect this is due to the dynamic population of the "Create New > Relationship From/To > " submenu, which loops through all tables in the model as soon as you invoke the popup menu, to determine possible columns you would want to create a relationship from/to.

Will redesign this, so that the looping is postponed until you invoke the Relationship From / To submenu, so that you won't have a delay when right-clicking.

**Comment by o-o00o-o** [comment]
Yeah I thought this but also I suspect you need it for the delete to ensure that you aren't going to break any dependencies with the delete. So I guess you will also need to have this delay on the delete as well.

I wonder if an alternative design would be to spin off a background thread on load to build the dependency graph in memory to provide a fully responsive user experience. I guess this is a lot more work though.

**Comment by otykier** [comment]
The dependency graph is updated upon name or expression changes. The "Delete" action doesn't check the dependencies until it is actually clicked, so that shouldn't be an issue.
